### ISSUE TITLE
https://orbitdb.org redirects to https://njal.la/

### ISSUE THREAD

**Issue by woss** [orbitdb/orbit-db#1018]
did you guys forget to renew the domain?

https://duckduckgo.com/?q=orbit+db&t=brave&ia=images

![image](https://user-images.githubusercontent.com/80440/187494241-0031399a-3c65-432d-9940-6154ae0e9c8a.png)

**Comment by aphelionz** [comment]
It still resolved to the website for me?

**Comment by aphelionz** [comment]
Double checked the settings, everything seems fine

**Comment by woss** [comment]
now i tried and it resolves to https://github.com/orbitdb
