### ISSUE TITLE
Clarification about valid oplog entries and maximum oplog time 

### ISSUE THREAD

**Issue by DevGrammo** [orbitdb/orbit-db#1065]
As far as I understood, if an entry is in the `oplog` then it has a valid signature and that is the unique requirement the entry has to met in order to be appended to the log | given the additional requirements specified by the access-controller ruling the orbitdb database. 

I understand that a `CRDT` is not a blockchain, however it seems to me that an adversarial peer with write-access could easily manipulate the ordering by sending fake `clock.time`. This means that although we still eventually agree on the ordering of the events, the ordering is manipulable and hence not reliable in a convincing sense. That is my understanding. 

In addition, an adversarial peer might send a malicious `clock.time`  such as in the following example: 

```javascript 
a = 999999999999999999999999999999999999999999999999999999999999999999999999

b = a +1

a == b 
> true

```
Then the database is "done" in the sense that it will be impossible to add new entries (actually each peer with write access could append one more entry. 

My question is, are those issues relevant to the proper working of the database  or not?  (especially the last one)

**Comment by haadcode** [comment]
Manipulating the `clock.time` (a Lamport clock) will not effect order of events. The (causal) order between entries is established through the merkle links (the `next` field in an entry). Doing such clock skewing can effect the conflict resolution though when two entries "happened at the same time" from the perspective of the causal order.
