### ISSUE TITLE
Dependencies on moving targets

### ISSUE THREAD

**Issue by wigy-opensource-developer** [orbitdb/orbit-db#142]
While trying to narrow down #141 I have realized that [ipfs-daemon 0.0.3 depends](https://github.com/haadcode/ipfs-daemon/blob/de99a772ff00e03cf172e2f2cbf637dfc0219a7e/package.json#L14) on the github master branch of js-ipfs-api that has a dev dependency on ipfs-daemon 0.2.3

I understand that it might be uncomfortable to release every version on npm, but I suggest to at least tag those dependencies on github and change the package.json to something like the following:
```
dependencies {
  ...
  "ipfs-api": "https://github.com/haadcode/js-ipfs-api.git#v11.1.0",
  ...
}
```

This helps reproducibility of issues, so it might save some time for both people maintaining the code and people using the code to track down where some problems appeared first.

**Comment by haadcode** [comment]
Hey @wigy-opensource-developer, thanks for reporting the issues! We're in the process of releasing 0.4.5 of go-ipfs and as orbit-db using the very latest version, the dependencies are a little... complicated. We're fixing this as we speak.

**Comment by haadcode** [comment]
To add to the previous: the plan is that we don't need to use GH repos as packages, nor depend on forks in the future.

**Comment by wigy-opensource-developer** [comment]
Awesome. Thanks for the feedback.

**Comment by haadcode** [comment]
I believe this can be closed. Feel free to re-open it if there are more questions or discussion to be had.
