### ISSUE TITLE
Ideas for demos for orbit-db

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit-db#148]
orbit-db starts to be in a shape that it's usable on various platforms and for various use cases. In order to show what orbit-db can do, we should have a bunch of cool demos that display orbit-db's capabilities and features.

One of them is [Orbit](https://github.com/haadcode/orbit), but I would like to see more and more varied ones. Another demo I made at some point (the code might not run anymore) is a twitter-like feed app https://github.com/haadcode/planet-express, but it was a hack and I haven't had the time to continue.

I would like to reach out to the community to source ideas as to **what we could build to demo orbit-db**?

What would you *like* to see? What do you propose to showcase the technology in a cool way? These could be either Node.js or in the browser.

**Comment by haadcode** [comment]
I would like to see someone take the idea of planet-express (ie. twitter) and build it from scratch. In order to build a twitter-like app, one needs to use several different orbit-db databases (feed, eventlog, counters, kvstore) and as such, this is a good and varied demo.

I would love to see a "playlist" or generic collection demo where you can add/remove items to collections. This kind of component could be used in file managers, music players, chat apps. etc.

It would be cool to see a graphical interface for the key value store. Functionality wise it wouldn't need to be anything more than what you can do with the kvstore, but we could do something cool with the UI (eg. a "oldschool terminal" styled interface in the browser, or perhaps a WebGL-based UI)?

A game using orbit-db would be really cool.

Another cool demo would be to hook #ipfs IRC channel with a bot to an orbit-db which then can be viewed in the browser, much like botbot.me.

If we want to show off some very complex  but extremely cool stuff, we could build a publishing platform demo: user profiles, several news feeds, items to purchase, personal/private collections. Think something like Steam or Spotify.

Hopes this gets you started with ideas!

**Comment by VictorBjelkholm** [comment]
I would love to see something like HackMD or Etherpad using orbit-db in the background.

**Comment by Kubuxu** [comment]
It should be possible by sending creating OrbitDB transport for Cryptpad.

**Comment by haadcode** [comment]
> I would love to see something like HackMD or Etherpad using orbit-db in the background.
> It should be possible by sending creating OrbitDB transport for Cryptpad.

Me too! 👍 There's a bit more work to a collaborative editor as it'd a specific type of db/CRDT that's not yet implemented in orbit-db. If someone wants to try to make this happen, I'd be more than happy to help.

**Comment by lgierth** [comment]
I'd love to see a chat bot which I can highlight and which will then log the line I wrote somewhere.

```
<lgierth> logbot: i'm doing something right now and i'm telling you so everyone else knows and it's searchable
<logbot> lgierth: ok -- new head: ipfs.io/ipfs/Qmfoobar
```

This would be the writing end pushing stuff into some standard-ish data structure, and the reading part would be a web UI with search and all.

**Comment by fdietze** [comment]
What about a todo-app where lists can be shared with other users?

**Comment by jbenet** [comment]
Here are much simpler suggestions, for _demos_ of the technology:

- Something like the mouse + typing demos of http://ppyr.us:8001/demo3/index.html
- Something like the one in https://youtu.be/5ebPhEKtY8c?t=176
- Something like -- but clearer than -- the orbit-db color demo page (its a good idea, just very confusing for people right now. needs to be a lot simpler, and easier to add multiple instances)
- something like this -- but without the "server" part (pubsub maybe) -- https://operational-transformation.github.io/visualization.html -- and easier to add more participants

---

I'm working on designing a visualization that will capture:
- orbit-db log (with inspection of message)
- pubsub stream (with inspection of message)
- connectivity
- adding/removing more peers
- opening/closing connections
- (bonus pts) adding/removing connectivity barriers

**Comment by cristiano-belloni** [comment]
@haadcode: I would like to build a twitter-like demo. But I guess that it would be worth to wait for https://github.com/orbitdb/orbit-db/pull/240 to be completed - as far as I can understand, with authenticated writes users won't be able to 1) modify other users' content and 2) prove they "own" a particular entry in the database, although they WON'T be able to 3) dynamically get a write permission (but I guess they will be able to do 1 and 2 with the wildcard permissions, am I correct?)

**Comment by haadcode** [comment]
@cristiano-belloni a twitter-like demo would be awesome! :) And indeed, with #240 which we can hopefully release this week, there'll be a way to have per-user feeds (1) as well as multi-user (or anyone-can-write) feeds.

Let us know if you start building it, I'd be happy to help!

**Comment by cristiano-belloni** [comment]
@haadcode So I'm coding around this Twitter demo thing and I decided to start with the per-user feeds. As you put it in the docs:

> For example, in a twitter-like application, tweets would not be saved in a global "tweets" database to which millions of users write concurretnly, but rather, each user would have their own database for their tweets. To follow a user, a peer would subscribe to a user's feed, ie. replicate their feed database.

So I'm trying to just have a key-value private database for user details (username or handle, first name, last name). What I do when the thing starts is:

```javascript
ipfs.on('ready', async () => {
      if (!orbitdb) orbitdb = new OrbitDB(ipfs)
      if (!access) access = {
        // Give write access to ourselves
        write: [orbitdb.key.getPublic('hex')]
      }
      res()
})
```

Then I open my user db and `load`:

```javascript
  if (!orbitdb) await init()
  if (!userDb) userDb = await orbitdb.kvstore('user-db', access)
  await userDb.load()
```

The userDb is empty at this point and I prompt the user to enter username, first name, last name. Then I set them:

```javascript
Promise.all([
    userDb.put('userName', userName),
    userDb.put('firstName', firstName),
    userDb.put('lastName', lastName),
  ])
```

Everything works ok, but if I reload the page and do the same, I would expect the values to be `get`table. Instead, if I do:

```javascript
return {
    userName: userDb.get('userName'),
    firstName: userDb.get('firstName'),
    lastName: userDb.get('lastName')
  }
```

The values will be all `undefined`. What am I missing? The `userDb.address.toString()` is always the same, and I assumed that `await userDb.load()` loads all the data previously `put` in the `userDb`. It doesn't seem the case.

**Comment by cristiano-belloni** [comment]
Mystery solved. This
```javascript
Promise.all([
    userDb.put('userName', userName),
    userDb.put('firstName', firstName),
    userDb.put('lastName', lastName),
  ])
```
will update only LastName, while this:

```javascript
  await userDb.put('userName', userName),
  await userDb.put('firstName', firstName),
  await userDb.put('lastName', lastName)
```

will update all three. It seems that running the three promises in parallel doesn't work, but running them serially does? Is it expected? Or I'm missing something obvious?

**Comment by aphelionz** [comment]
@cristiano-belloni each entry on a single node will need to know about all the previous entries from that node to set the clock value - I'm guessing you've got some sort of race condition going on between the write and the concurrent read/reduction of the oplog.

I'm going to close this ticket for now, and refer people to the [OrbitDB Field Manual](https://github.com/orbitdb/field-manual) for discussion about project ideas and questions like "What Can I Use Orbit For?
