### ISSUE TITLE
doesn't work with Node.js 4 LTS

### ISSUE THREAD

**Issue by diasdavid** [orbitdb/orbit-db#179]

**Comment by haadcode** [comment]
Any details as to why? Unsupported ES6 features?

**Comment by diasdavid** [comment]
yeah, exactly. The ones I caught were the "Default parameters"

**Comment by haadcode** [comment]
We have dropped the support for Node.js 4 and currently support Node.js >=8.0.0. For older versions, we have a [ES5 build](https://github.com/orbitdb/orbit-db/tree/master/dist/es5). More information in [changelog](https://github.com/orbitdb/orbit-db/blob/master/CHANGELOG.md#code-base-improvements).
