### ISSUE TITLE
Running tests on Cloud9 workspace

### ISSUE THREAD

**Issue by KennethHolmSeelig** [orbitdb/orbit-db#186]
I'm trying to run the test  [orbit-db/test/replicate.test.js](https://github.com/haadcode/orbit-db/blob/master/test/replicate.test.js) and have restricted it to run with the IpfsNodeDaemon.

`
[IpfsNodeDaemon].forEach((IpfsDaemon) => {
`
instead of
`
[IpfsNativeDaemon].forEach((IpfsDaemon) => {
`

But it times out 'waiting for peers'.

All other tests pass and I am using Node 6.1.0 like on the passing CircleCi build.
I have tried running on the same image as CircleCi uses for the passing test, but the image is too big for my little Docker workspace, but the same tests fail on other Ubuntu images. 

what am I missing?

$ npm test                                                                                      

```sh
  108 passing (2m)
  2 failing

  1) orbit-db replication two peers replicates database of 1 entry:
     Error: Timeout of 40000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) orbit-db replication two peers replicates database of 100 entries:
     Error: Timeout of 40000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Edited: for more information

**Comment by haadcode** [comment]
Apologies for missing this one completely!

If you'd care to try again from master, you should find the tests passing now. We just released a new version of orbit-db with many fixes and updates and the replication overall has been improved.

Let me know if this was fixed or if there's more I can do to help get it working!

**Comment by KennethHolmSeelig** [comment]
Works with IpfsNodeDaemon, which I needed, thanks!

**Comment by haadcode** [comment]
Awesome! Closing this, then. Feel free to re-open it if you have any more issues.
