### ISSUE TITLE
Does the db sync work for browser?

### ISSUE THREAD

**Issue by zabirauf** [orbitdb/orbit-db#197]
I tried running the `examples/browser/browser.html` with the SignalServer changed to `0.0.0.0:9090` and started the js-libp2p-webrtc-star signaling server locally. But when I run it in two tabs then the data being pushed to eventlog doesn't seem to sync across both of them. 

Am I missing something here? Does the data sync work in the browser as the node example seem to work fine. 

P.S: I am new to IPFS and ordit-db so my knowledge is limited.

**Comment by rkyleg** [comment]
I am confused about this as well. I am using the kvstore and data persists while the app is running; however, when I restart the app, the data is gone. I am using the IpfsBrowserDaemon with the signalling server from the browser example.

**Comment by zabirauf** [comment]
Following is what I'm seeing, whenever i start in a new incognito window the count starts from beginning i.e. its not syncing.

![orbit-db-example-issue](https://cloud.githubusercontent.com/assets/1104560/23836571/9d56edce-0737-11e7-8794-aa22cd81b8fb.gif)

**Comment by haadcode** [comment]
Hi everyone and thanks for reporting the bugs! We just released a new version of orbit-db, including updated examples. Would you care to take another try and see if this bug still happens?

As a clarification, as @zabirauf shows in his screenshots, you'll have to open the second peer in an *incognito tab*, otherwise the peers won't connect as they use the same ipfs repo (ie. they have the same IPFS peer id).

**Comment by zabirauf** [comment]
@haadcode When i run the example, i get the following error

```
TypeError: db.load is not a function
    at IpfsBrowserDaemon.ipfs.on (index.js:100)
    at IpfsBrowserDaemon.EventEmitter.emit (events.js:78)
    at _initDaemon.then.then (ipfs-browser-daemon.js:20)
```

**Comment by haadcode** [comment]
@zabirauf I believe this is due to not updating node_modules after pulling the latest. Make sure you do `rm -rf node_modules && npm install` after you've pulled from master in order to get the latest modules. Let me know if this helped.

**Comment by zabirauf** [comment]
@haadcode Thanks, that solved the issue. I do see the KVStore to be in sync but the log and counter still seem to be unsynced.

![orbit-db-example-issue](https://cloud.githubusercontent.com/assets/1104560/24235654/9020b58c-0f5b-11e7-9901-e5a0c1d75c6f.gif)

**Comment by haadcode** [comment]
@zabirauf thank for confirming this fixed your issue.

I see that in your video, the "Peers" at the top says 0 for both. This means that the two peers are not connected and as such, can't sync the databases (any of them). We still have some bugs related to the connectivity, so it might be that the peers don't connect every time. To go around this, I usually restart both peers until I see "Peers: 1" in both :) Let me know if this helps!

**Comment by zabirauf** [comment]
@haadcode Thanks a lot, it works. Everything syncs now 👍 . Closing the issue now.

**Comment by haadcode** [comment]
Great to hear! Please don't hesitate to open new issues if you come across any.
