### ISSUE TITLE
Is OrbitDB "live"?

### ISSUE THREAD

**Issue by rkyleg** [orbitdb/orbit-db#212]
When using the browser daemon and the ipfs dev signalling server, is the connection "live" to ipfs? I am not getting a "data" event from my databases, but when I change it to "write" the event gets thrown. This leads me to believe the data doesn't get written to ipfs. I also tried using a local ipfs node and setting the Addresses property in ipfs options and I still don't get the "data" event firing. Am I misunderstanding something?

**Comment by haadcode** [comment]
Hi @rkyleg, I believe the event you need to listen to is 'synced'. 'write' event is when database is updated locally. I noticed that the API documentation wasn't updated to reflect the recent change so I updated it to describe what to expect: https://github.com/orbitdb/orbit-db/blob/master/API.md#events. 

As for local data, note that there's a now an explicit [load()](https://github.com/orbitdb/orbit-db/blob/master/API.md#kvstorename) method that needs to be called if you wish to load the persisted local state of the database.

Let me know if this solves your problem.

**Comment by rkyleg** [comment]
@haadcode yes, that is greatly helpful! The events are firing as expected now, and I am able to load history with the load() method. Thank you!
