### ISSUE TITLE
IPFS hash for orbit db record

### ISSUE THREAD

**Issue by gagarin55** [orbitdb/orbit-db#215]
Hello, I use `new OrbitDB(ipfs).eventlog('MY_DB');` How I can obtain IPFS hash for my record or any other data structure which I can check directly by `ipfs cat ...` ?

**Comment by IamCarbonMan** [comment]
You're looking for the `load.progress` event: https://github.com/orbitdb/orbit-db/blob/master/API.md#events

**Comment by haadcode** [comment]
You get the IPFS hash of an individual operation as the return value of the operation. Eg.:
```js
const orbitdb = new OrbitDB(ipfs)
const feed = orbitdb.feed('my-feed')

// Get a hash of an operation
const hash = db.add('hello')
console.log(hash)

// Remove the entry in feed
db.del(hash)
console.log(db.iterator({ limit: -1 })
```

`db.iterator()` will also return the entries in their "raw" form, ie. the actual OP and its hash is included in the result.

Hope this helps! Feel free to re-open the issue if you have more questions.
