### ISSUE TITLE
Is it secure to store user's login data, passwords?

### ISSUE THREAD

**Issue by baimurzin** [orbitdb/orbit-db#217]
Is it secure to store user's login data, passwords?

**Comment by ccutch** [comment]
I would not store sensitive user data (emails, passwords, ect) for user login i would suggest a third party such as uport. If you are making a simple app, as I first did when learning about orbit, you can try what i tried which is to encrypt both the email and password such that the given encryption can be checked later (see code snippet at the bottom) though this is not very safe from phishing attacks and brute force.

```
// email, password given
// store = orbit-kv-store
email_hash = sha256(email)
user_key = sha256(email + password)

// to store login
store.set(email_hash, user_key)

// to check user
store.get(email_hash) == user_key
```

**Comment by haadcode** [comment]
Agreed with @ccutch. See https://github.com/orbitdb/orbit-db/issues/229#issuecomment-326931904 for more details.
