### ISSUE TITLE
How to designate a canonical place for the database?

### ISSUE THREAD

**Issue by carlbror** [orbitdb/orbit-db#224]
I'm trying to create a simple html-page where everyone who accessess it is using the same database, but I don't know how. 

So, when I open the page with Firefox I get one local database (placed somewhere in ~/.mozilla?), which works well enough. But when I open it with Opera I get another database (with no documents I've added to the firefox-database), and when I open Chromium I get a third, unique database. And when place the file on ipfs and read it through http://localhost:8080/ipfs/hash I access on database and when I read it through https://gateway.ipfs.io/ipfs/hash I read from another database. That is, in one database I have [{_id: "jknfiunuöf", doc: "Hello World!"}] and in another I have [_id: "xajnkju2", "Mellon"}].

So, how can I make them all read from the same database?

I'm guessing I need to define the server and folder path when creating the IPFS-object, such as:

```
  const ipfs = new IPFS({
    IpfsDataDir: '/orbit-db-/examples/browser',
    SignalServer: 'star-signal.cloud.ipfs.team'
  })
```

But I cannot get this to work, when I try to add a doc to the database now it simple says it is listening to this address. What am I missing?

This is the code I run:

```
'use strict'
const IPFS = require('ipfs-daemon/src/ipfs-browser-daemon')
const OrbitDB = require('orbit-db')
var newEntry, putButton;
if (typeof window !== 'undefined'){
  newEntry = document.getElementById('new-entry')
  putButton = document.getElementById('add-to-docstore')
}



const showContentOfDatabase = (array) =>{
  if(!array) array = [];
  var contentInHtml = "";
  for(var x = 0; x < array.length; x++){
    contentInHtml += "<p>" + array[x].doc +"</p>"
  }
  if (typeof window !== 'undefined'){
    document.getElementById('database-entries').innerHTML = contentInHtml;
  }else{
    console.log(contentInHtml)
  }
}

const openAndEditDatabase = (obj) =>{
  const ipfs = new IPFS({
    IpfsDataDir: 'orbit-db',
    SignalServer: 'ws://ip4/127.0.0.1/tcp/4001'
  })
  ipfs.on('error', (e) => console.log(e))
  ipfs.on('ready', () => {
    const orbitdb = new OrbitDB(ipfs)
    const docstore = orbitdb.docstore('docstore');
    docstore.events.on('ready', () => {
      console.log(docstore.query( (doc) => true ))
      showContentOfDatabase(docstore.query( (doc) => true ));
      if(obj && obj.put) docstore.put(obj.put)
    })
    docstore.load()

    docstore.events.on('write', () => {
      console.log("on write event")
      showContentOfDatabase(docstore.query( (doc) => true ));
    })
  })
}

openAndEditDatabase();
const addEntry = () =>{
  openAndEditDatabase({put:{_id:randomId(),doc:newEntry.value}})
  newEntry.value = "";
}


if (typeof window !== 'undefined'){
  putButton.addEventListener('click', addEntry)
}
```

**Comment by haadcode** [comment]
Sorry it took a while to get back to this @carlbror! We just released a new version [v0.18.0](https://github.com/orbitdb/orbit-db) which contains a lot of fixes and improvements.

Take a look at the new [getting started guide](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md), it should answer many of your questions. See especially the part on [replication](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#replicating-a-database) which contains an example how to get a database to multiple nodes. 

To answer the question as stated in the description:
*"How to designate a canonical place for the database?"*

OrbitDB will save data in `./orbitdb`. This can be any directory.

However, I believe what you're asking is:
*"How to use the same database on multiple nodes?"*

Each database has an address that can be used to open the same database on any node / app:
> When a database is created, it will be assigned an address by OrbitDB.
> *"/orbitdb/Qmd8TmZrWASypEp4Er9tgWP4kCNQnW4ncSnvjvyHQ3EVSU/first-database"*

See https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#address for more details and the [replication guide](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#replicating-a-database) for an example how to do this.

Hope this helps. 

Feel free to re-open the issue if you have further questions!

**Comment by aphelionz** [comment]
@haadcode Is there a way to designate a custom location for the orbitdb folder besides `./orbitdb`? I'd like something perhaps like `/var/ipfs/orbitdb-with-custom-folder-name`

**Comment by vvp** [comment]
@aphelionz you can specify a custom location for OrbitDB folder in the OrbitDB constructor, like in examples/eventlog.js:
```JS
const orbitdb = new OrbitDB(ipfs, './orbitdb/examples/eventlog')
```
