### ISSUE TITLE
Possible types of databases in Orbit?

### ISSUE THREAD

**Issue by ionicc** [orbitdb/orbit-db#229]
Can Orbit be used to make a NoSQL type database (MongoDB, etc). We want to build a distributed database system which will store individual people's id number and then store other data related to the number such as Name, age, etc.

**Comment by haadcode** [comment]
Thanks for the question @ionicc! 

First, please note that orbit-db makes no security nor privacy guarantees at the moment. 

***Storing people's id, name, age or any personal data, whether centralized or decentralized, should be carefully thought through and make sure that user's privacy and data security are the utmost importance!*** 

I'm sure you do, but I want to highlight it here.

As of today, I would not recommend you to use orbit-db for anything that stores people's personal data *unless* you can guarantee the privacy and security of that data via other means.

That said, security and privacy are very important properties and features in orbit-db and in the future we'll have ways to support them I'm sure, but as of today it would be irresponsible to advice storing private and sensitive data to orbit-db. 

> Can Orbit be used to make a NoSQL type database (MongoDB, etc).

Yes, absolutely! You can use the [Document Store](https://github.com/orbitdb/orbit-db-docstore) for that, it's for saving documents. Let us know if you hit any problems!

For more possible data models, take a look at the list in the [README](https://github.com/orbitdb/orbit-db#orbit-db).

I hope this answers your questions. If you have more questions, don't hesitate to ask and re-open the issue!
