### ISSUE TITLE
Document iterator options in Eventlog and Feed

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit-db#230]
We have the iterator() function in eventlog and feed to query the database. It's documented here: https://github.com/orbitdb/orbit-db/blob/master/API.md#eventlogname. The iterator() takes in an options object that can be used to filter the query. However, the different options are not documented!

The possible options are here https://github.com/orbitdb/orbit-db-eventstore/blob/master/src/EventStore.js#L47 in the code. 

They are:
- limit (how many results to return)
- gt/gte (greater than, greater or equal)
- lt/lte (lower than, lower or equal than)

Leaving this issue here as a reminder for myself but if anyone wants to do a small and easy contribution, this one is up for grabs!

**Comment by prabodhmeshram** [comment]
Hi @haadcode , I would Like to contribute. Is this issue still open ? If it is can you please explain what is required to be done here.

**Comment by haadcode** [comment]
Hey @prabodhmeshram and thank you for going for this! <3 It's still available for grabs.

The goal here is to document the `.iterator([options])` function thoroughly, see [here](https://github.com/orbitdb/orbit-db-eventstore/blob/master/src/EventStore.js#L26) and the current documentation [here](https://github.com/orbitdb/orbit-db/blob/master/API.md#eventlogname). The function takes `options` as its argument. As you can see, the `options` object is not currently documented. `options` is an object that can have the following fields:

`gt`, `gte`, `lt`, `lte` each one here is a *Multihash as a Base58 encoded string* and they work as a *range*, ie. "return all result starting from <hash>", { gt: 'QmFoo' }

`limit` integer, limits how many entries to return as a result, eg. { limit: 1 }

`reverse` boolean, should the results be reverse, eg. { reverse: true }

These options, what they take as input and what they do, should be document in https://github.com/orbitdb/orbit-db/blob/master/API.md#eventlogname. It would be also great to provide usage examples and output examples for each, but that's absolutely optional.

A PR that adds the documentation to https://github.com/orbitdb/orbit-db/blob/master/API.md#eventlogname would be highly appreciated.

Let me know if you need any clarification or help, I'd be happy to assist!

**Comment by prabodhmeshram** [comment]
Thanks @haadcode . I will study the code and will add a PR for the changes.

**Comment by haadcode** [comment]
This was done and contributed by @prabodhmeshram in https://github.com/orbitdb/orbit-db/pull/232. Thank you! ❤️
