### ISSUE TITLE
peerpad and orbit-db

### ISSUE THREAD

**Issue by spaceywolfi** [orbitdb/orbit-db#239]
[peerpad](https://github.com/ipfs-shipyard/peerpad)

i would like to understand these two projects more

So the ipfs-shipyard projects use http://y-js.org/ for the CRDT and orbit-db has its own?

orbit-db is a database build on top of ipfs. 
they both use ipfs pubsub?

i am a bit confused so i would like to understand why we have two projects build on top of ipfs. maybe someone can clarify the needs for 2 projects 👍 

sry for asking so many questions

**Comment by aphelionz** [comment]
Hi there, I'm not sure about Y's implementation but OrbitDB is built on top of what's called a G-Set CRDT, which is essentially an append-only operations log that is reduced to the database state at a particular time. We value eventual concurrency - peers come and go in a swarm.

For more info on the underlying concepts behind Orbit, you can see the new [Field Manual](https://github.com/orbitdb/field-manual) to learn more.
