### ISSUE TITLE
TodoMVC example

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit-db#246]
I made an example on how to use OrbitDB with [TodoMVC](https://github.com/tastejs/todomvc/):
https://github.com/haadcode/example-orbitdb-todomvc.

We should add it to the readme.

**Comment by haadcode** [comment]
Updated https://github.com/haadcode/example-orbitdb-todomvc and added a [live demo](https://ipfs.io/ipfs/QmTJGHccriUtq3qf3bvAQUcDUHnBbHNJG2x2FYwYUecN43/)

**Comment by haadcode** [comment]
Open the [live demo](https://ipfs.io/ipfs/QmTJGHccriUtq3qf3bvAQUcDUHnBbHNJG2x2FYwYUecN43/) in a second browser (or in incognito window) and you should have them both updating the TODO list:
<img src="https://raw.githubusercontent.com/haadcode/example-orbitdb-todomvc/master/screenshots/Screen%20Shot%202017-11-29%20at%2017.09.31.png">

**Comment by haadcode** [comment]
Need to update the code ^ to work with the latest releases of orbitdb and ipfs before this is finished.

**Comment by natachadelarosa** [comment]
Hello, can I work on this issue?

**Comment by haadcode** [comment]
@natachadelarosa absolutely! Would love to get the example updated! 😄❤️ 

I believe what needs to be done, is to: 
- Update both ipfs and orbit-db modules to ~0.28.0 (note, not ~0.29.0) and ~0.19.8 respectively. 
- The dev signal server address has changed to `/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star` which should be updated in https://github.com/orbitdb/example-orbitdb-todomvc/blob/master/src/store.js#L11
- There's a part of code here https://github.com/orbitdb/example-orbitdb-todomvc/blob/master/src/utils.js#L39 where we use a feature of document store that was never merged, ie. it doesn't exist. We should either remove the sorting completely (messes the UX a bit as todo-items will jump up and down on the list) or find another property to sort by (eg. `clock` or `payload.value._id` - the id of the document).

I believe those are all changes that are needed but there may be more small things that don't work (the code hasn't been updated in a while). Let us know if you hit any problems or have any questions!

**Comment by natachadelarosa** [comment]
Hello, 

Sorry for the delay in this, I had a rough week.

Could it be a problem if I do the project from 0? Because most of the package that uses are deprecated also de project organization is a bit outdated.

Regards,

**Comment by haadcode** [comment]
@natachadelarosa no problem at all to do it from scratch! Happy to replace the earlier project and help with any questions or review code if you want.

**Comment by natachadelarosa** [comment]
Hello @haadcode sorry with the delay on this, I didn't have the time, have had too much on my hands with Consensys dev program and my work. Yesterday I began to work on it and it's ready, on this link you can check it out and do a code review: https://github.com/natachadelarosa/example-orbitdb-todomvc-updated 

Sorry again for the delay.

Best regards,

**Comment by natachadelarosa** [comment]
Also, there's a couple of changes, as I told you before, I changed the entire structure of the project.

This is what I did:

- create-react-app as the base project
- todomvc-app-css for the style
- react-router instead of director for the navigation, this because director package was giving me problems with Webpack.
 
And I tried to follow ES6 as much as I could.

**Comment by RichardLitt** [comment]
This is awesome! So cool to see this work. 🎉 👍 👍 🌟

**Comment by natachadelarosa** [comment]
Thanks for your kind words @RichardLitt  👍

**Comment by haadcode** [comment]
@natachadelarosa sorry it took a while to get back to you! First, thank you for coming back to this and re-writing the example! 👍❤️ 

The code looks good to me and there are no glaring problems that I can see. There are some smaller things where the code could be improved, but I don't feel they're blockers to call it ready :) 

Would you want to move the repo to the @orbitdb organization? We could also just have it where it is atm and add it to the README and other relevant docs. Are you interested to maintain the project in the future? (You can totally say no, too! :))

**Comment by natachadelarosa** [comment]
Hi @haadcode! 

How can I move the repo to the @orbitdb organization? Do I need to make a push request to the original repo?

And of course I'll be happy to maintain the project and also help with other issues as well, I want to help as much as I can!

**Comment by RichardLitt** [comment]
I've invited you to the @orbitdb org. :) Use your powers (you can see other members, create repos, and teams) for good. 

When you've accepted, you'll be able to move the repo over to @orbitdb. :D

**Comment by sundbry** [comment]
Hi, I'm just testing Orbitdb around here. It seems to work ok with two separate browsers, but if I open it in two separate tabs, the consistency goes haywire. Is that a known limitation (from IndexedDB?)

**Comment by aphelionz** [comment]
More or less. Essentially the tabs share the same IPFS browser node (same IPFS id) and are going to conflict.

**Comment by aphelionz** [comment]
Concurrent tab support has been added! Closing this.
