### ISSUE TITLE
is this suitable for building a collaborating text editor?

### ISSUE THREAD

**Issue by coodoo** [orbitdb/orbit-db#248]
Meaning char-level syncing and merging using causal-tree merging strategy for CRDT, is this something supported by orbit? Thanks.

**Comment by aphelionz** [comment]
Yes, you could use OrbitDB for this, and in fact I believe some others have! For more information about what you might be able to use OrbitDB for, I'd recommend taking a look at at least the Introduction section of the new [OrbitDB Field Manual](https://github.com/orbitdb/field-manual). Feel free to open any issues there if things are unclear.
