### ISSUE TITLE
`setImmediate` is not defined.  

### ISSUE THREAD

**Issue by shd101wyy** [orbitdb/orbit-db#253]
Hi there,

When I use this library in browser and add an entry to `feed` db, it gives me an error that `setImmediate` is not defined. 
It seems that browser like Chrome doesn't support `setImmediate` function.  
So I installed the npm module [setImmediate](https://github.com/YuzuJS/setImmediate) manually and added the following lines to resolve this issue:

```javascript
var setImmedaite = require('setimmediate')

if (typeof(window['setImmediate']) === 'undefined') {
  window['setImmediate'] = setImmedaite
}
```

Thanks

**Comment by shd101wyy** [comment]
And I have a question here:

Is it possible to create a global database.  
Say that there is a database called `DB` in this world.  
I am running a IPFS node `nodeA` on computer `A`, and running a IPFS node `nodeB` on computer `B`.  
Is it possible that both `nodeA` and `nodeB` connect to `DB` and can modify `DB`?

Thanks

**Comment by cristiano-belloni** [comment]
Yes, you'll just have to:

- create DB with public access in nodeA:
```
const access = {
    // Give write access to everyone
    write: ['*'],
  }

  const db = await orbitdb.keyvalue('DB', access)
``` 

- get the address of DB on nodeA:

```
db.address.toString()
```

- Pass the address string to nodeB somehow
- Replicate DB on nodeB:

```javascript
const db = await orbitdb.keyvalue(addressStringFromNodeA)
```

See [this](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md) for a complete guide.

**Comment by shd101wyy** [comment]
@cristiano-belloni Thank you! That's awesome!
