### ISSUE TITLE
[FAQ]: For keyvalue type database, what is the difference between `.put` and `.set` function?

### ISSUE THREAD

**Issue by shd101wyy** [orbitdb/orbit-db#260]
I would assume that `.put` can be used to create a new entry in the database, but `.set` can't?
But if I want to update an entry in database, do both `.put` and `.set` behave the same?

Thank you

**Comment by haadcode** [comment]
Hi @shd101wyy! `.put` and `.set` do the same thing and one is an alias for the other.

I'll add a note to the readme to clarify this. Thanks for bringing it up! 😄 👍
