### ISSUE TITLE
Add contributors to package.json

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit-db#287]
Hey everyone,

I wanted to gauge your interest in getting some acknowledgment for your contributions on OrbitDB. The [js-ipfs](https://github.com/ipfs/js-ipfs) project includes everyone who ever contributed in their [package.json](https://github.com/ipfs/js-ipfs/blob/master/package.json#L171).

This gives recognition for the contributions made by people over time, which I like a lot. The only down sides I can see are: it requires making sure the list of contributors is up to date (not a blocker to do it imo) and as everyone's emails are included, some people may not appreciate having their email "published" and the fact that we've had contributors "outside" repo contributions (issues, IRC discussions, etc) that I feel should be credited just the same for the value they've added to the project (and this is hard to make sure that everyone's included).

I would be more than happy to start listing everyone in the package.json. I wanted to ask how do you feel about it? Or if you have alternative places where we can give credit to people?

cc @dignifiedquire @prabodhmeshram @ricardojmendez @shamb0t @RichardLitt @Alex-Werner @Kubuxu @nightwolfz @atfornes (I'm sorry if I missed anyone)

**Comment by dignifiedquire** [comment]
I think it is a great practice. Both js-ipfs and karma, where I have used and seen this practice first use a simple mechanism to make this work.
Part of the release scripts is using `git log` to gather all contributors of all time, and simply put the names and emails into the package.json. This means it is always up to date after a new release and little time has to be spent worrying or asking individuals to add them to the package.json.

See https://github.com/ipfs/aegir/blob/master/src/release/contributors.js for how aegir does it currently.

The only drawback to this is, that if people contribute to discussions only, they are not recognised with this system.

**Comment by ricardojmendez** [comment]
That's a nice touch, but not a deal-breaker for me if it doesn't happen.  :-) 

I've often seen it done on the README or CHANGELOG, but that mostly works for sporadic contributions. Adding people to the package.json sounds like a good approach.

**Comment by RichardLitt** [comment]
Adding to the package.json makes the most sense, to me. You can also add them to the README, or to the CONTRIBUTORS file. [all-contributors](https://github.com/kentcdodds/all-contributors) is an interesting spec for doing this. 

You can use [name-your-contributors](https://github.com/mntnr/name-your-contributors) to get all of your contributors, including discussions, which solves @dignifiedquire's issue of only getting code combinations. 

Updating using a post-commit script should be doable, too, so that it stays up to date.

If you do decide on a solution - you control here, and everyone who contributes should opt-out of these lists to make it easier for you (as opposed to opt-in) - let me know if you'd like help implementing it.

**Comment by ricardojmendez** [comment]
> If you do decide on a solution - you control here, and everyone who contributes should opt-out of these lists to make it easier for you (as opposed to opt-in)

Sounds like a good idea. Could be specified on the Contribution Guidelines, that way people are aware.

**Comment by haadcode** [comment]
I think I personally like CONTRIBUTORS file the most and @RichardLitt's proposal. What do you all think?

I don't see why we shouldn't go ahead and do this. Anyone willing to take this and implement it?

**Comment by haadcode** [comment]
> Could be specified on the Contribution Guidelines, that way people are aware.

We should add Contribution Guidelines too.

**Comment by RichardLitt** [comment]
I got this.

**Comment by RichardLitt** [comment]
By running:

```sh
$ name-your-contributors -u orbitdb -r orbit-db > contributors.json
$ cat contributors.json | jq '[ .[][].login | " - [@ \(.)](https://github.com/\(.))"]' | jq unique | jq -r .[] |
```

I was able to come up with a list of all contributors in this format:

```md
 - [@ 5310](https://github.com/5310)
```

1. Is this a good format? Perhaps `First Last <github url>` is better
2. Should we be gathering emails, too? (I don't think so.)
3. I'm not sure how to set this up with CircleCI, but it should work fairly well with Travis. @haadcode do you know the manifest well enough to run that command above?

**Comment by RichardLitt** [comment]
This has now been implemented. Thank you, everyone!
