### ISSUE TITLE
Build step missing?

### ISSUE THREAD

**Issue by ricardojmendez** [orbitdb/orbit-db#288]
I suspect I'm missing something from the build instructions. [After opening the browser examples](https://github.com/orbitdb/orbit-db#browser-example) I got a JS error that `lib/ipfs.js`was missing.

    $ find . | ack ipfs.js
    ./test/utils/start-ipfs.js

Did I skip a step somewhere?

**Comment by haadcode** [comment]
Ah, we don't have them in npm scripts :/ The lib files a copied in the [Makefile](https://github.com/orbitdb/orbit-db/blob/master/Makefile#L12). We should prolly create a script or move the `cp`commands to the npm script (npm build:examples).

**Comment by ricardojmendez** [comment]
Thanks, just ran make and created it. Ran into #294 while I was at it, though.

**Comment by haadcode** [comment]
The IPFS dist build is now copied to examples/lib/, fixed in https://github.com/orbitdb/orbit-db/pull/301

**Comment by haadcode** [comment]
The latest release, 0.19.0, should fix this. Please let us know if there are still problems in building the project.

Thank you for reporting and helping to fix this!
