### ISSUE TITLE
README linking to feature branches?

### ISSUE THREAD

**Issue by ricardojmendez** [orbitdb/orbit-db#290]
Is linking to images on feature branches from the README a good idea? I just noticed that one broke, likely because the feature branch was removed ([see PR](https://github.com/orbitdb/orbit-db/pull/289)).

**Comment by haadcode** [comment]
We (me) should not do that, my bad! Leftovers from an earlier PR...

Thanks for spotting this and [fixing it](https://github.com/orbitdb/orbit-db/pull/289)! 👍

**Comment by ricardojmendez** [comment]
Acknowledged. fwiw, there's two more linking to `feat/write-access/`, I just didn't change them because they weren't broken (but they did prompt this question).

**Comment by haadcode** [comment]
Thanks for spotting those too! 😄 Fixed here: https://github.com/orbitdb/orbit-db/commit/9ca27d370e238198fc8e8b191a0d7b3092d3e4d0
