### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by ricardojmendez** [orbitdb/orbit-db#294]
Can't find `dist/orbitdb.js` referenced on the make file:

> cp dist/orbitdb.min.js examples/browser/lib/orbitdb.min.js
> cp node_modules/ipfs/dist/index.min.js examples/browser/lib/ipfs.min.js
> cp dist/orbitdb.js examples/browser/lib/orbitdb.js
> cp: dist/orbitdb.js: No such file or directory
> make: *** [build] Error 1

That folder only contains `orbitdb.min.js`.

**Comment by haadcode** [comment]
Hmmm... it seems that we don't build the `build:debug` by default, which is what produces `dist/orbitdb.js`. The difference between that and `dist/orbitdb.min.js` is that the former is not uglified giving us a build that can be debugged easily. 

I wonder if we should build the debug build by default or leave it out. My intuition says just build it...

**Comment by haadcode** [comment]
This was fixed in https://github.com/orbitdb/orbit-db/pull/297. Thank you @ricardojmendez for reporting and looking into this!

**Comment by ricardojmendez** [comment]
My pleasure! Unfortunately there's another issue when building now - it doesn't look like `orbitdb.js.map` is being generated:

>  cp: dist/orbitdb.js.map: No such file or directory
>  npm ERR! code ELIFECYCLE
>  npm ERR! errno 1
>  npm ERR! orbit-db@0.18.12 build:debug: `webpack --config conf/webpack.debug.config.js --
>  sort-modules-by size && mkdir -p examples/browser/lib && cp dist/orbitdb.js 
>  examples/browser/lib/orbitdb.js && cp dist/orbitdb.js.map examples/browser/lib/orbitdb.js.map`

Do you want me to open a new issue or shall we re-open this one?

And a related question: should `dist/` be included in the repository? Seems like if that folder was always generated, it'd be easier to test make after a hard repo reset.

**Comment by haadcode** [comment]
Sorry for the troubles! Not sure why the sourcemaps are generated on my machine but not with the build. That said, [we don't have the sourcemaps generation on in the webpack conf](https://github.com/orbitdb/orbit-db/blob/master/conf/webpack.debug.config.js#L14) it seems. I'll fix this as I'm about to make a new release today.

Thanks for being thorough and helping to work out all these errors!

**Comment by haadcode** [comment]
> And a related question: should dist/ be included in the repository? Seems like if that folder was always generated, it'd be easier to test make after a hard repo reset.

Agreed. We originally included it to make sure the minified build is distributed, but there's no need to include in the *repo* and rather have it ship with the *npm package*. We need to setup .npmignore and .gitignore to handle this. We should open a new issue to track it.

**Comment by haadcode** [comment]
The issues with sourcemaps was fixed with this PR https://github.com/orbitdb/orbit-db/pull/299, thank you @FrauBienenstich!

It's merged and I'm gonna test it out once more before release.

**Comment by haadcode** [comment]
This should be fixed in 0.19.0. Please let us know and re-open the issue if you still encounter the problem.

Thank you everyone who contributed to finding and fixing the problem!
