### ISSUE TITLE
How to handle user/content discovery

### ISSUE THREAD

**Issue by davidrichard23** [orbitdb/orbit-db#296]
> each user would have their own database for their tweets. To follow a user, a peer would subscribe to a user's feed, ie. replicate their feed database.

How would a user discover a feed to subscribe to? From what I understand, only database level write permissions are available so I couldn't create a public database that allows users to add their profiles because any user would be able to edit/delete any other user's profile.

I could use a Log Database but then the profile wouldn't be editable or searchable. 

Is there something I'm missing or is this just a current limitation?

**Comment by fazo96** [comment]
I think discovering new database is just not currently in the scope of OrbitDB.

However you can solve that problem by opening a pubsub topic where the client advertises the address of their databases

**Comment by aphelionz** [comment]
@fazo96 is correct! This is currently on the application developer to do. However, we cover this in Chapter 5 of the tutorial section of the new [OrbitDB Field Manual](https://github.com/orbitdb/field-manual). People should check that out and open issues there if they have more questions or if something doesn't make sense.
