### ISSUE TITLE
Exclude `dist` from repository

### ISSUE THREAD

**Issue by ricardojmendez** [orbitdb/orbit-db#298]
We should include output folder `dist` on the repository.

Add to .gitignore and .npmignore

[Spawned off #294](https://github.com/orbitdb/orbit-db/issues/294#issuecomment-354596456)

**Comment by ricardojmendez** [comment]
> We originally included it to make sure the minified build is distributed, but there's no need to include in the repo and rather have it ship with the npm package.

Looks like `dist` is already on .gitignore (it still got committed at some point in the past) and .npmignore excludes `dist/*.map`.

Was the comment meant to exclude just the minified build from npm, or the `dist` folder as a whole, @haadcode ?

**Comment by haadcode** [comment]
Thank you @ricardojmendez for following up on this! 

To clarify:
- We should *exclude* `dist/`from the git repo (as these are the files produced by `npm run build`)
- We should *include* `dist/orbitdb.min.js` in npm package as it's the "browser distributable"
- We should *exclude* `dist/*.map` and `dist/orbitdb.js` (sourcemaps and debug build respectively) as they're fairly large and only needed for development purposes

I think that's it, hope I didn't miss anything.

**Comment by haadcode** [comment]
Ok, changed the npmignore to exclude the debug build here https://github.com/orbitdb/orbit-db/commit/f1b2f2252fa028a7da64e5713210fb2f8e2062d1 along with a note about the ES5 build.

**Comment by ricardojmendez** [comment]
Cool, I was just about to submit a PR for that.

**Comment by haadcode** [comment]
Sorry, I didn't see the update :/

**Comment by ricardojmendez** [comment]
No problem. :) Just pushed it but was still running my tests locally. I noticed you excluded `orbitdb.debug.js` on master and wanted to check if that was built anywhere, since I hadn't found where.

**Comment by haadcode** [comment]
@ricardojmendez can you PR it nevertheless? I didn't remove the es5 build yet.

**Comment by ricardojmendez** [comment]
Done!

**Comment by haadcode** [comment]
Thank you ❤️
