### ISSUE TITLE
Custom database types

### ISSUE THREAD

**Issue by garbados** [orbitdb/orbit-db#307]
Although the orbit-db-store documentation suggests you can use custom stores (["Creating Custom Data Stores"](https://github.com/orbitdb/orbit-db-store#creating-custom-data-stores)), doing so is actually quite difficult because of how OrbitDB [pre-processes](https://github.com/orbitdb/orbit-db/blob/master/src/OrbitDB.js#L73) new stores. Indeed, OrbitDB [rejects](https://github.com/orbitdb/orbit-db/blob/master/src/OrbitDB.js#L104) stores with types not matching those it doesn't already know about.

In [cubesat](https://github.com/garbados/cubesat), I've taken to [piggy-backing off of an existing store type](https://github.com/garbados/cubesat/blob/master/index.js#L109-L115) in order to use a custom store with a custom index. My approach is hacky as heck and I'd love a better way.

**Comment by haadcode** [comment]
Indeed, you're right! Adding stores currently is cumbersome. Your PR is a great fix for it, so let's do that :)

Btw. if you're interested, we have https://github.com/orbitdb/orbit-db/issues/4 open and looking for contributors. Take a look and see if you'd be interested. I think it'd be the best way to solve what you're doing in ^ and would love to have a "PouchDBStore" in OrbitDB :)

**Comment by garbados** [comment]
Yay! I've jumped into that thread and I hope to have something together for it shortly.

**Comment by haadcode** [comment]
This should now be fixed through the PR above (#308). @garbados if you feel this can be closed, feel free to do so or if there's still something that needs work, let's continue the discussion.

Thank you for all the contributions you've made around this!

**Comment by garbados** [comment]
Yay! Seems good to me 👍
