### ISSUE TITLE
Blog Post: Getting node.js and browser Orbit DBs to talk

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbit-db#314]
@haadcode said it was OK if I post this :100: 

http://mrh.io/2018-01-24-pushing-limits-ipfs-orbitdb/

**Comment by haadcode** [comment]
This is awesome @aphelionz! Thanks for writing it! ❤️ I'm sure it's going to help a lot of people both here and in the wider IPFS community.

**Comment by aphelionz** [comment]
You're welcome. Anybody who has questions can reach out via the email address in the post.

**Comment by grvhi** [comment]
@aphelionz - I'm keen to read your blog post, but sadly it seems that the files aren't currently available on IPFS?

`ipfs resolve -r /ipns/mrh.io/2018-01-24-pushing-limits-ipfs-orbitdb/: failed to get block for QmY2LufsW3v6AfxTTkp6SGqDGa5AeJhSZXH8RSsdiao4Ds: context deadline exceeded`

**Comment by maxkerp** [comment]
@aphelionz Any chance to get your blog post accessible again?

**Comment by grvhi** [comment]
Great stuff, thanks @aphelionz

**Comment by aphelionz** [comment]
@RichardLitt Should we move this elsewhere, like awesome-orbit-db or something? Per your comment in Gitter maybe it might inspire others to add stuff

**Comment by RichardLitt** [comment]
@aphelionz Makes sense to me. Good thinking putting writing there. Moving it there now.
