### ISSUE TITLE
Testing with js-ipfs next (0.28)

### ISSUE THREAD

**Issue by diasdavid** [orbitdb/orbit-db#329]
Ran tests and got:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/1211152/36792070-781911fe-1c67-11e8-80e4-77cebe55b80f.png">

Similar to https://github.com/ipfs-shipyard/ipfs-pubsub-room/issues/29

To prepare this module for the next release, you'll need:

- [ ] replace the `dial(peer, protocol, callback)` calls by `dialProtocol(peer, protocol, callback)`. See the updated libp2p API https://github.com/libp2p/js-libp2p#api

**Comment by haadcode** [comment]
Thanks for the heads up @diasdavid!

I believe we also need:
- [ ] [Fix the failing "load from snapshot" tests](https://github.com/orbitdb/orbit-db-store/pull/17) where it errors with "Invalid arguments, data must be an object, Buffer or readable stream"

**Comment by haadcode** [comment]
We're now using js-ipfs@0.28.0! 🎉Released in npm as [0.19.6](https://www.npmjs.com/package/orbit-db).
