### ISSUE TITLE
Please write me

### ISSUE THREAD

**Issue by plankeonus** [orbitdb/orbit-db#330]
Dear creator of Orbit! Please, write me via plankeon@inbox.ru
I didn't find how to send private messages here
I have something to talk about! It is very urgently
This message you can delete!
Wait for your letter very much!

**Comment by haadcode** [comment]
Thanks for reaching out @plankeonus! The best way to get directly in touch is via IRC on [#orbitdb](http://webchat.freenode.net/?channels=%23orbitdb) or PM me on IRC (haad).

**Comment by plankeonus** [comment]
Check haad@ipfs.io

**Comment by plankeonus** [comment]
please, delete all this posts! now we are at mail with you
