### ISSUE TITLE
orbitdb instances fail to synchronize

### ISSUE THREAD

**Issue by vrogojin** [orbitdb/orbit-db#341]
Hello,
I have created a keyvalue database. Then, when running two instances of the database, when the peers discover each other and try to sync, I get the following error (both peers get the error at the same time):
`TypeError: callback is not a function
    at switch.dial (/mnt/users/home/vrogojin/orbit-db/node_modules/libp2p/src/index.js:241:9)
`
No sync happens, of course.
Is it a known bug, or I am doing something wrong?
If needed, I can post my conf and code files

**Comment by haadcode** [comment]
@vrogojin this just got fixed in https://github.com/orbitdb/orbit-db/pull/340 and was reported earlier in https://github.com/orbitdb/orbit-db/issues/337.

Please re-install or clone again and it should work. Let us know if you still experience the problem!

**Comment by vrogojin** [comment]
One more update: when the database is empty, I can open two peers, they find each other and no error happens.

**Comment by vrogojin** [comment]
Oh, thanks. I will try now

**Comment by vrogojin** [comment]
It works. Thanks!
