### ISSUE TITLE
[General Inquiry] Further contact information

### ISSUE THREAD

**Issue by CarlChryniszzswics** [orbitdb/orbit-db#356]
Hello haad, 
I would like to contact you privately to further discuss a subject. 
Are you available at [keybase](keybase.io), for instance?

Thank you,
Carl

**Comment by haadcode** [comment]
Hi @CarlChryniszzswics, you can reach me on IRC on [#orbitdb](http://webchat.freenode.net/?channels=%23orbitdb) or DM on twitter (@haadcode).
