### ISSUE TITLE
How to add Node.js modules to webpack

### ISSUE THREAD

**Issue by willemneal** [orbitdb/orbit-db#363]
I'm very new to developing with node.js and webpack.

Currently, I've been working on a way to encrypt the peerID and keystore with a password.  This way it can act as a user's account.  I've got the encryption working and the serialization of the typed arrays, but what I need to do in to reconstruct `Keystore` passing it `_storage`.  

`Keystore`, however, is not in scope in the browser example.  How do I add it to webpack so that I can use it in the client?

**Comment by lukas2005** [comment]
Adding libraries to web pack is described on its docs

**Comment by RichardLitt** [comment]
Thanks @lukas2005. @willemneal hope that answered your question! :)
