### ISSUE TITLE
The demo at <celebdil.benet.ai:8080/ipfs> seems to be dead.

### ISSUE THREAD

**Issue by martinhbramwell** [orbitdb/orbit-db#368]
http://celebdil.benet.ai:8080/ipfs/Qmezm7g8mBpWyuPk6D84CNcfLKJwU6mpXuEN5GJZNkX3XK/

That link is published at https://github.com/orbitdb/orbit-db/blob/master/README.md#background

**Comment by RichardLitt** [comment]
The link appears to work for me. Try again?

**Comment by martinhbramwell** [comment]
The link does work, but I am unable to get the page to do anything at all.

My apologies, I was imprecise.

I'm seeing many console errors but, this is most likely the culprit:

```
WebSocket connection to 'ws://178.62.241.75:9090/socket.io/?EIO=3&transport=websocket' failed:

Error in connection establishment: net::ERR_CONNECTION_REFUSED WS.doOpen @ 

Swarm listening on /libp2p-webrtc-star/ip4/178.62.241.75/tcp/9090/ws/ipfs/QmSUXq2cq4241sGLq7u6XbdyC26XNbeGZMagGTgG2r1GQr
```

**Comment by martinhbramwell** [comment]
See also : [Live demo seems unresponsive](https://github.com/haadcode/proto2/issues/1) from  Mar 11/2018

**Comment by aphelionz** [comment]
Live demos are working for me, closing. Re-open if necessary.
