### ISSUE TITLE
preparations for js-ipfs 0.29.0

### ISSUE THREAD

**Issue by daviddias** [orbitdb/orbit-db#369]
Similar to https://github.com/orbitdb/ipfs-log/issues/124. Here I was less lucky, some tests failed with always the same error, example bellow:

```
 6) orbit-db - Automatic Replication (js-ipfs)
       automatic replication exchanges the correct heads:

      Uncaught AssertionError [ERR_ASSERTION]: must be a valid cid
      + expected - actual

      -false
      +true
```

**Comment by haadcode** [comment]
Thanks @diasdavid for keeping us up to date! ❤️ 

Will try to work the new release into OrbitDB asap. Any ideas what the ^ `must be a valid cid` comes from? PubSub (as mentioned in https://github.com/orbitdb/ipfs-log/issues/124)?

**Comment by mistakia** [comment]
It doesn't look like `orbit-db` or `ipfs-log` has `js-ipfs-block` in its dependency tree though.

**Comment by diasdavid** [comment]
My recommendation is to update all deps.
