### ISSUE TITLE
OrbitDB in browser lacks the `Store#load` method

### ISSUE THREAD

**Issue by lukas2005** [orbitdb/orbit-db#378]
OrbitDB in browser lacks the `Store#load` method
Is there any reason behind this?
If it's because there's nowhere to save the data then: you could utilize `window.localStorage` for that

**Comment by maxkerp** [comment]
That doesn't sound right, are you sure? It should be part of the prototype.
Can you share some output?

**Comment by lukas2005** [comment]
Yeah when I use `await db.load()` I get a error saying that load doesn't exist

**Comment by RichardLitt** [comment]
Could you give more context for this? If not the file you're calling `db.load()` in, at least the imports and the relevant function

**Comment by aphelionz** [comment]
This issue is outdated, closing for now. Re-open if necessary
