### ISSUE TITLE
Cannot retrieve data locally after redirect

### ISSUE THREAD

**Issue by guoliu** [orbitdb/orbit-db#388]
Hi, I'm new to orbit-db, and thanks for this exciting project! My question might be naive so please bear with me.

I'm using `react`/`react-router-dom` to create a draft editor with `orbit-db`. `orbitdb` has been initialized and attached to `window`.

On one component I have:
```
const draft = await window.orbitdb.eventlog('test', {
  write: ['*']
})
await draft.add({
  editorState: createEditorState()
})
await draft.close()
```

which then returns an redirect:
```<Redirect to={`/draft${draft.address}`} push />```

Page `/draft${draft.address}` got the address correctly as `draftAddress`, then re-create the store with
```
const draft = await window.orbitdb.eventlog(draftAddress)
await draft.load()
```
However, `draft.iterator({ limit: -1 }).collect()` remains an empty array.

Is it because I have to sync with a peer after creating to retrieve it after redirect? Since all data are local, I'd expect to be able to just get back the database after redirection.

Thank you!

**Comment by guoliu** [comment]
Ah sorry I found out the issue. I was missing the `/` before `orbitdb/` which was stripped out by react-route. Closing this issue now.

**Comment by RichardLitt** [comment]
Thanks, @guoliu! Was there anything in the documentation that helped to cause that confusion, you think? Can we make it easier to catch in the future?
