### ISSUE TITLE
Can't find variable: regeneratorRuntime

### ISSUE THREAD

**Issue by Nipol** [orbitdb/orbit-db#390]
I using Parcel and Orbit-DB. and then Error!

```
ReferenceError: Can't find variable: regeneratorRuntime
```

sample Repository.
https://github.com/Nipol/Parcel-orbitdb

help me!

**Comment by RichardLitt** [comment]
Thanks a ton for setting up a sample repository for this! It'll make it easier to diagnose. We'll get to this when we are able to.

**Comment by tyvdh** [comment]
Hit this too trying to run on a DigitalOcean Ubuntu machine

**Comment by Nipol** [comment]
@tyvdh Thanks! I added babel according to your advice.

**Comment by RichardLitt** [comment]
Thanks for helping out, @tyvdh!

**Comment by RichardLitt** [comment]
Actually, @tyvdh - were you also using Parcel? Or was this more general? If so, we should add your fix to the documentation.

**Comment by tyvdh** [comment]
General. I don’t even know what Parcel is 😋

**Comment by RichardLitt** [comment]
Hmm. Good to know! Sounds like it is just an orbit-db mixup when using babel, then. Should we add that import in a PR?

**Comment by tyvdh** [comment]
Idk. It works fine locally on my Mac. So it must be some issue with the OS. Just having a reference to “if you have this issue, try including this package” is likely sufficient.

**Comment by RichardLitt** [comment]
Cool. In that case, let's just leave this issue here and if someone else finds that this is the solution, let us know and we'll add it to the docs.
