### ISSUE TITLE
Install fails while adding leveldown dependency

### ISSUE THREAD

**Issue by oskarpyke** [orbitdb/orbit-db#392]
Having some trouble installing orbit-db to my working directory. `npm i orbit-db` fails while trying to add `leveldown` as a dependency. `yarn add orbit-db` fails in a similar fashion. Gist of `verbose` log 

https://gist.github.com/Annorstades/9663c945ae48c9fc012a61cc253a4d58

Things apparently start to go south once `prebuild-install || node-gyp rebuild` is invoked.

**Comment by haoliangyu** [comment]
I can also confirm that the package installation does not work at node v10 and I have to fall back to node v8.

**Comment by mistakia** [comment]
you could override the `leveldown` dependency of `orbit-db-cache` using [selective dependency resolution in yarn](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it) for now (or setting the leveldown version in the `package-lock.json` file and installing via `npm ci`).

Hopefully orbitdb/orbit-db-cache#7 will be merged soon

**Comment by drwasho** [comment]
Can confirm this is a problem @haadcode

**Comment by haadcode** [comment]
***Note!*** *We don't officially support Node.js v10 yet as it's not yet LTS. Once it is, we'll officially support it. That said, I think this is really important to fix and get working and we might as well do it before v10 LTS.*

We've now updated the LevelDB related modules to v3.x and the updated dependencies are merged to master. The tests are passing locally with v10 and on CI with v8, so I'm assuming this is fixed. Note that this fix hasn't been published to npm yet, but we're expecting to make and publish a new release soon.

I'll leave the issue open until we have a new version of orbitdb in npm. Meanwhile, would highly appreciate if you'd test this and let us know if you're still experiencing problems! 🙏

**Comment by aphelionz** [comment]
Node 10 is stable now - this should be working for folks. Feel free to re-open or create a new issue if it's not.
