### ISSUE TITLE
Difference between store.close() and store.drop()

### ISSUE THREAD

**Issue by haoliangyu** [orbitdb/orbit-db#393]
The documentation does not provide details on what `close` means for the `store.close()` function. I wonder  how it is different from the `store.drop()` function.

**Comment by RichardLitt** [comment]
Thanks for opening, @haoliangyu. Did you figure out the difference? Could the docs be better?

**Comment by haoliangyu** [comment]
Sort of. I tried this code with no error:

```
await db.close();
await db.drop();
```

I though `close` should mean closing the connection and stopping the replication, but the data should remain and getabble/querable (not tested), maybe even writtable (not tested). The `drop()` function actually removes the data from the data store.

@RichardLitt If that's true, it would be a nice property and should be mentioned.
