### ISSUE TITLE
Start a community call

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit-db#394]
Having talked to several people about this privately, it seems that there's interest to do a bi-/weekly community call for OrbitDB to discuss progress, ask questions and general get together.

Let's try to make it a fixed time every week taking into consideration All The Timezones, which I suppose means sometime between 3pm to 5pm or similar. Another thing to consider is that many OS teams seem to have weekly calls on Monday's and people might have scheduling conflicts, so we should be considerate of that too.

Would love to hear who's interested to join on (semi-)regular basis and what the preferred times are?

Would Monday be a good day, or should we consider Tuesday or Wednesday?

Should we do a weekly or bi-weekly call?

**Comment by RichardLitt** [comment]
Glad to hear that there is interest! Let's get this going! I'm in.

What do you mean by 3-5pm? Do you mean 3-5pm CEST? I think it might be better to gauge who would be interested in attending the first one. Can we ping the relevant parties, and direct them to this issue to have their +1s for next Monday, @haadcode? Let's plan repeat calls after the first one.

**Comment by thiagodelgado111** [comment]
I'd like to join! I could do it on bi-weekly on Monday starting on July 9th but it seems Tuesdays/Wednesdays would be easier given the "everyone does Monday calls" factor :)

**Comment by haadcode** [comment]
ping at least @coyetespike @vvp @shamb0t

**Comment by rikur** [comment]
I would jump in.

**Comment by coyotespike** [comment]
While we're discussing dynamic access, we could do weekly, and then biweekly is probably more sustainable.

**Comment by RichardLitt** [comment]
Great. How about next Monday, at 3pm CEST. We can arrange better times given turnout and in the call. 

If you like this time, leave a 🎉 reaction on this comment.

**Comment by thiagodelgado111** [comment]
Oops, sorry, actually I can only do Mondays starting from July 16th not the 9th like I said 😞  – considering it'd happen at 3pm CEST. Can we do this first one on Tuesday (July 10th) instead?

**Comment by haadcode** [comment]
@RichardLitt I meant 3-5pm **UTC** (we should always use UTC+0 when referring to timezones to make it easier to coordinate), sorry for not being explicit.

I'm fine doing it on Tuesday/Wednesday(s) (let's pick a day and stick to it every week). 3pm CEST (1pm UTC+0) works for me, but I'm wondering if that works for @coyotespike?

**Comment by RichardLitt** [comment]
Cool. Thanks for clarifying about UTC. 

I forgot to say: if I seem to be making decisions and suggesting alternatives a bit hastily, it's because I've seen a lot of scheduling threads take ages because everyone is waiting for other people to take the initiative with a time. I'd rather be a bit wrong and have a call earlier than a bit right and have one a few weeks later than we could have. :)

**Comment by haadcode** [comment]
I like that you took the initiative to propose a time 👍😄

**Comment by 509dave16** [comment]
@haadcode Is there anything I need to do start contributing to orbit-db? Would like to at least be able to start adding tags to issues.

**Comment by RichardLitt** [comment]
@509dave16 Thanks for asking! I think that might be a bit off-topic for this thread, though; this is about the community call. Jumping on it would be a great way to get involved and let us get to know you more.

Otherwise, I would suggest taking a look at the Contributing section of this repo, and at all of the issues [labelled "help wanted"](https://github.com/orbitdb/orbit-db/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22). Helping to resolve those would be great. Triaging issues is something that we have under control for now, unless you find issues which could really use labels (please let us know in a comment if you do!)

Let me know if you've got any questions - perhaps open a new issue titled: "I want to help contributing!" or something similar. :) This repo, currently a work-in-progress, may be the best place to do that: https://github.com/orbitdb/welcome/.

**Comment by GriffGreen** [comment]
https://doodle.com/ is an amazing tool.... 
Poll for times:
https://doodle.com/poll/zmyvvi86hz2zztk3

Also i suggested https://meet.jit.si/orbitdb (its an open source appearin)

**Comment by RichardLitt** [comment]
Thanks @GriffGreen. It's a bit late for a doodle since the meeting is tomorrow, but I think it'll help us next time we schedule one (and to see the availability of participants this time who are super responsive, at least :D). 

Let's assume 1300 UTC on Tuesday unless no one else can make it. Everyone, fill out the doodle poll if you could. :)

**Comment by GriffGreen** [comment]
Thx @RichardLitt my bad! I wasn't able to pull that out by skimming above.

1300 UTC on Tuesday which is:
6 am - LA time
9 am - NYC time
3 pm - Berlin time
8 pm - Thai time 

Someone from Giveth will for sure be there :-D

**Comment by RichardLitt** [comment]
Great. If anyone is here from the West Coast, let us know; we can switch up the meeting times to make it not so horrible for you in the future.

**Comment by rikur** [comment]
East coast here, but unfortunately tomorrow is a conference day. I'll join next week.

**Comment by RichardLitt** [comment]
Alright. I've set up a [Zoom meeting](https://zoom.us/) that we can use (I have a paid plan).

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/295694931

Or iPhone one-tap :
    US: +19294362866,,295694931#  or +16699006833,,295694931# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 929 436 2866  or +1 669 900 6833 
    Meeting ID: 295 694 931
    International numbers available: https://zoom.us/u/bIBDlJvH

If anyone wants me to invite their email, send a note to richard@maintainer.io and I'll go ahead and do that.

**Comment by haadcode** [comment]
Let's take notes here https://hackmd.io/5ZNf0nHnQSqUErnFREgFZg (I'll volunteer).

**Comment by vvp** [comment]
I'll join too! :slightly_smiling_face:

**Comment by RichardLitt** [comment]
Notes!

# orbit-db community call

date: Tue 10th of July, 2018
notetaker: @haadcode
moderator: @richardlitt

## participants
- @RichardLitt
- @vvp
- @haadcode
- @shamb0t
- @thiagodelgado111
- @coyotespike


## agenda
- Assign notetaker and moderator
- logo
    - have a logo proposals (2nd iteration based on initial idea and feedback)
    - discussed which one is the favorite
    - @richardlitt to open an issue and decide which
- access controller
    - design discussion last week, nobody worked on the implementation
    - https://github.com/orbitdb/ipfs-log/pull/128
    - A PR merging the ideas on 123, 127 and 128: https://github.com/orbitdb/ipfs-log/pull/131
- next release
    - @haadcode started release notes 3 months ago, and the PR is still open. Waiting for the access controller, but this has been lagging, so let's just make a release now.
    - Let's not set dates, maybe? It's still _ad hoc_. Let's release whenever it is good enough to release.
- "security bug" found
    - https://github.com/orbitdb/orbit-db-store/pull/28
- replication perf in ipfs-log
    - @haadcode has been working on this for a while in his computer
    - Visualisation thing
    - This is coming soon. 
- linting
    - https://github.com/thiagodelgado111/eslint-config-orbitdb
    - https://github.com/orbitdb/ipfs-log/pull/130
    - https://github.com/orbitdb/orbit-db/issues/338
    - @haadcode will check standard again to see if he still disagrees with them
- Move repos from @haadcode to @orbitdb https://github.com/orbitdb/welcome/issues/4
    - @haadcode to follow up
- OrbitDB or orbit-db? https://github.com/orbitdb/welcome/issues/5
    - "OrbitDB"
    - OrbitChat or Orbit Chat?
    - Orbit Chat.
- Change @orbitdb/maintainers https://github.com/orbitdb/welcome/issues/7
    - Haad will ping them if he sees David or Victor this week
- Move orbitdb/orbit? https://github.com/orbitdb/welcome/issues/8
    - keep the repo as it is
- Community Projects board https://github.com/orgs/orbitdb/projects/1
    - Richard is doing work here on the community; follow along or add things if you like!
- Directories list: https://github.com/orbitdb/welcome/pull/3
    - @RichardLitt needs review 

The next community call will be in two weeks. I'll announce it here. :)

**Comment by RichardLitt** [comment]
The next call is scheduled for July 24th at 1300UTC. See https://github.com/orbitdb/welcome/issues/12.
