### ISSUE TITLE
Database Type

### ISSUE THREAD

**Issue by yuppies09** [orbitdb/orbit-db#400]
What sort of database type can be created with orbit db when implementing it with IoT data. Also I have been using go-ipfs for all the experiments with IPFS. But I don't find a version of orbit DB with go-ipfs. But implementation with js.ipfs exists. If I install them in the same machine will it still work?

**Comment by RichardLitt** [comment]
I'm not sure of the answers to these. But I suspect that orbitdb is data format agnostic, so it doesn't matter if you're working with iot. As well, orbit is implemented in JS, but it shouldn't matter which IPFS implementation you have running. The go implementation should be fine.

**Comment by mistakia** [comment]
All data is stored in an append-only (immutable) log, [`ipfs-log`](https://github.com/orbitdb/ipfs-log). However, depending on how you will be retrieving data - OrbitDB has many [Stores](https://github.com/orbitdb/orbit-db-store) to provide functionality you would typically find in document stores, keyvalue stores, etc. 

You could also build your [own custom store](https://github.com/orbitdb/orbit-db#custom-store-types) to provide for any special indexing or retrieval that may be needed in your case, but everything at the end of the day is stored using `ipfs-log`.

**Comment by mistakia** [comment]
As for using it with `go-ipfs` - you can use OrbitDB with [`js-ipfs-api`](https://github.com/ipfs/js-ipfs-api) which can then communicate to a `go-ipfs` instance running locally (via the http api). You can use [`js-ipfsd-ctl`](https://github.com/ipfs/js-ipfsd-ctl) to programatically spin up ipfs daemon instances (go or js).

Some more info [here](https://github.com/orbitdb/orbit-db/blob/master/API.md#using-with-a-running-ipfs-daemon).

**Comment by aphelionz** [comment]
@yuppies09 Closing this now and referring people to the [OrbitDB Field Manual](https://github.com/orbitdb/field-manual) if they have more questions. Feel free to open an issue or a PR if you have more questions!
