### ISSUE TITLE
Embedding and using OrbitDB exclusively from browser HTML / JavaScript

### ISSUE THREAD

**Issue by MirceaKitsune** [orbitdb/orbit-db#403]
Greetings. I'm thinking of creating my first IPFS application with the help of OrbitDB. I'm relatively familiar with IPFS but new to Orbit, about which I have a few questions. This is the first one which is essential for me knowing whether Orbit can be used in the way that I need.

First a bit of background on what I want to do: My goal is to create a website similar to social media (Facebook, Twitter, etc). I want the site to be fully based on HTML and JavaScript, using IPFS and OrbitDB for storage... no server side scripting, anyone who downloads the bundle and opens the HTML file in a browser can use the system. For the site to be as user friendly as any normal page on the internet, I cannot require the end user to install either IPFS or Orbit on their own and run them in the background... and that is where my question comes in.

The [guide](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md) mainly explains how to use Orbit after installing it as a npm module and I believe running it via NodeJS. What I wish to know is whether it can be embedded into a website, so anyone visiting that site from a standard web browser (at least Chromium or Firefox) gets the desired functionality via JS embedded on the page. In this ideal scenario, the HTML file simply points to an orbitdb.js file on say Github in a <script> tag, then my own script later uses its functions to work with the databases. Note that for this to be possible https://gateway.ipfs.io/ipfs/ might need to be the URL in use by OrbitDB locally.

Is this form of usage possible, can Orbit be used from website JS without the user accessing the site having to install anything? If so are there any examples for this specific scenario, including configuring the IPFS gateway Orbit should work with in this case? Thank you.

**Comment by MirceaKitsune** [comment]
My question has been answered in [this thread](https://discuss.ipfs.io/t/embedding-and-using-orbitdb-exclusively-from-browser-html-javascript). I managed to get a browser node working using the browser example in OrbitDB. I can create and read a database through IPFS flawlessly!

**Comment by RichardLitt** [comment]
@MirceaKitsune That's awesome! Glad you got your question answered.

Would you be willing to help us document this better for the next person, so that they don't need to search through the issues? Adding something to the README should help, for now, I think, although a tutorial like the Guide would be better, I think.

**Comment by MirceaKitsune** [comment]
@RichardLitt What I did is already documented, though might not be easy to see unless you know where to look. I only had to follow the instructions in the following two paragraphs from the README.MD:

https://github.com/orbitdb/orbit-db#install-dependencies
https://github.com/orbitdb/orbit-db#browser-example

**Comment by RichardLitt** [comment]
Got it! Alright. In that case, I think we'll just keep this as it is for now. Thanks, @MirceaKitsune :)
