### ISSUE TITLE
Using orbit-db without pubsub

### ISSUE THREAD

**Issue by oed** [orbitdb/orbit-db#425]
Is it possible to use orbit-db with a go-ipfs node that doesn't have pubsub enabled? (My guess is no, not at this point) How hard would it be to make this happen?

The use case I'm considering is the following. User creates a db locally (or connected to a remote go-ipfs node). It then sends the hash of the db to a server which fetches and pins all the objects of the db. When the user goes online with a different computer they can ask the server about the latest hash and fetch the data. This could also be done similarly with multiple users of a db.

**Comment by mistakia** [comment]
Doable and shouldn't be too hard — depends more on content discovery (i.e. DHT, etc) working well on IPFS.

The server will need the head entry. Using the head, the server can retrieve the previous entries by following the `next` pointer and feeding them to [`Log.fromEntryHash`](https://github.com/orbitdb/ipfs-log/blob/master/src/log.js#L446) — the entries will need to be available and discoverable on IPFS.

A few good spots to look under the hood: [`Store.sync()`](https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L222) & [`Replicator._processOne()`](https://github.com/orbitdb/orbit-db-store/blob/master/src/Replicator.js#L152)

**Comment by mistakia** [comment]
If my understanding is accurate — Pubsub is used to efficiently exchange heads between peers of a given db. Without Pubsub, you'll have to handle the exchange of heads oob but can then feed the heads to `Store.sync()`.

**Comment by oed** [comment]
Thanks, sounds like it shouldn't be too hard to implement. My main problem thought is that when creating a db on an ipfs node without pubsub enabled I get this error:
```
UnhandledPromiseRejectionWarning: Error: experimental pubsub feature not enabled. Run daemon with --enable-pubsub-experiment to use
```

**Comment by mistakia** [comment]
Hmm - my first suggestion would be to pass `{replicate: false}` as an option when creating

**Comment by oed** [comment]
That worked, thanks! Didn't know it was an option, don't think it's in the API doc :)
