### ISSUE TITLE
Add a distribution package for browsers

### ISSUE THREAD

**Issue by hazae41** [orbitdb/orbit-db#439]
If OrbitDB aims to be used in browsers, why do you share a distribution package for nodejs and not for browsers?

**Comment by aphelionz** [comment]
@hazae41 What people currently do is use the files in `dist/` or use a tool like unpkg. How can we improve this?

**Comment by hazae41** [comment]
There was no dist/ in older versions of orbit-db

**Comment by aphelionz** [comment]
Thanks @hazae41
