### ISSUE TITLE
Syncing db by only knowing latest head hash

### ISSUE THREAD

**Issue by oed** [orbitdb/orbit-db#447]
Hey, I'm trying to sync a orbitdb store to it's most recent state by only knowing the hash of the most recent head. However after calling `.sync` on the store it remains empty. What am I doing wrong? Is there a better way to do this?

Below is my code for doing the sync.
```js
  async _sync (hash) {
    if (!this.db) {
      const orbitdb = new OrbitDB(this.ipfs)
      this.db = await orbitdb.keyvalue('3box.datastore', {
        replicate: false,
        write: ['*']
      })
    }
    if (hash) {
      let log = await Log.fromEntryHash(this.ipfs, hash)
      // sync orbitdb to hash
      await this.db.sync(log.values)
    }
  }
```

**Comment by haadcode** [comment]
@oed thanks for the question!

Is `sync` call throwing any errors if you add try/catch around it? I'm not sure, but I think `.fromEntryHash` requires the third parameter `id` which is the address of the db (`this.db.address`). Perhaps that solves it?

**Comment by haadcode** [comment]
It might also need the 6th and 7th args (sorry! we're improving this in the upcoming release), key and access list, see here for an example: https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L211.

**Comment by oed** [comment]
@haadcode tnx for the quick response! 
Not throwing any errors when doing the sync. Strange thing is if I log `log.values` I get the array of entries which does seem correct. However syncing to the store does nothing. Do you still think that it's an issue with the call to `fromEntryHash`?

Here is the contents of `log.values`
```
    [ { hash: 'QmWBo4YUeonewZBbLygdVKetuiYuMhxy7YfTSG2gYwA29K',
        id:
         '/orbitdb/QmSYP6ujFsASqQMnP2hiV7B9AH7HgE2U3PMJFnC7JUvfTh/3box.datastore',
        payload:
         { op: 'PUT',
           key: 'key1',
           value: 'asd9hfg0847h.such encrypted, wow!value1' },
        next: [],
        v: 0,
        clock:
         { id:
            '04c4aec1d999f574479b9125c9633ebd686cc28be92e037566677a68fbf11f190070ddc32672e5a1e7304a5bb131345bf0a0dd56a32eb180b3b04f93aa0c20306c',
           time: 1 },
        sig:
         '30450220109bb6c7900219b4a45c28310c3a59eab03783419411af993a0f9cab932eef280221009f8e985411e4b2493cf8ea6d6e7ffb663d20fe4f9cc9399a5c4bda9f47d28ff0',
        key:
         '04c4aec1d999f574479b9125c9633ebd686cc28be92e037566677a68fbf11f190070ddc32672e5a1e7304a5bb131345bf0a0dd56a32eb180b3b04f93aa0c20306c' },
      { hash: 'QmcJo9nbt61gmtPLWEmhsohbp54GUG3EdYMm5XkQoUsuuv',
        id:
         '/orbitdb/QmSYP6ujFsASqQMnP2hiV7B9AH7HgE2U3PMJFnC7JUvfTh/3box.datastore',
        payload:
         { op: 'PUT',
           key: 'key2',
           value: 'asd9hfg0847h.such encrypted, wow!lalalla' },
        next: [ 'QmWBo4YUeonewZBbLygdVKetuiYuMhxy7YfTSG2gYwA29K' ],
        v: 0,
        clock:
         { id:
            '04c4aec1d999f574479b9125c9633ebd686cc28be92e037566677a68fbf11f190070ddc32672e5a1e7304a5bb131345bf0a0dd56a32eb180b3b04f93aa0c20306c',
           time: 2 },
        sig:
         '30450220109bb6c7900219b4a45c28310c3a59eab03783419411af993a0f9cab932eef280221009f8e985411e4b2493cf8ea6d6e7ffb663d20fe4f9cc9399a5c4bda9f47d28ff0',
        key:
         '04c4aec1d999f574479b9125c9633ebd686cc28be92e037566677a68fbf11f190070ddc32672e5a1e7304a5bb131345bf0a0dd56a32eb180b3b04f93aa0c20306c' },
      { hash: 'QmcyYVF9s54jDCqdtmAqdjurietV8hpTmSdVnYYmvPjDDW',
        id:
         '/orbitdb/QmSYP6ujFsASqQMnP2hiV7B9AH7HgE2U3PMJFnC7JUvfTh/3box.datastore',
        payload:
         { op: 'PUT',
           key: 'key3',
           value: 'asd9hfg0847h.such encrypted, wow!12345' },
        next:
         [ 'QmcJo9nbt61gmtPLWEmhsohbp54GUG3EdYMm5XkQoUsuuv',
           'QmWBo4YUeonewZBbLygdVKetuiYuMhxy7YfTSG2gYwA29K' ],
        v: 0,
        clock:
         { id:
            '04c4aec1d999f574479b9125c9633ebd686cc28be92e037566677a68fbf11f190070ddc32672e5a1e7304a5bb131345bf0a0dd56a32eb180b3b04f93aa0c20306c',
           time: 3 },
        sig:
         '30450220109bb6c7900219b4a45c28310c3a59eab03783419411af993a0f9cab932eef280221009f8e985411e4b2493cf8ea6d6e7ffb663d20fe4f9cc9399a5c4bda9f47d28ff0',
        key:
         '04c4aec1d999f574479b9125c9633ebd686cc28be92e037566677a68fbf11f190070ddc32672e5a1e7304a5bb131345bf0a0dd56a32eb180b3b04f93aa0c20306c' },
      { hash: 'QmXqTAFLHq8t5QFqZZJKyDMdzLhQWexDNKUVSJYXbMKnHc',
        id:
         '/orbitdb/QmSYP6ujFsASqQMnP2hiV7B9AH7HgE2U3PMJFnC7JUvfTh/3box.datastore',
        payload: { op: 'PUT', key: 'key3', value: null },
        next:
         [ 'QmcyYVF9s54jDCqdtmAqdjurietV8hpTmSdVnYYmvPjDDW',
           'QmcJo9nbt61gmtPLWEmhsohbp54GUG3EdYMm5XkQoUsuuv',
           'QmWBo4YUeonewZBbLygdVKetuiYuMhxy7YfTSG2gYwA29K' ],
        v: 0,
        clock:
         { id:
            '04c4aec1d999f574479b9125c9633ebd686cc28be92e037566677a68fbf11f190070ddc32672e5a1e7304a5bb131345bf0a0dd56a32eb180b3b04f93aa0c20306c',
           time: 4 },
        sig:
         '30450220109bb6c7900219b4a45c28310c3a59eab03783419411af993a0f9cab932eef280221009f8e985411e4b2493cf8ea6d6e7ffb663d20fe4f9cc9399a5c4bda9f47d28ff0',
        key:
         '04c4aec1d999f574479b9125c9633ebd686cc28be92e037566677a68fbf11f190070ddc32672e5a1e7304a5bb131345bf0a0dd56a32eb180b3b04f93aa0c20306c' },
      { hash: 'QmPHuR66KzGLayZZ2mJSt4FubKk5ydRvPpLD5cc48LDgiT',
        id:
         '/orbitdb/QmSYP6ujFsASqQMnP2hiV7B9AH7HgE2U3PMJFnC7JUvfTh/3box.datastore',
        payload: { op: 'PUT', key: 'key2', value: null },
        next:
         [ 'QmXqTAFLHq8t5QFqZZJKyDMdzLhQWexDNKUVSJYXbMKnHc',
           'QmcyYVF9s54jDCqdtmAqdjurietV8hpTmSdVnYYmvPjDDW',
           'QmcJo9nbt61gmtPLWEmhsohbp54GUG3EdYMm5XkQoUsuuv',
           'QmWBo4YUeonewZBbLygdVKetuiYuMhxy7YfTSG2gYwA29K' ],
        v: 0,
        clock:
         { id:
            '04c4aec1d999f574479b9125c9633ebd686cc28be92e037566677a68fbf11f190070ddc32672e5a1e7304a5bb131345bf0a0dd56a32eb180b3b04f93aa0c20306c',
           time: 5 },
        sig:
         '30450220109bb6c7900219b4a45c28310c3a59eab03783419411af993a0f9cab932eef280221009f8e985411e4b2493cf8ea6d6e7ffb663d20fe4f9cc9399a5c4bda9f47d28ff0',
        key:
         '04c4aec1d999f574479b9125c9633ebd686cc28be92e037566677a68fbf11f190070ddc32672e5a1e7304a5bb131345bf0a0dd56a32eb180b3b04f93aa0c20306c' } ]
```

**Comment by oed** [comment]
I had no luck with adding the additional params to `Log.fromEntryHash` btw :/

**Comment by haadcode** [comment]
So it wasn't that :)

At what point do you query the db after calling `sync()`? Right after `await this.db.sync(log.values)`? If that's the case, then that might be it. The way `sync()` works is that it just passes the hashes to the replicator, which then will emit events once it has loaded all the log that was referenced by the given hashes. So in short, if the db is queried right after sync(), it may not have finished the replication yet and thus gives an empty result. The way to test it is to listen for the `replicated` event and query the db after it has been fire, eg.
```javascript
this.db.events.on('replicated', (address, logLength) => {
  /* query db here */
  const value = this.db.get('key1')
  console.log(value)
})
await this.db.sync(log.values)
```

Let me know if that works and if not, happy to dig deeper!

**Comment by oed** [comment]
That was it! Didn't know that the replication didn't happen in one go. 
Thank you @haadcode :)

**Comment by oed** [comment]
Another question related to this that I have is that `fromEntryHash` seem to add the entry to ipfs to check if the hash is correct. In my case this seems like unnecessary overhead since I fetched the entries from ipfs in the first place. Am I missing something?

**Comment by haadcode** [comment]
@oed awesome, glad to hear that solved it! Given all that, I think we should improve the semantics of `sync()` and replication so that they're more intuitive for the users. 

Any suggestions this can be improved would be highly appreciated!

**Comment by haadcode** [comment]
> Another question related to this that I have is that fromEntryHash seem to add the entry to ipfs to check if the hash is correct. In my case this seems like unnecessary overhead since I fetched the entries from ipfs in the first place. Am I missing something?

Indeed it tries to save to IPFS on sync. The background for that is that it was originally meant to be used only when entries were received from other peers via pubsub and not meant for "local replication" (ie. when the data is already in IPFS). It works in both cases, but as you said, there's an overhead there that may not be needed. That said, I believe IPFS doesn't "double store" the data but returns early after realizing that the data is already stored, so I think (although I'm not 100% sure) it doesn't hit disk (but there is still the overhead as you described).

I'd be curious to understand your use case a little better to propose a possible solution. It may be that you don't need `sync()` but can do it in a different way. And if not, we can try and add something that solves the overhead problem for you. Feel free to post here or reach out on IRC or [Gitter](https://gitter.im/orbitdb) to chat more!

**Comment by oed** [comment]
> Any suggestions this can be improved would be highly appreciated!

Maybe something like `queueForReplication`? But maybe that misses some other aspect of what it's used for?

> That said, I believe IPFS doesn't "double store" the data but returns early after realizing that the data is already stored

Didn't know that, ty.

The use case I have is as follows: Users create a store locally (but using a remote ipfs node). They then post the latest hash to a server which keeps track of each users latest head hash. If the user then at a later point connects using a different browser for example, they will be able to retrieve the hash from the server and sync their personal db to the latest state. 
I hope that makes sense ^^

Btw, seems like the matrix.org bot have been banned from your IRC channel because I can't find it using riot. (Joined the gitter now instead :))
