### ISSUE TITLE
bootstrapping in local network doesn't seem to work?

### ISSUE THREAD

**Issue by shi-yan** [orbitdb/orbit-db#454]
Hello,

tried to get a test net up, but bootstrapping doesn't seem to work. I have 2 computer under the same wifi network. exchanged address like:

ipfs.bootstrap.add(/ip4/192.168.1.27/tcp/4002/ipfs/QmW16nMgkcJqeZNnaVa1k9DyYB7J8VwH1gxdYfiP8xp71p)

but the two computer didn't seem to see each other. I have waited for quite long time, didn't see the   db.events.on('replicated' event fired. 

What should I do?

Also the example https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#replicating-a-database doesn't work for me either, because both orbitdb instances will need the port 4002, and I didn't see an option to change the port?

Thanks.

**Comment by oed** [comment]
It's possible to change the port of ipfs. See [here](https://github.com/ipfs/js-ipfs#optionsconfig)

**Comment by shi-yan** [comment]
I have figured this out. the jsipfs document isn't clear on how to do bootstrapping and confused me . after reading https://github.com/ipfs/js-ipfs/issues/1304

and doing:

`const ipfs = new IPFS({
  repo: './orbitdb/examples/ipfs',
  start: true,
  EXPERIMENTAL: {
    pubsub: true,
  },
  config: {
    Bootstrap: ['/ip4/192.168.1.27/tcp/4002/ipfs/QmW16nMgkcJqeZNnaVa1k9DyYB7J8VwH1gxdYfiP8xp71p']
  }
})`

it all worked.
