### ISSUE TITLE
Which mecanism does orbitdb use for read/write access?

### ISSUE THREAD

**Issue by maroodb** [orbitdb/orbit-db#458]
read/write access control isn't implemented in IPFS spec, so which mecanisme is used by orbitdb ?

**Comment by RichardLitt** [comment]
IIRC, we haven't implemented this yet. One of the other maintainers should know.

**Comment by shamb0t** [comment]
Hi @maroodb!

There is currently no read-access control. Anyone with the address and network access can read the contents of the db. For write-access, an immutable list of write-capable keys must be added at db creation as shown [here](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#access-control). Though we are in the process of changing this mechanism to add support for dynamically adding write-capabilities (we are removing `orbitdb.key` in favor of using an [identity](https://github.com/orbitdb/orbit-db-identity-provider) as `orbitdb.identity`). Key-revocation is still an open discussion and is not currently being implemented. I hope this answers your question!

**Comment by aphelionz** [comment]
Closing and referring people to the [OrbitDB Field Manual](https://github.com/orbitdb/field-manual) if they have more questions.
