### ISSUE TITLE
Syncing db 

### ISSUE THREAD

**Issue by ajayrao80** [orbitdb/orbit-db#460]
Here's the scenario. PeerA comes online, loads the db from remote address, does some operations and updates the values of the database and goes offline. PeerB comes online, loads the database, and starts reading the entries. Does the entries contain the ones made by PeerA?

**Comment by RichardLitt** [comment]
Good question. Some clarifications: Did PeerA access the internet after they've updated the values, or was that only locally? Are there other nodes which hold the db besides PeerA and PeerB?

**Comment by aphelionz** [comment]
Some explicit answers to the questions asked here:

> Does the entries contain the ones made by PeerA?

No, not in the scenario you described. In a peer-to-peer swarm the data isn't persisted anywhere automatically. There ARE pinning services that help with this, but by default those entries are offline along with Peer A

> Did PeerA access the internet after they've updated the values, or was that only locally?

If they did and they were replicated by another peer, or pinned via a service, then this is good news! The entries could well be out there.

> Are there other nodes which hold the db besides PeerA and PeerB?

Likewise this - any online peer will be making the OrbitDB address available. More good news, if this is the case :+1: 

Also, if you have more questions, we just released the [OrbitDB Field Manual](https://github.com/orbitdb/field-manual). Check it out and feel free to open issues / PRs if you see fit!
