### ISSUE TITLE
A distributed forum based on OrbitDB

### ISSUE THREAD

**Issue by klueq** [orbitdb/orbit-db#465]
Is OrbitDB the right model for a distributed/decentralised forum?

In short, we say that a forum is a set of `(name, data)` pairs, e.g.:

- `name = "posts/4/comments/8/README.md"`
- `data = "Hello world!"`

Every forum user keeps a partial copy of this set. When someone wants to add a new `(name, data)` entry, it sends it to the peers, they verify the new entry and re-transmit further. Then we write UI on top of this and the forum is done.

This is a more detailed [description](https://github.com/klueq/shared-folder-ipfs) of this idea.

I wonder if OrbitDB can do this kind of p2p file system.

**Comment by lukas2005** [comment]
This sound like a good idea. I think this can be done. Altho with the current lack of dynamic permissions moderating that forum would be impossible (cause either the whole forum would be read/write/delete for all or nobody would be able to remove other user's content which is also bad)

**Comment by klueq** [comment]
That's a good point about the moderating permissions. However I think it's possible. When I said "they verify the new entry" I really meant that they run a Lua/JS script that verifies every new `(name, data)` pair. The script can also verify access control. For example, our forum may look like this:

```
README.md
posts/
users/
mods/
```

The script then verifies that only those in the `users/` folder may add new files and only those in the `mods/` folder may add special files that would make the UI hide the corresponding posts/comments. We can use the public RSA keys to verify identity.

Deleting files isn't possible in this model, but files can be hidden at the UI level:

```
posts/
hidden-posts/
```

If a reference to a post is added to `hidden-posts`, the UI hides it. It can't be unhidden, but we can fix even that if we need to. In practice, I think, it's better for every user to maintain filter at the UI level. For example, reddit is not readable unless I hide 99% of stuff that people post there: that stuff is ok from the mods point of view, but it doesn't help me much. Same here.

Of course, all this moderating stuff shouldn't be in the protocol. We only say that every forum has a special rules Lua/JS script that does any sort of checks that the forum creator chose appropriate. No moderation is the default option: then content cannot be taken down even by the forum creator.

However, if there is a model which allows to not only add, but also delete files, and do that in a spam resilient and consistent manner without carrying the entire history of changes, then it would be a big step forward. We could then develop more dynamic apps like an online chess server: there is an `active-games/` folder where files are constantly added and removed.
