### ISSUE TITLE
typescript typings

### ISSUE THREAD

**Issue by lukas2005** [orbitdb/orbit-db#466]
I created some basic typescript typings. they don't have comments and some of the values/methods/classes are missing but it's better than nothing :+1: 
[@types.zip](https://github.com/orbitdb/orbit-db/files/2424470/types.zip)

**Comment by RichardLitt** [comment]
Thanks @lukas2005. Can you explain a bit more what these are for? I'm confused, and I don't really want to download a random zip file without knowing what this is about. :D

**Comment by lukas2005** [comment]
These are typings for orbitdb itself and all the official stores. Also maybe i should make a repo for them :thinking:

**Comment by lukas2005** [comment]
Okay I uploaded the typing to my project's repo: https://github.com/Anchor-Chat/AnchorAPI/tree/master/src/%40types/orbit-db

**Comment by lukas2005** [comment]
Decided to move them to a separate repo: https://github.com/lukas2005/-types-orbit-db

**Comment by cryptoquick** [comment]
@lukas2005 you are awesome, thank you
also, lol, cool database, but it's 2019, we're gonna need some typescript typings

**Comment by RichardLitt** [comment]
> also, lol, cool database, but it's 2019, we're gonna need some typescript typings

This isn't entirely constructive. Would you like to PR something? :)

**Comment by cryptoquick** [comment]
@RichardLitt um, @lukas2005 literally created a repo with TypeScript typings for you :)

**Comment by cryptoquick** [comment]
I shouldn't be flippant, I appreciate your work, but it makes it hard to work with as a TypeScript developer. The entire IPFS ecosystem is rather unapproachable because of it. I use TypeScript to discover APIs and save me lots of time. If I were you, I'd highly recommend looking into using it for your project. FWIW.

**Comment by aphelionz** [comment]
@cryptoquick @RichardLitt This seems reasonable, but I admit I'm not a TypeScript dev so I don't know how these would properly be incorporated. Is it sufficient to run `npm i --save https://github.com/lukas2005/orbit-db-types` as @lukas2005 suggets or does this require a tighter integration? Maybe we can call more attention to it from the README?

**Comment by cryptoquick** [comment]
After doing some in-depth research into Scuttlebutt / ssb-db, I'm going to see how far I can get into using ipfs-js + electron main thread + orbitaldb as the basis for a social network. If things go well with that, I'd be happy to help create a TypeScript conversion branch for this project, if you like. You could then try it out and see how it goes.

As for TypeScript typings themselves, I've been having mixed luck with using @lukas2005 's typings in my project so far. I had to use the typings separately so far. Like this:

```typescript
const OrbitDB = require('orbit-db')
import { OrbitDB as IOrbitDB } from 'orbit-db'

const launch = (): Promise<IOrbitDB> =>
  new Promise(resolve => {
    ipfs.on('ready', () => {
      const orbitdb = new OrbitDB(ipfs)
      resolve(orbitdb)
    })
  })
```

**Comment by aphelionz** [comment]
It looks like there's also some other TypeScript work going on here: https://github.com/orbitdb/orbit-db/issues/347. Again, not being a TS user myself I would look to the community for guidance here.

**Comment by aphelionz** [comment]
@RichardLitt I was thinking that as well.

For the time being, I'd be happy to point people in @lukas2005 's direction, contingent upon @cryptoquick's approved.

**Comment by RichardLitt** [comment]
If you want, @lukas2005, we could also transfer your repo to the OrbitDB organization and give you and @cryptoquick admin rights for it. If others in the community are using it, that might be the best solution.

**Comment by cryptoquick** [comment]
Ideally these typings would be included in the main project so they're easily available. Do you agree, @lukas2005 ?

**Comment by lukas2005** [comment]
yeah i guess that's a good idea

czw., 3 sty 2019 o 02:46 Hunter Trujillo <notifications@github.com>
napisał(a):

**Comment by lukas2005** [comment]
i'm just gonna look into the few issues that a few people pointed out and
make a PR

czw., 3 sty 2019 o 19:54 Łukasz Mariański <lukas2005.38@gmail.com>
napisał(a):

**Comment by aphelionz** [comment]
@cryptoquick @lukas2005 For now, please keep the bindings in the repo they are currently in. As it stands right now, the OrbitDB team is only a handful of people and things are moving fast for us. The maintenance responsibility of keeping the bindings up to date is something that we unfortunately can't take on right now and would need to rely on the community for.

@lukas2005 if you're ok with it, we will happily add your repo to the readme and, if you would like, move the repo under the official orbitdb namespace and give you access, as @RichardLitt suggested.

**Comment by lukas2005** [comment]
Yeah I'm fine with that so I guess I just do a repo transfer and then you
give me access?

pt., 4 sty 2019, 16:43: Mark Robert Henderson <notifications@github.com>
napisał(a):

**Comment by lukas2005** [comment]
Ah but I have to have create repo perms on the org

niedz., 6 sty 2019, 00:36: Łukasz Mariański <lukas2005.38@gmail.com>
napisał(a):

**Comment by aphelionz** [comment]
Great. @RichardLitt can you facilitate @lukas2005 getting the repo?

**Comment by lukas2005** [comment]
@cryptoquick try importing OrbitDB using the ts method:
```ts
import OrbitDB from "orbit-db";
```
that works for me

**Comment by RichardLitt** [comment]
@lukas2005 Added you to an org team. Let me know if you can't transfer it!

**Comment by lukas2005** [comment]
Nope It says I have to have create repo perms

niedz., 6 sty 2019, 17:34: Richard Littauer <notifications@github.com>
napisał(a):

**Comment by RichardLitt** [comment]
Try now. :)

**Comment by lukas2005** [comment]
Still nope

wt., 8 sty 2019, 15:39: Richard Littauer <notifications@github.com>
napisał(a):

**Comment by RichardLitt** [comment]
I added you to the org. Check your email. :) 

(Sorry, everyone, for the noise).

**Comment by aphelionz** [comment]
Pull request submitted! We're very close.

**Comment by RichardLitt** [comment]
\o/
