### ISSUE TITLE
Proper Way To Replicate DB and Access From Another Device

### ISSUE THREAD

**Issue by jehunter5811** [orbitdb/orbit-db#468]
Great project! I can very easily log in with uPort and store data. However, it seems I am only storing data to local storage, because when I use another browser as a test of accessing from another device, I cannot open the DB created from Browser1. Here's what I'm trying: 

on Browser1: 

```
export function loadDB() {
  ipfs.on('ready', async () => {
    const orbitdb = new OrbitDB(ipfs)
    db = await orbitdb.open("/orbitdb/QmdABCZSfHpGunEEZznoWsXWcRTKgFvawVh4LSL1m8YqEd/first-database", {create: true, type: "keyvalue"})
    db.load()
    .then(() => {
      this.handleGet();
    });
  })
```

Note: handleGet() loads the previously stored documents, which works on Browser1. I am also passing a hard-coded orbitdb address for now as I test. 

Now, on Browser2, I am trying to load the DB using the exact same code as above, but the documents I stored in Browser1 do not load. I get an empty object instead. 

Any help would be greatly appreciated because I know I'm doing something wrong here. Just can't figure it out.

**Comment by lukas2005** [comment]
Are you using `js-ipfs` or `js-ipfs-api` + go-ipfs?

**Comment by jehunter5811** [comment]
Thanks, @lukas2005! I'm using js-ipfs (I think). I went through the quick start guide instructions on OrbitDB to get started: 

```npm install orbit-db ipfs```

So are you saying that with the configuration example you provided, you can manually specify servers with js-ipfs? And if so, are those standard websocket signaling server addresses or do I have to provide my own?

**Comment by lukas2005** [comment]
the node.js `ipfs` package is `js-ipfs` and yes those are the official ones. You can also run your own signal server if you want using https://github.com/libp2p/js-libp2p-websocket-star-rendezvous

**Comment by jehunter5811** [comment]
Thanks a lot. I can't get it to work with that configuration, and I feel like I'm missing a step somewhere that's just not documented maybe: 

```webSocket connection to 'wss://ws-star-signal-1.servep2p.com/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED```
