### ISSUE TITLE
orbitdb.open hangs

### ISSUE THREAD

**Issue by lukas2005** [orbitdb/orbit-db#469]
For some reason my code just hangs on this line of code: `let userLog = await orbitdb.open(USER_LOG_ADDRESS, {type:"eventstore"}) as EventStore;
` (TypeScript)

USER_LOG_ADDRESS is `/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog` and it points to a eventstore database i created using this script: https://github.com/Anchor-Chat/AnchorAPI/blob/d2956953f568b9844c744db89411485664644b04/scripts/create-public-db.js

Full code:
https://github.com/Anchor-Chat/AnchorAPI/tree/master/src/AnchorAPIBuilder.ts

To run this code:
```
git clone https://github.com/Anchor-Chat/AnchorAPI.git
cd  AnchorAPI
npm i && npm test
```

**Comment by lukas2005** [comment]
Looks like this only occurs when the database exists

**Comment by haadcode** [comment]
@lukas2005 thanks for opening the issue! 👍 

When `ipfs.object.get` call "hangs", it usually means that the data (for the requested hash) is not available in the network, ie. there's no peer online that has the hash. So it sounds to me it's a connection issue between the peers. You can try to verify that the peers are connected, before making the database query, with `ipfs.swarm.peers()` which gives you the list of connected peers. You should see the other peer's ID on that list.

**Comment by lukas2005** [comment]
Thanks :) Is there any way to check if a certain database exists/is accessible? Because what I'm trying to do is if db exists connect to it else create it

**Comment by lukas2005** [comment]
to

**Comment by haadcode** [comment]
> Is there any way to check if a certain database exists/is accessible? Because what I'm trying to do is if db exists connect to it else create it

@lukas2005 iirc, you can use `orbitdb.open(name/address, { create: true, ... })` to achieve ^. Hope that helps!

**Comment by lukas2005** [comment]
thanks :+1:
