### ISSUE TITLE
db.get() is undefined even though the db loads and the expected files are there

### ISSUE THREAD

**Issue by jehunter5811** [orbitdb/orbit-db#470]
I've added an object using keyvalue like this: 

```db.put('documents', object);```

When I load my db it loads as expected and properly replicates across peers. I know this because if I console.log ```db``` I can drill down to db._index._index and see the object I stored. I can also call ```db.all()``` and get the same result. 

However, when I call ```db.get('documents')```, I get undefined. Any ideas why that might be? 

Here's my code that uses ```db.get()```: 

```
ipfs.on('ready', async () => {
    const orbitdb = new OrbitDB(ipfs)
    db = await orbitdb.open(address, {
      sync: true,
      create: true,
      overwrite: true,
      localOnly: false,
      type: 'keyvalue',
      write: ['*']
    });

    db.load();
    await db.load(db, 'Loading database...')
    .then(() => {
      console.log(db.get('documents')); //this === undefined
    });
  })
}
```

**Comment by lukas2005** [comment]
uhh `db.load` only takes a single optional argument: https://github.com/orbitdb/orbit-db/blob/master/API.md#storeloadamount

So your code should look like this:
```js
ipfs.on('ready', async () => {
    const orbitdb = new OrbitDB(ipfs)
    let db = await orbitdb.open(address, {
      sync: true,
      create: true,
      overwrite: true,
      localOnly: false,
      type: 'keyvalue',
      write: ['*']
    });

    db.load()
    .then(() => {
      console.log(db.get('documents')); //this === undefined
    });
  })
}
```
Also when you `await ...` don't expect to get a promise

**Comment by jehunter5811** [comment]
Once again, you're a huge help @lukas2005! Not sure where I even got the idea that the second parameter should be in there. It's working as expected now!
