### ISSUE TITLE
Sync db between multiple peers in a network

### ISSUE THREAD

**Issue by subhasisbanik** [orbitdb/orbit-db#471]
I have used orbitdb js to create a db and retrieve the data back for a single peer with both IPFS daemon as well as ipfs-js.
Now in a truly decentralized environment, what I plan to do is to create cluster of IPFS peers with orbitdb running on top of it. 
I have clustered ipfs with ipfs-cluster-service and ipfs-cluster-ctl but it seems it has no way I am able to insert data from 1 orbitdb peer and get it back from another peer.
I have made another setup which peers ipfs daemon with "ipfs swarm peers" but still it isn't serving the thing I want, connecting orbitdb to add and get it back in a network).
Maybe adding this as an issue would be wrong because maybe orbitdb isn't designed that way, but I believe there should be atleast 1 solution to this problem.
Please help!!

**Comment by ryancbarry** [comment]
> it seems it has no way I am able to insert data from 1 orbitdb peer and get it back from another peer

Looks like I'm running into this too. I added data to a key-value store, then tried to retrieve that data using a different peer, but just got `undefined`. Is this kind of thing not supported? Or is there a way to do this?

**Comment by aphelionz** [comment]
Hi @ryancbarry and @subhasisbanik.

In order for the peers to replicate databases two underlying IPFS links need to be in place:

1. The peers must be connected direclty via an `ipfs.swarm.peers` call. `js-ipfs` has made a TON of headway on this but for now it's still best to explicitly connect.
2. Once connected, the peers must be able to `pubsub` with each other.

Also, I wanted to let you know about the [OrbitDB Field Manual](https://github.com/orbitdb/field-manual) which aims to answer all of these questions via a tutorial and other sections. Feel free to open issues or PRs there if something doesnt make sense or if you have more questions.
