### ISSUE TITLE
Replicating a database without write access

### ISSUE THREAD

**Issue by theoturner** [orbitdb/orbit-db#475]
I have computer A where I create an OrbitDB database and computer B where I want to replicate the database. I want B to be able to read the database but not write to it.

If, on creating the database, I set the option `write: ['*']`, the database replicates with all contents on computer B. If I remove this option (i.e. database is read-only), computer B receives an empty object `[]`.

Selective read access is still in development, however it is implied in various issues that read-only access is possible. How is this done?

**Comment by haadcode** [comment]
Thanks for the question @theoturner!

When leaving out the `write` option from the database creation, OrbitDB will default to adding the creator of the database as the only one with write access.

Read-only access means that ^. When the `write` access is defined, it'll only allow peers/nodes with the defined keys to write (=update) the database while allowing others to only read it. OrbitDB currently doesn't implement "selective read-access" and this needs to be done on app-level. I believe [3box](https://github.com/uport-project/3box) is implementing something akin to "selective read access", so you might find more information and ideas there.

**So to answer the question:** database replication works without defining `write` access in any special way and you should see the same database results on both computers. 

If it doesn't, as it seems, then it'd be helpful if you can share the code you're using to produce the erroneous behaviour (as you describe above), perhaps there's something there that's causing it.

**Comment by theoturner** [comment]
Fixed by putting the second machine's read in a `db.events.on('replicated', (address) => { ... }` block.
