### ISSUE TITLE
How does querying work?

### ISSUE THREAD

**Issue by rbaid1221** [orbitdb/orbit-db#477]
From what I'm seeing about querying in the code, we literally pull all the content from our IPFS root database node, load it into a local data structure, and then query the plain-text content..

We were looking to encrypt all of our data before we stored it, so in this case indexing and querying would not work, correct?

**Comment by lukas2005** [comment]
? All you need to do is encrypt your data and put it into the database. Knowing which one you are planning to use and if you want everything (in case of a KVStore both keys and values) or just the data encrypted

**Comment by RichardLitt** [comment]
Yes, indexing and querying won't work on encrypted data. :)

**Comment by bugeats** [comment]
Can’t you just encrypt the values and not the keys?
