### ISSUE TITLE
How can use the hash returned by `put` method

### ISSUE THREAD

**Issue by marciok** [orbitdb/orbit-db#480]
At the documentation there's the following: 
```
const hash = await db.put({ _id: 'QmAwesomeIpfsHash', name: 'shamb0t', followers: 500 })
```
So a hash is returned when I insert a new document, let's say if I want to find the inserted documented by its hash how could I do it? When I try to find it using cat nothing is returned. 

I want that to store that hash on ethereum and be able to access it  

Thanks is advance.

**Comment by lukas2005** [comment]
`db.get()` takes in a hash

**Comment by DanielVF** [comment]
That hash is the IPFS address of that update (called an entry Entry). It contains pointers from that update to all previous Entries that your instance of this OrbitDB database knows about.

Orbit DB stores each Entry in an IPFS `object`. This is a lower level than the usual IPFS commands operate at. To read it, you'll want to do an `ipfs object get YOURHASH`, then get the data field and parse it as json.

**Comment by aphelionz** [comment]
We cover this pretty extensively now in the new [OrbitDB Field Manual](https://github.com/orbitdb/field-manual). Check out the Tutorial section, particularly Chapter 2 which covers reading and writing data.
