### ISSUE TITLE
What can I do with the hash returned by `put`

### ISSUE THREAD

**Issue by marciok** [orbitdb/orbit-db#481]
At the documentation there's the following: 
```
const hash = await db.put({ _id: 'QmAwesomeIpfsHash', name: 'shamb0t', followers: 500 })
```
So a hash is returned when I insert a new document, let's say if I want to find the inserted documented by its hash how could I do it? When I try to find it using cat nothing is returned. 

I want that to store that hash on ethereum and be able to access it  

Thanks is advance.

**Comment by aphelionz** [comment]
Hi @marciok. I'm not sure of the timing, but we'v e recently switched to IPLD so if you try the `ipfs.dag.get` command, you might have better luck.

**Comment by marciok** [comment]
@aphelionz Thanks for the reply, I'll try later..

Best
