### ISSUE TITLE
error while npm install

### ISSUE THREAD

**Issue by mccoysc** [orbitdb/orbit-db#483]
when install the code from the downloaded zip file got the following error:
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE checkout feat/acl-refactor
npm ERR! error: pathspec 'feat/acl-refactor' did not match any file(s) known to git.

**Comment by RichardLitt** [comment]
I'm sorry. We currently don't support Windows. Try on a Unix box? :)
