### ISSUE TITLE
OrbitDB documentation should have more information / links to underlying concepts

### ISSUE THREAD

**Issue by sirfumblestone** [orbitdb/orbit-db#492]
Today OrbitDB documentation assumes that the reader has sufficient knowledge about e.g. p2p paradigm and CRDTs to start with. I think it would be beneficial to provide a beginner guide that would offer somewhat structured advise how to get familiar with the concepts behind OrbitDB. I believe this would help new users to gain better understanding of OrbitDB 🙂

**Comment by aphelionz** [comment]
Resolved via the [Field Manual](https://github.com/orbitdb/field-manual)
