### ISSUE TITLE
Store data in IPLD compatible way?

### ISSUE THREAD

**Issue by singpolyma** [orbitdb/orbit-db#501]
`ipfs dag get <DB-HASH>` right now gives:

    { "data": "<BASE64 ENCODED JSON>", "links": [] }

Why not store that JSON as IPLD-CBOR so that the data can be traversed using `ipfs dag ...` commands more naturally?

**Comment by aphelionz** [comment]
@singpolyma I believe this has been addressed at the `ipfs-log` layer.

**Comment by aphelionz** [comment]
Correction! This was resolved in https://github.com/orbitdb/orbit-db-io/
