### ISSUE TITLE
Far more next pointers than expected.

### ISSUE THREAD

**Issue by DanielVF** [orbitdb/orbit-db#518]
I have several instances of orbit DB, connected through ipfs-api to a local Go IPFS server. Each orbit DB instance is using their own filesystem store in a different directory.

I'm seeing that, outside of bringing up a completely new node, all new head entries are pointing not only to their predecessor head, but also to almost every other previous head:

![image](https://user-images.githubusercontent.com/837/49394905-125f5400-f703-11e8-9fe8-24c8078edbc4.png)

Is this the expected behavior? I would have expected a more linear chain, with more like two or three  "nexts" per entry (because I'm writing before the remote sync is finished).

Each instance is running the code below, and I stop and start an instance to add a write.

```javascript
const IpfsApi = require('ipfs-api')
const OrbitDB = require('orbit-db')

const ipfs = IpfsApi('localhost', '5001')
const orbitdb = new OrbitDB(ipfs)

async function run(){
    const db = await orbitdb.open('/orbitdb/HASHOFMYDB/test-db')
    await db.load()

    const result = db.iterator({ limit: -1 }).collect()
    console.log(JSON.stringify(result, null, 2))

    db.events.on('replicated', (address) => {
        console.log("REPLICATED")
        console.log(db.iterator({ limit: -1 }).collect())
    })
}

run()
```

**Comment by haadcode** [comment]
How many heads to reference in an Entry in [ipfs-log is customizable by the user](https://github.com/orbitdb/ipfs-log/blob/master/src/log.js#L213). [We use 64 references by default](https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L20) in OrbitDB although this can be customizable by the user by passing in `referenceCount` value when creating a database.

The more references helps to parallelize the replication, but comes with the cost of using more data per entry. One or few references means small size but loading happens more sequentially.

**Comment by DanielVF** [comment]
Thanks!
