### ISSUE TITLE
Does Orbit DB create roughly N² rooms for N IPFS peers on the same database?  

### ISSUE THREAD

**Issue by DanielVF** [orbitdb/orbit-db#520]
It appears that whenever a new IPFS peer joins a database, a separate IPFS PubSub subscription is created between them. Thus, if we have four peers, and one new peer joins, four new subscriptions are created. The total number of subscriptions is then (number of peers) * (number of peers - 1).

In looking at the code that is run when a peer connects:
https://github.com/orbitdb/orbit-db/blob/master/src/OrbitDB.js#L173-L205
and
https://github.com/orbitdb/orbit-db/blob/master/src/exchange-heads.js#L21

I tested this locally and it seems to be the case. When I'm running paired OrbitDB instances and IPFS instances, and I list active IPFS PubSub subscriptions on one of those IPFS peers, I see a subscription for the pairs of that peer and each other peer. For example, if I'm on PeerA, and have four other database peers online, I'll see subscriptions to rooms:

    DBAddress
    /.../PeerA/PeerB
    /.../PeerA/PeerC
    /.../PeerA/PeerD
    /.../PeerA/PeerE

Peer B will have subscriptions to

    DBAddress
    /.../PeerA/PeerB
    /.../PeerB/PeerC
    /.../PeerB/PeerD
    /.../PeerB/PeerE

Etc.

Is this correct?

This seems to be a concerning scaling limit. 

I've heard IPFS PubSub has issues with too many rooms. N² subscription growth would seem to put a pretty strong limit on how many peers could be online at one time. If I have a 10,000 users online at the same time, that's 99,990,000 IPFS PubSub rooms, which, I'm guessing would have IPFS PubSub broken a long time before that point.

All the rooms won't exist on every IPFS node, but I'm thinking that "hub" IPFS nodes or IPFS bootstrap nodes could get a lot.

Sample code below, just change ports and run from a a different directory each time you launch:

```javascript
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  },
  config: {
    Addresses: {
        Swarm: [
          '/ip4/0.0.0.0/tcp/4062',
          '/ip4/127.0.0.1/tcp/4063/ws'
        ],
        API: '/ip4/127.0.0.1/tcp/5062',
        Gateway: '/ip4/127.0.0.1/tcp/9160'
      },      
  },
  repo: '.'
}

// Create IPFS instance
const ipfs = new IPFS(ipfsOptions)

ipfs.on('error', (e) => console.error(e))
ipfs.on('ready', async () => {
  const orbitdb = new OrbitDB(ipfs)

  // Create / Open a database
  const db = await orbitdb.log('DBNAME')
  await db.load()

  // Listen for updates from peers
  db.events.on('replicated', (address) => {
    console.log("replicated")
  })

  // Add an entry
  const hash = await db.add('world')
  console.log(hash)

})

// Show this peer's active subscriptions
setInterval(async () => {
    console.log("-----")
    console.log(await ipfs.pubsub.ls())
}, 2000);
```

**Comment by haadcode** [comment]
Short answer: **no**.

For exchanging the heads upon connecting, there's a 1-to-1 connection between each peer across all databases, so each peer only has one subscription to every other peer. There's also only one connection between peers on libp2p level.

> The total number of subscriptions is then (number of peers) * (number of peers - 1).

The total number of subscriptions per peer is `1 * number of peers`.

**Comment by DanielVF** [comment]
Each peer has N subscriptions, but the total number of distinct rooms used across all the connected database instances is roughy N², right?

And something like the IPFS pubsub bootstrap nodes would we see all of these if the local IPFS PubSub node is in its default config?
