### ISSUE TITLE
Add compatibility for the new js-ipfs-http-client and update the doc.

### ISSUE THREAD

**Issue by hushino** [orbitdb/orbit-db#523]
When the next npm command is executed: npm install orbit-db ipfs
only orbit-d ends and ipfs is deprecated and throws error.

**Comment by aphelionz** [comment]
Hi @hushino thanks for the report. Can you help me replicate it? I tried this with the following node and npm versions and it seemed to work  ok for me:

```
+ ipfs@0.33.1
+ orbit-db@0.19.9
added 856 packages from 549 contributors and audited 15447 packages in 55.546s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

$ node -v
v10.13.0

$ npm -v
6.5.0
```

**Comment by hushino** [comment]
it was just an error with node-gyp, solved.
`
$ node -v
v10.14.2

$ npm -v
6.5.0
`

**Comment by aphelionz** [comment]
Great! Thanks for updating us.
