### ISSUE TITLE
Preparing for 0.20.0 release

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit-db#524]
This is an issue to track progress and todos on our way to release the next version.

0.20.0 will be a big update bringing in the new access control system and many many others updates and ***some APIs will break*** (so, heads up).

**Comment by haadcode** [comment]
Currently merging all the dependency PRs to land the [New Access Controller system PR](https://github.com/orbitdb/orbit-db/pull/495). We plan to merge the deps into their respective master today, test it over the weekend and early next week, add missing pieces and fix rough edges and then merge it to master here.

**Comment by aphelionz** [comment]
Closing this as we're now preparing for 0.22
