### ISSUE TITLE
Add non-technical description of OrbitDB

### ISSUE THREAD

**Issue by sirfumblestone** [orbitdb/orbit-db#527]
It would be great to see also a non-technical description of OrbitDB (e.g. key features and capabilities). At the moment they might not be that evident if you are not experience developer and familiar with database models/types. I believe this kind of information would serve well people who are not so much (at least not yet) into database internals but are on quest of finding new tech 🖖

**Comment by sirfumblestone** [comment]
Would it make sense to add a bit more verbose description to [README](https://github.com/orbitdb/orbit-db/blob/master/README.md)?

**Comment by RichardLitt** [comment]
I think that this could go in a Background section above the Usage section. But I'm not sure that this needs to be expounded upon in great depth in this repository, in general. I think it might belong in a blog post or in a tutorial, rather, or on an orbitdb-related website.

**Comment by aphelionz** [comment]
Resolved via the [Field Manual](https://github.com/orbitdb/field-manual/blob/master/00_Introduction/02_What_is_OrbitDB.md). Feel free to open any tickets there in case that section is unclear
