### ISSUE TITLE
Live demo 1 is not working

### ISSUE THREAD

**Issue by LastExile16** [orbitdb/orbit-db#535]
live demo 1 shows `websocket error`
in console it shows the following error using google chrome:
```
WebSocket connection to 'wss://ws-star.discovery.libp2p.io/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
and this error message using firefox:
```
Firefox can’t establish a connection to the server at wss://ws-star.discovery.libp2p.io/socket.io/?EIO=3&transport=websocket.
Transport.prototype.onError@https://ipfs.io/ipfs/QmeESXh9wPib8Xz7hdRzHuYLDuEUgkYTSuujZ2phQfvznQ/bundle.js:1:690938
WS.prototype.addEventListeners/this.ws.onerror@https://ipfs.io/ipfs/QmeESXh9wPib8Xz7hdRzHuYLDuEUgkYTSuujZ2phQfvznQ/bundle.js:1:1857862
```

**Comment by aphelionz** [comment]
I can reproduce this.

Unfortunately, the OrbitDB team does not control `wss://ws-star.discovery.libp2p.io/`. I will look at swapping in another star server. @haadcode where is the code for Live Demo 1?

**Comment by haadcode** [comment]
@aphelionz the source for Live Demo 1 is https://github.com/orbitdb/orbit-db/tree/master/examples/browser.

I believe we haven't updated the deployed version in a long time (thus the error). "Deploying it" means putting the example folder on IPFS and pinning it on the gateways (which can be done through eg. https://twitter.com/ipfspin), and updating the address (hash) in the README.
