### ISSUE TITLE
Does it supports database sharding?

### ISSUE THREAD

**Issue by DaniellMesquita** [orbitdb/orbit-db#536]

**Comment by aphelionz** [comment]
Might you be able to elaborate on your question? As it stands it could be interpreted a few ways, from "Please explain OrbitDB's perspective on and behavior around sharding," to "How can I shard my database in OrbitDB?"

What are you working on, and how can we help? :)

**Comment by DaniellMesquita** [comment]
Does it supports the database sharded between peers (like PHP sites and their databases does), without the need for seeding a whole database?

**Comment by DaniellMesquita** [comment]
And does it uses SQL?

**Comment by DaniellMesquita** [comment]
@aphelionz

**Comment by RichardLitt** [comment]
@DaniellMesquita 	At the moment, I don't think that it supports sharding in that way. It certainly doesn't use SQL. I encourage you to check out the [Field Manual](https://github.com/orbitdb/field-manual), which may help with your questions.
