### ISSUE TITLE
preparations for js-ipfs 0.34.0

### ISSUE THREAD

**Issue by alanshaw** [orbitdb/orbit-db#543]
👋 I upgraded `ipfs` to `0.34.0-rc.1`, `datastore-level` to `^0.10.0`, `ipfs-repo` to `~0.26.1` and ran the tests but there were many failures 😞.

There have been breaking changes to the Object API which I believe to be the cause of the failures. You can read the release notes here: https://github.com/ipfs/js-ipfs/issues/1721

**Comment by aphelionz** [comment]
Yes, we recently migrated `ipfs-log` to use IPLD links and `ipfs.dag.get` instead of `object.get`. This is, in part,  why I think those tests passed and these are failing.

**Comment by maht0rz** [comment]
ipfs@0.34.0 also breaks the current getting started guide, as `npm install orbit-db ipfs` already installs the latest version (0.34.0) which doesnt work with orbit-db

**Comment by vasa-develop** [comment]
cool, it works!
Closing the issue.

**Comment by AlbertoElias** [comment]
Hey, what's the roadmap for this? 0.35 is also coming soon, already in a prerelease and both 0.34 and 0.35 have critical features. Thanks!

**Comment by aphelionz** [comment]
0.36 is supported in the stable 0.21.4 version and we're now working on supporting 0.38
