### ISSUE TITLE
Crash after restart 

### ISSUE THREAD

**Issue by mmsqe** [orbitdb/orbit-db#548]
Steps to reproduce:

1. Run the following code, successful put into OrbitDB
2. Re-run the code
3. App crashes without error

```
let items = Array(10).fill('QmYjvgGiiQb88HbgAp9ba3tPX9eikCDHQzJP7negnyv72F');
await Promise.all((items).map(async (data, i) => {
  //db is an OrbitDB instance
  await db.put({
    id: `id_${i}`,
    data: data
  });
  console.log('success put: ', i);
}));
```

**Comment by mmsqe** [comment]
This issue has been fixed after updating docker container from `node:8-alpine` to `node:8`, app won't crash after re-run

**Comment by RichardLitt** [comment]
@mmsqe Ahhh. Glad you got this fixed. I spent some time last night trying to replicate, but ran into my own issues. Thanks for following up and closing this.
