### ISSUE TITLE
Issue with ipfs daemon code example

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbit-db#549]
```js
const db = await orbitdb.log('hello')
```

I'm getting a linting error that you can't use await like this, outside of an async function. Should we remove it from the example?

**Comment by BartKnucle** [comment]
Can you link where you get the code sample please?

**Comment by RichardLitt** [comment]
@BartKnucle This is from the README, [here](https://github.com/orbitdb/orbit-db#module-with-ipfs-daemon).

**Comment by aphelionz** [comment]
I think we need to either assume that people will understand that it needs to be wrapped in an `async` function, or wrap the examples in an async IIFE like so:

```javascript
(async () => {
  const db = await orbitdb.log('hello')
})()
```

**Comment by RichardLitt** [comment]
Can we just add a note that it needs to be wrapped in an async? I think the IIFE might introduce more confusions than not. But this might just be _me_ being confused, so I'm not sure it's necessary to change anything.

**Comment by aphelionz** [comment]
Yeah, a note should be fine
