### ISSUE TITLE
repo folder keeps getting locked

### ISSUE THREAD

**Issue by Jonsey** [orbitdb/orbit-db#557]
Getting this error on the second attempt to access orbit db

{ Error: Lock file is already being hold
    at options.fs.stat (/home/user/projects/app/server/node_modules/proper-lockfile/lib/lockfile.js:54:47)
    at /home/user/projects/app/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
  code: 'ELOCKED',
  file: '/home/user/projects/app/server/orbitdb' }

**Comment by BartKnucle** [comment]
Can you share your code?

**Comment by Jonsey** [comment]
It was my own fault I was creating multiple OrbitDb instances with the same IPFS config options.  My bad.
