### ISSUE TITLE
429 (Too Many Requests) browser example errors in console

### ISSUE THREAD

**Issue by huhsame** [orbitdb/orbit-db#560]
I install orbit-db repository and run.
example works on browser but there are lots of errors in console.

**GET** https://node0.preload.ipfs.io/api/v0/refs?r=true&arg=Qmb3vcXiX6dBHjWojh817SoVUdBmxiycrPs23ySeMRHT5v **429 (Too Many Requests)**

This message is repeated with different hash. 
here are captures.

![image](https://user-images.githubusercontent.com/9151382/52402720-59553580-2b08-11e9-9f22-b14012b74545.png)
![image](https://user-images.githubusercontent.com/9151382/52402770-768a0400-2b08-11e9-9266-3f8ed0726afd.png)

package version 
"go-ipfs-dep": "0.4.18",
 "ipfs": "~0.33.0",

and node 10
mac

**Comment by aphelionz** [comment]
@huhsame Try this.

When instantiating IPFS use: 

```javascript
this.ipfs = new Ipfs({
  preload: { enabled: false },
  ....
}
```

**Comment by RichardLitt** [comment]
@aphelionz What does preload do?

**Comment by huhsame** [comment]
https://github.com/ipfs/js-ipfs#optionspreload

**Comment by haadcode** [comment]
This would be great candidate for FAQ
