### ISSUE TITLE
Making a database to which anyone can add new entries, but only edit or delete their own content

### ISSUE THREAD

**Issue by MirceaKitsune** [orbitdb/orbit-db#567]
I'm still circling around my idea of creating a social media or art gallery site using nothing but IPFS and OrbitDB. Orbit's current rigidity on permissions makes this very difficult: It's not easy to find any reasonable format when a database can be either written to by everyone or only written to by the owner, as you need write access to let your users use the site but giving it to everyone means any troll can freely edit or delete the entire database.

I wanted to ask about a compromise idea: Would it be possible to create a database in which anyone can create new entries, but users may only delete their own entries? I'm particularly thinking of [docstore](https://github.com/orbitdb/orbit-db-docstore) here, since I remember it's the only one that supports indexing which is needed for large sites.

For example: User A creates a database. They then post a new object to it, followed by users B and C. Since user A owns the database, they can delete both their post and those of B and C... however user B can only delete their own entries without touching those of A or C, whereas C can only delete theirs without any editing rights over those of A and B.

**Comment by aphelionz** [comment]
Thanks for the question!

I might suggest the followinh approach using nested database address:

1. Create a master database that anybody can write to and add entries. Validate this data carefully, but in the end allow any valid entries. Let's make this a `docstore`, indexed by the public keys of the users connecting to it.
2. When each entry is created, create a new `keyvalue` database with **per user** ACL and store the address of this new database back in the global `docstore`. This database would be where the true user data lives. This could be any type, I just picked `keyvalue` at random

Nesting the databases in this way allows you to maintain a global index of all your users and allow anybody to join in freely, but then constrain them inside their own databases via ACL.

**Comment by MirceaKitsune** [comment]
I've thought about using a database of databases, but that approach seems complicated too. The main issue is that, the master database pointing to the sub-databases needs to be writable to by anyone so that the list can be updated, but this again has the issue that anybody can edit or delete its entries. This is at least true for docstore, which is required for indexing and good performance.

**Comment by mistakia** [comment]
One workaround to that issue is to only validate edits made by the same key used to make the original entry and ignore any delete operations. This would require a [custom store approach](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#custom-stores).

**Comment by tabcat** [comment]
> 1. Create a master database that anybody can write to and add entries. Validate this data carefully, but in the end allow any valid entries. Let's make this a `docstore`, indexed by the public keys of the users connecting to it.

could you have the docstore indexed by public keys only allow entries on an index that are signed by the person with the matching public key?

**Comment by MirceaKitsune** [comment]
The problem with docstore is that you can only set it up in one of two ways: Either only the owner can make changes but everyone else can read it, either everyone can make changes as well as read it. In the first case, the system is unworkable for users because the database owner needs to manually approve every change thus each user must go through them which is absurd. In the second case, the system works for everyone but any troll with a script can wipe out the database and even worse edit other people's posts and even impersonate them. There's just no in-between way.

If no solution is found I'm thinking of going with a recommendation system: Every user has their own database which only they can edit, from which they may watch other users... the users they watch will then display in their feed, which others can use as its own website. It's the only system that feels reliable at the moment, as I don't see how a common indexing or search system is possible.

**Comment by aphelionz** [comment]
Great to see the discussion, and also great to see the discussion leading to viable ideas

**Comment by MirceaKitsune** [comment]
Right now I'm pondering the following solution: Every profile (device) will use a `docstore` type database, which only the owner can edit and contains both user settings as well as posts. After that there will be a site-wide `eventstore` database, to which every active user announces their profile's database whenever they load the page: This can be used to get a list of profiles for searches.

`eventstore` is append-only, so letting everyone write to it is safe. The only way to vandalize that is if an attacker makes a script spamming it constantly and filling it up with junk, as there will have to be a limitation in # of latest entries read per search (eg: 1000 (last active users)) to avoid large sites requiring 10's of MB's to be downloaded each time. I'm not sure how this final risk can be easily prevented.

**Comment by aphelionz** [comment]
So far so good. How would you differentiate the user settings from the posts in the docstore db?

**Comment by MirceaKitsune** [comment]
I can't easily think of a way, but that is solvable: I definitely want only one database per user, where every post as well as activity is one object. I'll want to index posts by tag, so if I have "foo bar" I can get the results by either "foo" or "bar". I'll probably have a special type field which indicates what the object represents (a post, a profile update, a follow request, etc).

**Comment by aphelionz** [comment]
@MirceaKitsune What did you end up going with? :)

**Comment by MirceaKitsune** [comment]
I'm not at programming the platform yet, might be months or later. Still need to think about the details, but I'll likely use two databases: DocStore for the profile, append-only Feed to help profiles communicate with one another (for search, notifications, etc).

**Comment by aphelionz** [comment]
That sounds good - feel free to re-open this issue or create a new one if you have more questions. Definitely stop back to show us what you made!
