### ISSUE TITLE
Replication issue

### ISSUE THREAD

**Issue by codeforgeek** [orbitdb/orbit-db#575]
When I add something from machine A where IPFS is running , it gets replicated to machine B where i i am running the code and opening database using address.

When I add something from Machine B, it does't get replicated in machine A unless I restart the code. Restarting the code on machine A makes the replication works.

Anything I am missing here?

**Comment by BartKnucle** [comment]
Hi! Can you post your code please?

**Comment by codeforgeek** [comment]
Sure.

Code running on Machine A:

```
const IPFS = require('ipfs-api');
const OrbitDB = require('orbit-db');
const uuid = require('uuid/v4');
const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  }
};

// Create IPFS instance
const ipfs = new IPFS('localhost','5001');
const orbitdb = new OrbitDB(ipfs);
let db = null; 
async function loadDB() {
	db = await orbitdb.docs('todo');
	// load the local store of the data
	db.events.on('ready', () => {
		console.log('database is ready.')
	});
	db.load();
}
loadDB();
```

Code running on Machine B:
```
const IPFS = require('ipfs-api');
const OrbitDB = require('orbit-db');
const uuid = require('uuid/v4');
const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  },
  host: '172.16.28.148',
  port: '5001'
};

// Create IPFS instance
const ipfs = new IPFS(ipfsOptions);
//const ipfs = new IPFS('localhost','5001');
const orbitdb = new OrbitDB(ipfs);
let db = null;
async function loadDB() {
        db = await orbitdb.open('/orbitdb/QmQvUq6dZa1gR9KZn18diAsnSD6C4xsvdkbZvmq8MeL7rG/todo2');
        // load the local store of the data
        db.events.on('ready', () => {
                console.log('database is ready.')
        });
        db.load();
}
loadDB();
```
I am running IPFS peer on machine A. When I add something in database from Machine A, its gets replicated to Machine B in fraction of second. Code to add is:
```
     let id = uuid();
     let hash = await db.put({_id: id, text: data, status: 'PENDING'});
     let todoData = db.get(id);
```
But when I add something from Machine B, it doesnt get replicated in Machine A but when I restart the code on Machine A it replicate the changes from Machine B.

**Comment by BartKnucle** [comment]
Do you have an error message from orbitdb?
If you are on node, add: "set LOG=debug" before the exec command.
In the browser: "window.LOG = 'Verbose'" in your html code.

**Comment by BartKnucle** [comment]
Maybe you can also add the replication event to check if the replication process trigger on both sides.

**Comment by codeforgeek** [comment]
I don't have any error messages. 

And I have exposed it as a REST API and calling that from UI. So not sure about window.log.

And replication part, I will add the listener and come back to you. Also, have you done this before i mean syncing the same database in multiple machines?

**Comment by BartKnucle** [comment]
Yes but I created an ipfs node for each machine. And since orbitdb use pubsub to sync the databases I don't know how it handle the sync on the same node.
I also do not use ipfs-api library but a js-ipfs instance inside the browser... Very different setup.
I had also problems to sync under windows that I've solved since. Logs may help.

**Comment by aphelionz** [comment]
IPFS pubsub is pretty intermittent in the browser. I admit I haven't done a lot to drill down into the internals of what's going on but I know that using these settings in your IPFS instantiation is helpful:

```javascript
let node = new IPFS({
  relay: { enabled: true, hop: { enabled: true, active: true } }
  /* opther options, etc... */
})
```

**Comment by codeforgeek** [comment]
@aphelionz Added the above code too and ran local instance of IPFS in each node. Still the same. When I add something in Machine A, Machine B replicate but not vice versa unless I restart the code in machine A.

**Comment by codeforgeek** [comment]
Is there any way we can manually fire the replicate event in the code?

**Comment by BartKnucle** [comment]
You really should try to enable debugging on your 2 machines and give us logs. It will be very helpfull since the replications problems are hard to solve given all the different possible setups.

**Comment by codeforgeek** [comment]
How do I enable the logging?

**Comment by BartKnucle** [comment]
If you are on node, add: "set LOG=debug" before the exec command.
In the browser: "window.LOG = 'Verbose'" in your javascript code.

**Comment by codeforgeek** [comment]
Thanks so much for your help and really sorry for wasting your time guys. It was a stupid mistake, in Machine A i was reopening the database again, i commented that is working like charm.

Thanks again for your help :)

**Comment by BartKnucle** [comment]
You are welcome :)
