### ISSUE TITLE
I cant able to create write access with public 

### ISSUE THREAD

**Issue by kesavananbu** [orbitdb/orbit-db#578]
const access = {
 write : ['*'],
}
const db = await orbitNode._orbitdb.keyvalue('UsersCredentials',access)

Is the Structure correct ?

I Could not able to able to add entry to this. This Another peer which using  Address of the db above created.
Could not append entry, key "04d29d042e28b3ab201eb453486ca280dd80a157b806e5826a15d71fe3147b1fba059399d2c6e339c646afcfea42fd81a18fa73231bd6ecc8e75cd4947ead8b897" is not allowed to write to the log

**Comment by aphelionz** [comment]
Ah, you need to wrap that in an `accessController` key:

```
{
  accessController: {
    write: ['*'] // Allow anyone to write to the channel
  }
}
```
