### ISSUE TITLE
Knowing who added what

### ISSUE THREAD

**Issue by Hazae41** [orbitdb/orbit-db#582]
Hello, is there a way to know which PeerID added a given entry to the database?

**Comment by aphelionz** [comment]
@Hazae41 Great question, and the answer is "yes, there is."

Assuming you have an OrbitDB at `db`, `db._oplog` will give you the list of entries in a [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) format. Then, each entry will have an `identity` with the IPFS node ID, the publicKey, and a signature.

**Comment by Hazae41** [comment]
Great! Thanks!

**Comment by Hazae41** [comment]
Hello, there never seems to be an `identity` in any of the values of `db._oplog.value`
![](https://i.imgur.com/ccPI9N7.png)
Using orbit-db 0.19.9

**Comment by aphelionz** [comment]
Hmm, ok, I guess it depends on what you're passing as an Identity manager, but you can still get the same info from the `clock` field

**Comment by Hazae41** [comment]
Okay thanks!
