### ISSUE TITLE
API documentation for write is incorrect

### ISSUE THREAD

**Issue by oed** [orbitdb/orbit-db#584]
The [docs](https://github.com/orbitdb/orbit-db/blob/master/API.md#write) says that the params for the `write` event are `(dbname, hash, entry)`, but in the [code](https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L423) they are `this.address.toString(), entry, this._oplog.heads`.

Nothing urgent, just a heads up 🙂

**Comment by shamb0t** [comment]
Thanks @oed! Fixed in #746
