### ISSUE TITLE
OrbitDB Roadmap

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbit-db#585]
## OrbitDB Roadmap

Over the past few months, the OrbitDB core team has been working hard. This is a basic summary of what we've done and where we're going.

Our major work, the [Access Controller](https://github.com/orbitdb/orbit-db-access-controllers), is probably the biggest feature to be released since OrbitDB was created.

The AC release is almost ready. We've had to do a lot of refactoring, and add support for backwards compatibility, to ensure that no one gets left behind. (Still, after the release, we need to prepare to support users, fix bugs, and so on, of course.)

From the community, the biggest feature requests we've heard are ACL, log traversal, and loading semantics. Most of the other requests have been "will this work with X" - for instance, getting OrbitDB running on Windows. (Do you have something that isn't listed here? Mention it in the [next OrbitDB call](https://github.com/orbitdb/welcome/issues/53)!, or open an issue.) In order to help triage questions and enable us to focus on working on the hard stuff, @aphelionz has spent the last month working on an OrbitDB guide - still in progress - which will address most of the questions we've seen thus far. We also have the [FAQ](https://github.com/orbitdb/orbit-db/blob/master/FAQ.md), which you're all welcome to contribute to.

## OrbitDB Development Roadmap

_Note: If you have questions or want elaboration, comment below!_

1. ACL Work 0.20.0 release (@shamb0t / @haadcode / @aphelionz) - **This week / next week**
    - Not including key revocation
    - Tests
        - Difference Function Test
        - Reduce Entries after `findHeads`
    - Document release process and intention (when, how often?)
    - Priority: Very High
    - Performance issues / optimizations for opening / closing storage
    - Removing CID field from entry, just using hash
    - https://github.com/orbitdb/orbit-db-io/issues/1
    - Write tests for orbit-db-keystore
    - remove await from tests in orbit-db-access-controllers
    - print actual error and stack trace for validation error in ipfs-log
3. [OrbitDB Guide](https://github.com/orbitdb/field-manual/) (@aphelionz) - **Released!**
4. Optimizations (@shamb0t)
    - Priority: High
    - Keystore IndexedDB open/close
    - Adding references in ipfs-log
    - optimizing stores
    - skip list-ish type of thing / add references / optimized loading
    - kvstore "caching layer" aka "index"
        - Figure out what has already been processed and cache the hash of that
5. Semantics around loading -  "when is db ready?"
6. Property Based Testing
7. Set up Workshops && Meetups && Conferences
8. Add a bot to automatically get npm ownership decentralized
9. Linting
10. Backwards compatibility 1.19.10 release

### If we have the time:

6. Benchmarking
    - We'd love to have help with this! Let us know if you're up for it.
    - Get @mistakia's PR up to date
7. HTTP API
    - Can be worked on in isolation
    - We'd also love to have help with this! Let us know if you're up for it.
8. Key revocation (involved)

## OrbitDB Community

We also have been working on making sure that us, the maintainers, are listening to you, our users and community! Here's a few things we've been doing and will continue to work on over the next few months:

- We're active on [Gitter](https://gitter.im/orbitdb/Lobby), and will endeavor to be as responsive as we can.
- The OrbitDB guide will help with referring people to a document where they can find answers; but we're also committing to pointing people to open issues that deal with their bugs as responsively and helpfully as we can.
- We've removed Waffle.io from across the GitHub organization, as it wasn't something we were actively using.
- We've decided we're probably too small a community presence to really benefit from [GitHub Apps](https://developer.github.com/apps/). That having been said, if you have any apps you think would help us all develop better, get in touch!
- Wrote this Roadmap. :)
- We've now got [an npm policy](https://github.com/orbitdb/welcome/blob/master/npm-policy.md) for how we work with our modules.
- Coming up: Adding a better linter (we've had some issues with standard and multiline commenting, among other things), refactoring the PR template, and trying to get an @orbitdb twitter account.
- We've also kept up the biweekly community calls (see https://github.com/orbitdb/welcome), and will continue to do so. Join us!

**Comment by aphelionz** [comment]
@RichardLitt Should we plan on closing this and creating a new one soon?

**Comment by RichardLitt** [comment]
Aye. Let's put the dates in the title next time.

**Comment by aphelionz** [comment]
Ok, great! I guess leave it up for now until we can replace it for maximum transparency

**Comment by Dracks977** [comment]
hello windows support coming ?

**Comment by RichardLitt** [comment]
Closing in favor of #719.
