### ISSUE TITLE
Ipfs & Orbitdb version compatibility issues with React App

### ISSUE THREAD

**Issue by AqeelKazmi** [orbitdb/orbit-db#591]
Recently i used ipfs@0.33.0 , ipfs-pubsub-room@1.4.1 . orbitdb@0.19.9 packages in nodejs application. It works fine and all packages integrated successfuly and worked perfectly. But due to business logic i need to shift on React, for this i use ipfs@0.33.0 , ipfs-pubsub-room@1.4.1 . orbitdb@0.19.9 versions but ipfs gives error "There is already a transport with this key" ... I tried to resolve but failed. Then i switched to ipfs@0.34.4 (latest) , ipfs-pubsub-room@1.4.1 . orbitdb@0.19.9 versions it resolved "There is already a transport with this key" error but when create orbitdb by using```  let db = await orbitdb.keyvalue("orderbook3", access); ``` it throws error " Arguments to path.join must be strings" .

I think there is only version compatibility issues regarding ipfs and orbitdb. Suggestions are required

**Comment by aphelionz** [comment]
Thanks for opening the issue!

We just released the 0.20.0-rc1 (as yet formally unannounced). Please try `npm install orbit-db@rc1`

**Comment by AqeelKazmi** [comment]
I already tried with this verison 0.20.0-rc1

When i import in React  ```  import {OrbitDB} from 'orbit-db'  ```
it throws error " Unhandled Rejection (TypeError): orbit_db__WEBPACK_IMPORTED_MODULE_8__.OrbitDB is not a constructor "


& when import in React like ```   import OrbitDB from 'orbit-db'    ```
it throws error "Unhandled Rejection (Error): identity is a required argument. See https://github.com/orbitdb/orbit-db/blob/master/API.md#createinstance "

Suggestions required

**Comment by AqeelKazmi** [comment]
ok i just pass another param along with ipfs to create orbitdb instance
```  const orbitdb = new OrbitDB(ipfs, "identity");   ```
& it created databaseString and working good,  but getting error on  ``` db.key.getPublic('hex') ```  " Cannot read property 'getPublic' of undefined  ".

**Comment by haadcode** [comment]
@AqeelKazmi thanks for reporting the issue and providing details. With the 0.20.0-rc1, the API for creating an instance (as well as some others) have changed. Take a look at the updated docs in https://github.com/orbitdb/orbit-db#module-with-ipfs-instance how to create an OrbitDB instance (tldr: instead of using `new OrbitDB()` the instance is created with `OrbitDB.createInstance`).

Hope this helps and you can make progress! If not, let us know! Would also love to hear if you find any other errors, feel free to open new issues or report them here 👍

**Comment by AqeelKazmi** [comment]
@haadcode  thank you very much for response.
By using older version 0.19.9 it returns db.key.getPublic attribute that has public key for newly created db.
But this new version is not returning any db.key attribute. **so how to get public key for db?**

**Comment by haadcode** [comment]
I believe the key is now https://github.com/orbitdb/orbit-db/blob/master/API.md#storeidentity

**Comment by AqeelKazmi** [comment]
By instantiating like this ```   const orbitdb = new OrbitDB(ipfs, "identity");   ```
orbitdb is just running but not accessing many of the things like publickey, comnnected peers list etc.

Therefore i tried to instantiate with the new way given ```    const orbitdb = await OrbitDB.createInstance(ipfs)   ```
But using this way throws error:  "   TypeError: Failed to execute 'digest' on 'SubtleCrypto': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'   "

I googled it but not found more useful solution except something chrome issues i think.
@haadcode  Further guidance is required with bundle of thanks

**Comment by AqeelKazmi** [comment]
@haadcode i go into mutihashing-asyncs/src/crypto-sha1-2-browser.js of node_Modules and ```   const res = webCrypto.digest({ name: type }, data)  ```   before passing this data to  webCrypto.digest i simply typecast it
```    var data = new Uint8Array(data);    
 const res = webCrypto.digest({ name: type }, data)
```

And now successfully creating orbitdb object and returning complete attribute list of publicKey etc.
But still  db.get('peers') is undefined. I will explore further and raise issue if not get solution.

**Comment by aphelionz** [comment]
@AqeelKazmi make sure you're using await / promises when writing data to the database, and then check this FAQ issue for more info.

https://github.com/orbitdb/orbit-db/issues/579

Good luck!
