### ISSUE TITLE
Make open accept identity as an optional parameter

### ISSUE THREAD

**Issue by oed** [orbitdb/orbit-db#598]
Right now I can only open DBs with write permissions that the identity passed to the constructor of OrbitDB. I would like to have an optional identity parameter that can be passed to the `open` function  that makes the [`_createStore`](https://github.com/orbitdb/orbit-db/blob/master/src/OrbitDB.js#L172) use this given identity instead of `this.identity`.

As I understand it there should not be any issue with doing this?

**Comment by shamb0t** [comment]
Closed by #609
