### ISSUE TITLE
OrbitDB.createInstance is not a function

### ISSUE THREAD

**Issue by shaikh-shahid** [orbitdb/orbit-db#599]
I am using the latest ipfs http client and orbit db as shown in example and getting this error when loading the database.

```
OrbitDB.createInstance is not a function
```

**Comment by codeforgeek** [comment]
I have installed the orbitdb using npm i --S orbit-db

**Comment by gil-air-may** [comment]
Having the same problem in a browser application. The browser IPFS node is working correctly.
IFPS -> js/ipfs/ 0.34.4

**Comment by huhsame** [comment]
I got the same error.

**Comment by aphelionz** [comment]
Please try the npm tag `rc2` - the second release candidate was just publushed

`npm i -S orbit-db@rc2`

**Comment by huhsame** [comment]
It still has the same problem with `rc2`. please check.

**Comment by huhsame** [comment]
After trying `rc2`, another error appears. 
[#602] (https://github.com/orbitdb/orbit-db/issues/602
)

**Comment by haadcode** [comment]
@huhsame does `rc2` fix the original error? If so, feel free to close this issue (and re-open it if the problem persists).
