### ISSUE TITLE
Signature validation error orbitdb-0.20.0-rc3

### ISSUE THREAD

**Issue by alexander-lipnitskiy** [orbitdb/orbit-db#604]
jsipfs-0.35.0
orbitdb-0.20.0-rc3
node-v10.15.3

I am using a document store for orbitdb with jsipfs. IPFS node is created programmatically. When I am trying to replicate orbitdb with an object that contains more than two property I get the following error.

`UnhandledPromiseRejectionWarning: Error: Could not validate signature "..." and key "."
    at verify (.../node_modules/ipfs-log/src/log.js:370:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

Example of my object that I want to store in orbitdbt:

`await db.put({ _id: "AirQuality", first: 1,second: 2,third: 3 });`

It looks like when I have an object in orbitdb with more than two fields it is could not be validated successfully.

**Comment by AlbertoElias** [comment]
Noticed this as well. For me it fails when running `await mydb.load()`

@alexander-lipnitskiy does it work fine in rc2?

**Comment by alexander-lipnitskiy** [comment]
> Noticed this as well. For me it fails when running `await mydb.load()`
> 
> @alexander-lipnitskiy does it work fine in rc2?

I didn't try with other versions of orbitdb. I found in an orbit-welcome repository that developers know about this issue. You can read about it there. https://github.com/orbitdb/welcome/commit/29375311e5aa21ca86a9c79af3a05256c08a1ac7

**Comment by AlbertoElias** [comment]
Thanks for that. Hopefully it will be fixed soon.

>

**Comment by shamb0t** [comment]
@AlbertoElias @alexander-lipnitskiy thanks for reporting! Indeed we're working on a fix. Can you confirm if you are getting the issue in `orbit-db@rc4`?

**Comment by alexander-lipnitskiy** [comment]
Of course, I am waiting for a new update.

**Comment by AlbertoElias** [comment]
I'm still getting the error. I tested by deleting all storage and starting
again.

>

**Comment by shamb0t** [comment]
@AlbertoElias do you still face the issue with clean `npm install` with `rm -r node_modules && rm package-lock.json && npm install orbit-db@rc4`?

**Comment by AlbertoElias** [comment]
Yup, you´re right! Now that is working, but I'm bumping into other errors, one of them being #605 and the other I think is specific to IPFS. Thank you!

**Comment by BartKnucle** [comment]
Hello, I still have the problem on the RC6 from npm package.

**Comment by BartKnucle** [comment]
I've gone a bit further. It seems that the JSON.stringify is not deterministic.
When I use a determinisic librairy there is no more errors:

To test the changes mades in toBuffer method in entry.js from the ipfs-log library.

```
static toBuffer (entry) {
  var stringify = require('json-stable-stringify')
  return Buffer.from(stringify(entry))
  //return Buffer.from(JSON.stringify(entry))
}
```

**Comment by BartKnucle** [comment]
Ok, still have some problems with dates field :(

**Comment by BartKnucle** [comment]
Ok, the JSON library use Date.prototype.toISOString It work when formating dates now.

**Comment by haydenyoung** [comment]
Is this still an issue in RC9? I'm running into the same problem. Do I need to delete the store first (I.e. this will not fix an already deployed data store?)
