### ISSUE TITLE
TypeError: this._db.all is not a function in OrbitDBAccessController

### ISSUE THREAD

**Issue by AlbertoElias** [orbitdb/orbit-db#605]
I´m doing a `put` on my document database: `db.put(myObject)`. 

It happens when I add:

```
accessController: {
				type: 'orbitdb',
				write: [orbitdb.identity.publicKey]
			},
```
to the configuration object when instancing the document store.

The error is here: https://github.com/orbitdb/orbit-db-access-controllers/blob/24162d037ea0078b53b985219449c2de3ab6320b/src/orbitdb-access-controller.js#L41 Should I open the issue in that repo?

**Comment by AlbertoElias** [comment]
Tested in rc5

**Comment by shamb0t** [comment]
Thanks for reporting @AlbertoElias! This should be fixed now in `orbit-db@rc6`, does the error still appear for you?

**Comment by AlbertoElias** [comment]
I am now getting:

`Error: Could not append entry, key "0201b42d3c8637d5ecda27703394b41b21424d16887f811f7facc1ae143d81f083" is not allowed to write to the log`

**Comment by shamb0t** [comment]
@AlbertoElias are you having this issue with a new db? The error is thrown when a key tries to add an entry without access. Can you print the output of `db.access._db.get('write')`?

**Comment by RichardLitt** [comment]
Ping @AlbertoElias

**Comment by shamb0t** [comment]
Believe this was resolved in https://github.com/orbitdb/orbit-db-kvstore/pull/33, feel free to reopen if this is still an issue :)
