### ISSUE TITLE
Documentation should specify the types of databases we can create.

### ISSUE THREAD

**Issue by crazyrabbitLTC** [orbitdb/orbit-db#628]
At this point in the Documentation: 

https://github.com/orbitdb/orbit-db/blob/master/API.md#orbitdbcreatename-type-options

We are shown how to create a database, however, we don't have any list of the types of databases we can create (the example shows: 'eventlog') however it's unclear if KeyValue store should be 'kvstore' or 'keyValue', etc... 

We should list the various types and the strings that corespond to them here.

**Comment by RichardLitt** [comment]
Sounds good to me. Would you be able to craft a PR?

**Comment by crazyrabbitLTC** [comment]
Almost forgot about this comment! I'm a little tight for the next week but I'll try to do it, would be a pleasure to contribute!!!

**Comment by aphelionz** [comment]
Keeping this here until the docs are updated but then will move to the field-manual repo after

**Comment by 1-byte-man** [comment]
I made this #702 . is this okay?

**Comment by RichardLitt** [comment]
@1-byte-man Totally OK! Some small changes are needed for that PR, but it looks pretty great to me. :)

**Comment by shamb0t** [comment]
Resolved by #702, thank you @1-byte-man!
