### ISSUE TITLE
v0.20.0 - js-ipfs-http-client pubsub support and go-ipfs

### ISSUE THREAD

**Issue by movefasta** [orbitdb/orbit-db#632]
Greetings everyone!
With v0.20.0 release was added support for using OrbitDB with go-ipfs (through js-ipfs-http-client) -
https://github.com/orbitdb/orbit-db/blob/master/CHANGELOG.md#go-ipfs-support

I tried to run OrbitDB in browser with go-ipfs 0.4.19 and got an error in console.log:
`Error: pubsub is currently not supported when run in the browser` and find out that `ipfs-pubsub` is still unsupported in `js-ipfs-http-client`: https://github.com/ipfs/js-ipfs-http-client/issues/518

Is it bug or i doing something wrong ?

**Comment by phillmac** [comment]
AFAIK there's not been any progress on this, the issue you referenced is still open.

**Comment by movefasta** [comment]
> AFAIK there's not been any progress on this, the issue you referenced is still open.
If orbit-db requires ipfs-pubsub to work, is it fair to say that in reality there is no support for go-ipfs in orbit-db, because js-ipfs-http-client does not support ipfs-pubsub.

**Comment by phillmac** [comment]
There's no in-browser support, sure. js-ipfs-http-client does support pubsub in Node.js environments however.

**Comment by phillmac** [comment]
https://discuss.ipfs.io/t/pubsub-in-the-browser-with-the-js-ipfs-http-api-client/6174
Fixed by: https://github.com/ipfs/js-ipfs-http-client/pull/1059
