### ISSUE TITLE
Cannot read property set of undefined

### ISSUE THREAD

**Issue by voxsoftware** [orbitdb/orbit-db#635]
Cannot read property 'set' of undefined","stack":"TypeError: Cannot read property 'set' of undefined\n    at OrbitDB._addManifestToCache (/home/james/test/node_modules/orbit-db/src/OrbitDB.js:373:17

**Comment by shamb0t** [comment]
Hey @voxsoftware are you using a custom cache? Can you provide the code which throws the above error?

**Comment by RichardLitt** [comment]
Ping @voxsoftware

**Comment by shamb0t** [comment]
Closing for now as more info needed. Pleas do reopen if this is still an issue :)
