### ISSUE TITLE
Announcement: Meetup in Berlin, June 10th

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbit-db#639]
👋 Hey everyone. In case you're not a watcher in the [community repo](https://github.com/orbitdb/welcome), we're planning a meetup in Berlin on June 10th. We'd love to know if you're in the area and would like to join us. 

Our planning thread is here: https://github.com/orbitdb/welcome/issues/63. Let us know if you can make it!

Locking this thread to avoid duplicative comments and noise.

**Comment by aphelionz** [comment]
Closing this as the event has passed
