### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [orbitdb/orbit-db#648]
i get very low performance. just about 50 inserts per second.
this code runs 3+ seconds:
```js
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

// OrbitDB uses Pubsub which is an experimental feature
// and need to be turned on manually.
// Note that these options need to be passed to IPFS in
// all examples in this document even if not specified so.
const ipfsOptions = {
    EXPERIMENTAL: {
        pubsub: true
    }
}

// Create IPFS instance
const ipfs = new IPFS(ipfsOptions)

ipfs.on('ready', async () => {
    // Create OrbitDB instance
    const orbitdb = await OrbitDB.createInstance(ipfs)
    const dbkv = await orbitdb.keyvalue('keyvalue-database')

    let c = 1
    while (c <= 100) {
        await dbkv.put(c, c)
        c++
        console.log(c);
    }
    console.log(await dbkv.get(c-1));
    process.exit(0)
})
```
even if remove console.log in a loop - it's still 3+ sec.

platform: 
MacOS, SSD
node --version
v10.16.0

**Comment by aphelionz** [comment]
Hi @Vasiliy-Bondarenko thanks for opening an issue.

I've mitigated a large performance issue in this branch, please have a look: https://github.com/orbitdb/orbit-db/tree/fix/persistent-keystore

**Comment by RichardLitt** [comment]
@Vasiliy-Bondarenko have you tried the branch that @aphelionz suggested?

**Comment by aphelionz** [comment]
@Vasiliy-Bondarenko Improved performance is now in RC if you want to test it out - `npm install orbit-db@next`. I'm going to close this for now and you can either re-open this or create new issues if you have trouble.
