### ISSUE TITLE
How to check if a PeerID has write-permission

### ISSUE THREAD

**Issue by hazae41** [orbitdb/orbit-db#649]
If someone says "here is my database /orbitdb/.../mydatabase"

How do I check if he is the owner of the database, using only his IPFS peerID?

**Comment by RichardLitt** [comment]
@hazae41 Did you find the solution for this? :)

**Comment by hazae41** [comment]
I found an array named "write" in an object named "access" in the database object
![](https://i.imgur.com/STDu1ws.png)
But this array contains orbit-db peerIDs, not ipfs peerIDs

**Comment by hazae41** [comment]
It seems an orbit-db app must only use orbit-db peerIDs as they are the only way of proving an identity
https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#identity

So an ipfs peerID refers to the device, while an orbit-db peerID refers to a certain profile in the app

**Comment by RichardLitt** [comment]
Well that is succinct. Thank you!
