### ISSUE TITLE
OrbitDB in simple DAPP with CRUD operations

### ISSUE THREAD

**Issue by kottackalthulasi** [orbitdb/orbit-db#656]
Can anyone suggest a simple orbitdb DAPP with CRUD operations?

**Comment by kottackalthulasi** [comment]
Thanks for the support. I have solved it by myself. Its because of the babel configuration in webpack. I tried different plugins and packages. Here I am attaching my babel configuration code and package.json.

BABEL CONFIGURATION
module: { rules: [{ test: /\.js$/, // exclude: /(node_modules|bower_components)/, exclude: { test: /(node_modules|bower_components)/, // Do not exclude this dependency // not: [/libp2p/,/p-queue/] not: [/libp2p/,/p-queue/,/orbit-db-access-controllers/] }, use: { loader: 'babel-loader', options: { presets: [ [ 'env', { targets: { node: '10.16.0' } } ] ], plugins: [ 'transform-object-rest-spread', 'transform-class-properties' ] } } }] },

package.json
{ "name": "truffle-init-webpack", "version": "0.0.2", "description": "Frontend example using truffle v3", "scripts": { "lint": "eslint ./", "build": "webpack", "dev": "webpack-dev-server" }, "author": "Thulasi", "license": "tk", "devDependencies": { "@babel/preset-env": "^7.5.0", "babel-core": "^6.22.1", "babel-eslint": "^6.1.2", "babel-loader": "^7.1.0", "babel-plugin-transform-async-to-generator": "^6.24.1", "babel-plugin-transform-class-properties": "^6.24.1", "babel-plugin-transform-es2015-classes": "^6.24.1", "babel-plugin-transform-object-rest-spread": "^6.26.0", "babel-plugin-transform-runtime": "^6.23.0", "babel-polyfill": "^6.26.0", "babel-preset-env": "^1.1.8", "babel-preset-es2015": "^6.22.0", "babel-preset-es2015-node5": "^1.2.0", "babel-register": "^6.22.0", "copy-webpack-plugin": "^4.0.1", "css-loader": "^0.26.1", "eslint": "^3.14.0", "eslint-config-standard": "^6.0.0", "eslint-plugin-babel": "^4.0.0", "eslint-plugin-mocha": "^4.8.0", "eslint-plugin-promise": "^3.0.0", "eslint-plugin-standard": "^2.0.0", "html-webpack-plugin": "^2.28.0", "json-loader": "^0.5.4", "react": "^16.7.0", "style-loader": "^0.13.1", "truffle-contract": "^1.1.6", "web3": "^0.18.2", "webpack-dev-server": "^2.3.0" }, "dependencies": { "@0xcert/ethereum-utils": "^1.1.0", "@nodeutils/defaults-deep": "^1.1.0", "aes256": "^1.0.4", "async": "^3.0.1", "async-waterfall": "^0.1.5", "awesome-pie-chart": "^0.4.0", "babel-polyfill": "^6.26.0", "bluebird": "^3.5.3", "canvasjs": "^1.8.1", "country-list": "^2.1.0", "cryptr": "^4.0.0", "d3": "^5.7.0", "dgram": "^1.0.1", "file-saver": "^2.0.0", "fs": "0.0.1-security", "geoip-lite": "^1.3.5", "instascan": "^1.0.0", "ip-to-int": "^0.3.1", "ipfs": "^0.33.1", "ipfs-api": "^14.0.4", "ipfs-pubsub-room": "^1.2.1", "iplocation": "^6.1.0", "jszip": "^3.1.5", "knockout": "^3.5.0", "libp2p": "^0.25.4", "libp2p-bootstrap": "^0.9.7", "libp2p-kad-dht": "^0.15.2", "libp2p-mdns": "^0.12.3", "libp2p-mplex": "^0.8.5", "libp2p-multiplex": "^0.5.0", "libp2p-secio": "^0.11.1", "libp2p-spdy": "^0.13.3", "libp2p-tcp": "^0.13.0", "libp2p-webrtc-star": "^0.13.2", "libp2p-websockets": "^0.12.2", "mongodb": "^3.1.9", "mongoose": "^5.3.10", "multer": "^1.4.1", "multiaddr": "^6.1.0", "node-where": "^1.1.0", "openzeppelin-solidity": "^1.12.0", "orbit-db": "^0.21.4", "peer-book": "^0.5.1", "peer-id": "^0.12.2", "peer-info": "^0.15.1", "public-ip": "^3.0.0", "pull-pushable": "^2.2.0", "pull-stream": "^3.6.12", "pull-stream-to-stream": "^1.3.4", "pusher": "^2.2.0", "qr-image": "^3.2.0", "qrcode-generator": "^1.4.1", "query-string": "^6.7.0", "readable-stream": "^3.0.2", "readmore-js": "^2.2.1", "request": "^2.88.0", "sendotp": "^1.2.9", "string-split": "^0.3.1", "sweetalert": "^2.1.0", "sweetalert2": "^7.32.2", "truffle": "^4.1.5", "typedarray-to-buffer": "^3.1.2", "utf8": "^3.0.0", "webpack": "^3.11.0", "xmlhttprequest": "^1.8.0" } }

**Comment by kottackalthulasi** [comment]
I have done it in my DAPP. CRUD for different OrbitDB database types is attached below.

> Code
```
//  ORBITDB
      const ipfsOptions = {
        EXPERIMENTAL: {
          pubsub: true
        }
      }
      // Create IPFS instance
        const ipfs = new IPFSS(ipfsOptions)

        ipfs.on('error', (e) => console.error(e))
        ipfs.on('ready', async () => {
          const orbitdb = await OrbitDB.createInstance(ipfs)
```
          
  ```
// // LOG DataStructure
          // // // Create / Open a database
          // const db = await orbitdb.log('UserData Log')
          // console.log("USER DATA ORBITDB")
          // console.log(db);
          // await db.load()

          // // Listen for updates from peers
          // db.events.on('replicated', (address) => {
          //   console.log(db.iterator({ limit: -1 }).collect())
          // })

          // // Add an entry
          // const hash  = await db.add(VendorName)
          // const hash1 = await db.add(VendorEmailAddress)
          // const hash2 = await db.add(metamaskAdd)
          // const hash3 = await db.add(phNo)
          // const hash4 = await db.add(convertedImage)
          // console.log(hash+ hash1 + hash2 + hash3 + hash4)
          // console.log(db.get(hash)) //GET

          // // Query Iterator
          // const result = db.iterator({ limit: -1 }).collect()
          // console.log(JSON.stringify(result, null, 2))
```

  ```
// // FEED DataStructure
          // // Create / Open a Feed database 
          // const db = await orbitdb.feed('UserData FEED')
          // console.log("USER DATA ORBITDB")
          // console.log(db);
          // await db.load()

          // // Listen for updates from peers
          // db.events.on('replicated', (address) => {
          //   console.log(db.iterator({ limit: -1 }).collect())
          // })

          // //  add(data)
          // const hash  = await db.add(VendorName)
          // const hash1 = await db.add(VendorEmailAddress)
          // const hash2 = await db.add(metamaskAdd)
          // const hash3 = await db.add(phNo)
          // const hash4 = await db.add(convertedImage)
          // console.log(db.get(hash)) //GET => get(hash)

          // //  remove(hash)
          // const hashRemove = await db.remove(hash)
          // console.log("DEL")
          // console.log(db.get(hash));

          // // Query Iterator
          // const result = db.iterator({ limit: -1 }).collect()
          // console.log(JSON.stringify(result, null, 2))


```
  ```
// // Key Value DataStructure
          // Creates and opens a keyvalue database
          // const db = await orbitdb.keyvalue('User Data KeyValue')
          // console.log("USER DATA ORBITDB");
          // console.log(db);
          // await db.load()

          // //put(key, value)
          // await db.put('Name', { name: VendorName })
          // await db.put('Email', { name: VendorEmailAddress })
          // await db.put('Wallet', { name: metamaskAdd })
          // await db.put('Phn', { name: phNo })
          // await db.put('Pic', { name: convertedImage })
          // console.log(db.get('Phn')); //GET

          // //set(key, value) alias for put
          // await db.set('hello', { name: 'Friend' })


          // // del(key)
          // const hash = await db.del('Phn')
          // console.log(hash); // QmbYHhnXEdmdfUDzZKeEg7HyG2f8veaF2wBrYFcSHJ3mvd
          // console.log(db.get('Phn')); //undefined


```
  // // DOCSTORE
        // //Creates and opens a docstore database
        // const db = await orbitdb.docs('User Data DOCSTORE');
        const db = await orbitdb.docs('User Data DOCSTORE', { indexBy: 'name' })
        console.log(db);
        await db.load();

        // put(doc)        
        var hash = await db.put({ _id: 'QmAwesomeIpfsHash', name: VendorName, followers: 100 })
        var hash1 = await db.put({ _id: 'QmAwesomeIpfsHash', name: VendorEmailAddress, followers: 200 })
        var hash2 = await db.put({ _id: 'QmAwesomeIpfsHash', name: metamaskAdd, followers: 300 })
        var hash3 = await db.put({ _id: 'QmAwesomeIpfsHash', name: phNo, followers: 500 })
        var hash4 = await db.put({ _id: 'QmAwesomeIpfsHash', name: convertedImage, followers: 500 })
        console.log(db.get(phNo)); //GET

        // get(key)
        const profile = db.get(VendorName);
        console.log(profile);
        // to get all the records
        const profileFull = db.get('');
        console.log(profileFull)

        var hash = await db.put({ _id: 'QmAwesomeIpfsHash', name: VendorName+ ' TestUpdate', followers: 100 })

        // query(mapper)      
        const all = db.query((doc) => doc.followers <= 200)
        console.log(all)
        
        // del(key)        
        const hashDel = await db.del(VendorName)
        console.log(db.get(VendorName))
            
 ```
 // // COUNTER TYPE
          // //Creates and opens a counter database
          // const counter = await orbitdb.counter('USER DATA COUNTER')
          // console.log(counter);
          // await counter.load();

          // // value
          // console.log(counter.value) //0

          // await counter.inc()
          // console.log(counter.value) // 1
          // await counter.inc(7)
          // counter.value // 8
          // await counter.inc(-2)
          // counter.value // 8



          


        })
```

**Comment by shamb0t** [comment]
Thanks @kottackalthulasi
