### ISSUE TITLE
Why OrbitDB is not getting worked with web application? I need a orbitdb sample application with CRUD operation.

### ISSUE THREAD

**Issue by kottackalthulasi** [orbitdb/orbit-db#657]

**Comment by phillmac** [comment]
What issues are you seeing?
Can you describe your problem a little more?

**Comment by kottackalthulasi** [comment]
I can connect with orbitdb. But operations like updation, deletion etc. are  not known. Cn you please provide the code for reference.

**Comment by phillmac** [comment]
The documentation has several examples, starting from here:
https://github.com/orbitdb/orbit-db/blob/master/API.md#public-instance-methods

**Comment by kottackalthulasi** [comment]
Thank you. But I still get some loader issues when I tried it with truffle. 
Errors showing while integrating with truffle as:
ERROR in ./~/ipld/src/index.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipld/src/index.js Unexpected token (90:37)
You may need an appropriate loader to handle this file type.
| }
|
| const generator = async function * () {
| // End iteration if there isn't a CID to follow anymore
| while (cid !== null) {

ERROR in ./~/ipfs/src/core/components/resolve.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipfs/src/core/components/resolve.js Unexpected token (40:10)
You may need an appropriate loader to handle this file type.
| let remainderPath = path
| try {
| for await (const result of results) {
| if (result.remainderPath === '') {
| // Use values from previous iteration if the value isn't a CID

ERROR in ./~/orbit-db-access-controllers/src/legacy-ipfs-access-controller.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/orbit-db-access-controllers/src/legacy-ipfs-access-controller.js Unexpected token (59:16)
You may need an appropriate loader to handle this file type.
|
| static async create (orbitdb, options = {}) {
| options = { ...options, ...{ write: options.write || [orbitdb.identity.publicKey] } }
| return new LegacyIPFSAccessController(orbitdb._ipfs, options)
| }

ERROR in ./~/orbit-db-access-controllers/src/orbitdb-access-controller.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/orbit-db-access-controllers/src/orbitdb-access-controller.js Unexpected token (51:8)
You may need an appropriate loader to handle this file type.
| // and make sure all values are Sets
| Object.entries({
| ...capabilities,
| // Add the root access controller's 'write' access list
| // as admins on this controller

ERROR in ./~/orbit-db-access-controllers/src/ipfs-access-controller.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/orbit-db-access-controllers/src/ipfs-access-controller.js Unexpected token (58:16)
You may need an appropriate loader to handle this file type.
|
| static async create (orbitdb, options = {}) {
| options = { ...options, ...{ write: options.write || [orbitdb.identity.id] } }
| return new IPFSAccessController(orbitdb._ipfs, options)
| }

ERROR in ./~/ipfs/src/core/components/files-regular/get-pull-stream.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipfs/src/core/components/files-regular/get-pull-stream.js Unexpected token (29:8)
You may need an appropriate loader to handle this file type.
| toPullStream.source(exporter.recursive(ipfsPath, self._ipld, options)),
| map(mapFile({
| ...options,
| includeContent: true
| }))

ERROR in ./~/async-iterator-all/index.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/async-iterator-all/index.js Unexpected token (6:6)
You may need an appropriate loader to handle this file type.
| const arr = []
|
| for await (const entry of iterator) {
| arr.push(entry)
| }

ERROR in ./~/pull-stream-to-async-iterator/index.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/pull-stream-to-async-iterator/index.js Unexpected token (4:25)
You may need an appropriate loader to handle this file type.
|
| module.exports = source => {
| return (async function * () {
| let _read
|

ERROR in ./~/libp2p/src/index.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/libp2p/src/index.js Unexpected token (120:8)
You may need an appropriate loader to handle this file type.
| this._dht = new DHT(this._switch, {
| datastore: this.datastore,
| ...this._config.dht
| })
| }

ERROR in ./~/libp2p-kad-dht/src/index.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/libp2p-kad-dht/src/index.js Unexpected token (115:6)
You may need an appropriate loader to handle this file type.
| this.validators = {
| pk: libp2pRecord.validator.validators.pk,
| ...options.validators
| }
|

ERROR in ./~/ipfs-unixfs-importer/src/index.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipfs-unixfs-importer/src/index.js Unexpected token (74:32)
You may need an appropriate loader to handle this file type.
| })
|
| module.exports = async function * (source, ipld, options = {}) {
| const opts = Options(options)
|

ERROR in ./~/ipfs-unixfs-exporter/src/index.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipfs-unixfs-exporter/src/index.js Unexpected token (47:32)
You may need an appropriate loader to handle this file type.
| }
|
| const walkPath = async function * (path, ipld) {
| let {
| cid,

ERROR in ./~/pull-mplex/src/mplex.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/pull-mplex/src/mplex.js Unexpected token (54:6)
You may need an appropriate loader to handle this file type.
| maxMsgSize: MAX_MSG_SIZE,
| lazy: false,
| ...opts
| }
|

ERROR in ./~/ipfs-mfs/src/core/write.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipfs-mfs/src/core/write.js Unexpected token (173:45)
You may need an appropriate loader to handle this file type.
|
| return {
| [Symbol.asyncIterator]: async function * () {}
| }
| })

ERROR in ./~/ipfs-mfs/src/core/read.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipfs-mfs/src/core/read.js Unexpected token (18:45)
You may need an appropriate loader to handle this file type.
|
| return {
| [Symbol.asyncIterator]: async function * read () {
| const mfsPath = await toMfsPath(context, path)
| const result = await exporter(mfsPath.mfsPath, context.ipld)

ERROR in ./~/ipfs-mfs/src/core/ls.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipfs-mfs/src/core/ls.js Unexpected token (33:24)
You may need an appropriate loader to handle this file type.
|
| module.exports = (context) => {
| return async function * mfsLs (path = FILE_SEPARATOR, options = {}) {
| if (typeof path === 'object' && !(path instanceof String)) {
| options = path

ERROR in ./~/ipfs-mfs/src/core/utils/update-tree.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipfs-mfs/src/core/utils/update-tree.js Unexpected token (20:6)
You may need an appropriate loader to handle this file type.
| let child
|
| for await (const node of context.ipld.getMany(trail.map(node => node.cid))) {
| const cid = trail[index].cid
| const name = trail[index].name

ERROR in ./~/ipfs-mfs/src/core/utils/to-trail.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipfs-mfs/src/core/utils/to-trail.js Unexpected token (11:6)
You may need an appropriate loader to handle this file type.
| const output = []
|
| for await (const fsEntry of exporter.path(path, context.ipld)) {
| output.push({
| name: fsEntry.name,

ERROR in ./~/ipfs-unixfs-importer/src/dir-sharded.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/ipfs-unixfs-importer/src/dir-sharded.js Unexpected token (66:8)
You may need an appropriate loader to handle this file type.
| }
|
| async * eachChildSeries () {
| for await (const { key, value } of this._bucket.eachLeafSeries()) {
| yield {

ERROR in ./~/async-iterator-last/index.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/async-iterator-last/index.js Unexpected token (6:6)
You may need an appropriate loader to handle this file type.
| let res
|
| for await (const entry of iterator) {
| res = entry
| }

ERROR in ./~/p-queue/index.js
Module parse failed: /home/kottackal/Documents/Thulasi/BlockChain/first/node_modules/p-queue/index.js Unexpected token (33:3)
You may need an appropriate loader to handle this file type.
| options = {
| priority: 0,
| ...options
| };
|

Input Code
Error occurs while using this code.

const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')
// OrbitDB uses Pubsub which is an experimental feature
// and need to be turned on manually.
// Note that these options need to be passed to IPFS in
// all examples even if not specified so.
const ipfsOptions = {
EXPERIMENTAL: {
pubsub: true
}
}

// Create IPFS instance
const ipfs = new IPFS(ipfsOptions)

ipfs.on('error', (e) => console.error(e))
ipfs.on('ready', async () => {
const orbitdb = await OrbitDB.createInstance(ipfs)

// Create / Open a database
const db = await orbitdb.log('hello')
await db.load()

// Listen for updates from peers
db.events.on('replicated', (address) => {
console.log(db.iterator({ limit: -1 }).collect())
})

// Add an entry
const hash = await db.add('world')
console.log(hash)

// Query
const result = db.iterator({ limit: -1 }).collect()
console.log(JSON.stringify(result, null, 2))
})



**Babel Configuration 

 module: {
    rules: [
      {
       test: /\.css$/,
       use: [ 'style-loader', 'css-loader' ]
      }
    ],
    loaders: [
      { test: /\.json$/, use: 'json-loader' },
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015'],
          plugins: ['transform-runtime']
        }
      }
    ]
  }
Environment

Babel cli version: 6.26.0
Node/npm version: 10.16.0
OS: [Ubuntu 18.04]

**Comment by kottackalthulasi** [comment]
Thanks for the support. I have solved it by myself. Its because of the babel configuration in webpack. I tried different plugins and packages. Here I am attaching my babel configuration code and package.json.

> BABEL CONFIGURATION
``
module: {
    rules: [{
      test: /\.js$/,
     // exclude: /(node_modules|bower_components)/,
             exclude: {
          test: /(node_modules|bower_components)/,
          // Do not exclude this dependency
         // not: [/libp2p/,/p-queue/]
         not: [/libp2p/,/p-queue/,/orbit-db-access-controllers/]
        },
      use: {
        loader: 'babel-loader',
        options: {
          presets: [
            [
              'env',
              {
                targets: {
                  node: '10.16.0'
                }
              }
            ]
          ],
          plugins: [
            'transform-object-rest-spread',
            'transform-class-properties'
          ]
        }
      }
    }]
  },

``

> package.json
``
{
  "name": "truffle-init-webpack",
  "version": "0.0.2",
  "description": "Frontend example using truffle v3",
  "scripts": {
    "lint": "eslint ./",
    "build": "webpack",
    "dev": "webpack-dev-server"
  },
  "author": "Thulasi",
  "license": "tk",
  "devDependencies": {
    "@babel/preset-env": "^7.5.0",
    "babel-core": "^6.22.1",
    "babel-eslint": "^6.1.2",
    "babel-loader": "^7.1.0",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.1.8",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-es2015-node5": "^1.2.0",
    "babel-register": "^6.22.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "eslint": "^3.14.0",
    "eslint-config-standard": "^6.0.0",
    "eslint-plugin-babel": "^4.0.0",
    "eslint-plugin-mocha": "^4.8.0",
    "eslint-plugin-promise": "^3.0.0",
    "eslint-plugin-standard": "^2.0.0",
    "html-webpack-plugin": "^2.28.0",
    "json-loader": "^0.5.4",
    "react": "^16.7.0",
    "style-loader": "^0.13.1",
    "truffle-contract": "^1.1.6",
    "web3": "^0.18.2",
    "webpack-dev-server": "^2.3.0"
  },
  "dependencies": {
    "@0xcert/ethereum-utils": "^1.1.0",
    "@nodeutils/defaults-deep": "^1.1.0",
    "aes256": "^1.0.4",
    "async": "^3.0.1",
    "async-waterfall": "^0.1.5",
    "awesome-pie-chart": "^0.4.0",
    "babel-polyfill": "^6.26.0",
    "bluebird": "^3.5.3",
    "canvasjs": "^1.8.1",
    "country-list": "^2.1.0",
    "cryptr": "^4.0.0",
    "d3": "^5.7.0",
    "dgram": "^1.0.1",
    "file-saver": "^2.0.0",
    "fs": "0.0.1-security",
    "geoip-lite": "^1.3.5",
    "instascan": "^1.0.0",
    "ip-to-int": "^0.3.1",
    "ipfs": "^0.33.1",
    "ipfs-api": "^14.0.4",
    "ipfs-pubsub-room": "^1.2.1",
    "iplocation": "^6.1.0",
    "jszip": "^3.1.5",
    "knockout": "^3.5.0",
    "libp2p": "^0.25.4",
    "libp2p-bootstrap": "^0.9.7",
    "libp2p-kad-dht": "^0.15.2",
    "libp2p-mdns": "^0.12.3",
    "libp2p-mplex": "^0.8.5",
    "libp2p-multiplex": "^0.5.0",
    "libp2p-secio": "^0.11.1",
    "libp2p-spdy": "^0.13.3",
    "libp2p-tcp": "^0.13.0",
    "libp2p-webrtc-star": "^0.13.2",
    "libp2p-websockets": "^0.12.2",
    "mongodb": "^3.1.9",
    "mongoose": "^5.3.10",
    "multer": "^1.4.1",
    "multiaddr": "^6.1.0",
    "node-where": "^1.1.0",
    "openzeppelin-solidity": "^1.12.0",
    "orbit-db": "^0.21.4",
    "peer-book": "^0.5.1",
    "peer-id": "^0.12.2",
    "peer-info": "^0.15.1",
    "public-ip": "^3.0.0",
    "pull-pushable": "^2.2.0",
    "pull-stream": "^3.6.12",
    "pull-stream-to-stream": "^1.3.4",
    "pusher": "^2.2.0",
    "qr-image": "^3.2.0",
    "qrcode-generator": "^1.4.1",
    "query-string": "^6.7.0",
    "readable-stream": "^3.0.2",
    "readmore-js": "^2.2.1",
    "request": "^2.88.0",
    "sendotp": "^1.2.9",
    "string-split": "^0.3.1",
    "sweetalert": "^2.1.0",
    "sweetalert2": "^7.32.2",
    "truffle": "^4.1.5",
    "typedarray-to-buffer": "^3.1.2",
    "utf8": "^3.0.0",
    "webpack": "^3.11.0",
    "xmlhttprequest": "^1.8.0"
  }
}

``

**Comment by aphelionz** [comment]
Awesome!
