### ISSUE TITLE
User with granted admin access cannot grant admin access

### ISSUE THREAD

**Issue by hazae41** [orbitdb/orbit-db#664]
UserA creates a database, then grants admin and write access to UserB.
UserB wants to grant admin and write access to UserC but he can't.

![](https://i.imgur.com/YsTpe95.png)

**Comment by hazae41** [comment]
It works when UserA tries to grant admin and write access to UserC

**Comment by phillmac** [comment]
My best guess here is that the db store backing the access controller hasn't replicated from UserA to UserB. 
Can you confirm or disprove this?
