### ISSUE TITLE
Come hack with us at Web3 in Berlin on Monday!

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbit-db#665]
We're hosting a hack session for OrbitDB at the p2p Node hackspace at [Web3](https://web3summit.com/) in Berlin next Monday. If you're around, come and hack with us!

**What it is:** A tutorial for how to implement OrbitDB to build a basic app
**When:**  Monday at 15:35, for 50 minutes
**Where:** P2P Node in the Hackerspace.
**Workshop Leaders:** @shamb0t, @aphelionz, and @RichardLitt
**Goal:** Build a functional OrbitDB app, so that you can understand the basics of using decentralized databases.

We're going to show you how to build a decentralized playlist - think Spotify playlists, but on the decentralized net. Awesome!

We'll be going through a small tutorial app we've built as an example. We'll have dedicated mentors on hand to help out with questions, and, instead of a talk format, encourage learning while doing.

Experienced people are also encouraged to attend! While we can't focus on your custom PubSub implementation, we can certainly answer some questions and be around to help out here and there.

More details will be forthcoming as soon as we have them. Feel free to ask questions, as always, on [the Gitter](https://gitter.im/orbitdb/Lobby).

**Comment by aphelionz** [comment]
Closing as the workshop has passed
