### ISSUE TITLE
Check removed and added elements in feed db after a replicate

### ISSUE THREAD

**Issue by lukas2005** [orbitdb/orbit-db#666]
I'm trying to figure out which elements in a feed db got removed and which added inside a replicated event handler without having to iterate over the entire thing several times. Any suggestions?

**Comment by aphelionz** [comment]
Thanks for making an issue @lukas2005 . Can you tell me a little bit more about what you're working with? Are you only looking at what's coming across during the head exchange? Or are you looking at a full index?

**Comment by lukas2005** [comment]
I'm just trying to get differences in the data I'm storing so that then I can emit events that notify other parts of the app of new and removed elements

**Comment by phillmac** [comment]
Perhaps you could try listening to the [replicate.progress](https://github.com/orbitdb/orbit-db/blob/master/API.md#replicateprogress) event. The `entry` field might have what you're looking for

**Comment by aphelionz** [comment]
Yes, @phillmac is right. You can monitor that and then emit events based on the payloads that come through and/or the delta between what you have and what you got

**Comment by lukas2005** [comment]
Ok thanks
