### ISSUE TITLE
Is there any private instance available for Orbit DB. If there, then please provide more information regarding its installation.

### ISSUE THREAD

**Issue by kottackalthulasi** [orbitdb/orbit-db#667]
Please provide more installation details regarding orbit DB private instance for Ethereum Blockchain applications.

**Comment by aphelionz** [comment]
Hi @kottackalthulasi, thanks for asking this. This will soon be included in the Field Manual but for now I can type out an answer here, and then others can also chime in with techiques that work for them.

For starters, I believe there's two main routes you can go, and you can do both of them:

1. Run a private IPFS network. I wrote a blog post about how to do it here: https://mrh.io/ipfs-private-networks/ Essentially the IPFS nodes that are running share a swarm key, and cannot connect to any other nodes that don't have the same swarm key. Other public nodes don't swarm with your nodes either.

2. Encrypt-at-rest all persisted data with user keys. you can use metamask keys for this by way of the identity-provider. There's an implementation here: https://github.com/orbitdb/orbit-db-identity-provider/blob/master/src/ethereum-identity-provider.js  Essentially the metamask keys are cross-signed with the orbitdb keys proving ownership of both and then you have full write-protection via Metamask

**Comment by kottackalthulasi** [comment]
@aphelionz Thanks for the reply. I have already set up my IPFS as private network. But I don't understand how the step-2 can be implemented. Can you please explain it in more detail.

**Comment by kottackalthulasi** [comment]
@aphelionz Let me know if there is a private IPFS network, then the initiating orbitdb will also use private instance? Sorry if it's wrong.

**Comment by phillmac** [comment]
@kottackalthulasi That's correct. Orbitdb relies on ipfs for all of its network IO, so if ipfs is in private swarm mode, then orbitdb will be unable to connect to anything outside the private ipfs swarm.

**Comment by kottackalthulasi** [comment]
@phillmac thanks for the response

**Comment by RichardLitt** [comment]
@kottackalthulasi 	Closing this as answered. Thank you. :)
