### ISSUE TITLE
How to import a .csv file dataset to docstore orbitdb?

### ISSUE THREAD

**Issue by kottackalthulasi** [orbitdb/orbit-db#669]
I would like to start a prediction mechanism using orbitdb. For that I am using a .csv file dataset as input. So anyone please help me to import a .csv file as input to docstore orbitdb.

**Comment by RichardLitt** [comment]
I'm not sure that this is a bug or a feature request for OrbitDB. You might find the answer in the [field manual](https://github.com/orbitdb/field-manual). If not, the best place to ask is on the Gitter. 

I am going to close this as non-actionable. Feel free to dispute this, though!

**Comment by aphelionz** [comment]
@kottackalthulasi Good news and bad news.

`orbit-db-cli` has an "import" function that takes a CSV into a docstore, essentially doing what you describe

The bad news is that the repo is out of date. However there is a branch you might try here: https://github.com/orbitdb/orbit-db-cli/tree/big-update
