### ISSUE TITLE
Release v0.22.0

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbit-db#670]
Closed. You should now refer to https://orbitdb.org/orbitdb-release-v0.22/

**Comment by phillmac** [comment]
Just a quick question is https://github.com/orbitdb/orbit-db-access-controllers/pull/36 being considered for this release? It'd be wonderful if I could close https://github.com/orbitdb/orbit-db-http-api/issues/20 :)

**Comment by aphelionz** [comment]
I don't see why not! @shamb0t ?

**Comment by aphelionz** [comment]
Actually it looks like perhaps this has been published to npm? Or do we need to publish `orbit-db-access-controller@0.2.3` ?

**Comment by phillmac** [comment]
Yeah it hasn't been published yet, version 0.2.2 doesn't include that PR

**Comment by aphelionz** [comment]
@phillmac Please try now - 0.2.3 was published. Hopefully that allows you to close your issue

**Comment by phillmac** [comment]
Thanks, that's great!

**Comment by sirfumblestone** [comment]
I would split the announcement to 1) orbitdb.org entry and 2) tweet to make sure both gets done 🙂 Additionally, maybe the 1) could also have the a high-level change log and then direct link to the .md file? I believe it would make it easier to quickly get an idea what's new?

**Comment by RichardLitt** [comment]
@aphelionz 	Can this be updated?
