### ISSUE TITLE
js-IPFS early testers programme

### ISSUE THREAD

**Issue by achingbrain** [orbitdb/orbit-db#682]
We're trying to improve our release process for [`js-IPFS`](https://github.com/ipfs/js-ipfs) and part of that is introducing an early testers programme.

Full details are on the doc at [`ipfs/js-ipfs/doc/EARLY_TESTERS.md`](https://github.com/ipfs/js-ipfs/tree/master/doc/EARLY_TESTERS.md) - if you'd like to join in and help out please send a PR updating that doc to add this repo and we'll open PRs here when new pre-release versions are available for testing.

**Comment by aphelionz** [comment]
Thanks @achingbrain. Weve added two of our projects to the list.

**Comment by achingbrain** [comment]
Great, I look forward to receiving the PR!

**Comment by aphelionz** [comment]
@achingbrain I guess I thought I had made the PR, but didn't click the final button. It's there now: https://github.com/ipfs/js-ipfs/pull/2498
