### ISSUE TITLE
Expose modules in OrbitDB class for the browser

### ISSUE THREAD

**Issue by hazae41** [orbitdb/orbit-db#715]
It's ridiculous that we need to reimport these modules while OrbitDB actually uses them.

How about static getters? so we can use

    const { OrbitDB } = window;
    const { Store } = OrbitDB;
    const { AccessControllers, AccessController } = OrbitDB;
    const { Identities, IdentityProvider } = OrbitDB;
    ...

Also, we should be able to add a custom access controller without needing the AccessControllers object

    OrbitDB.addAccessController(MyAccessController)

Same with identity providers

    OrbitDB.addIdentityProvider(MyIdentityProvider)
    
While we're at it, `OrbitDB.addDatabaseType(CustomStore.type, CustomStore)` should be simplified to  `OrbitDB.addDatabaseType(CustomStore)` and get the type directly from `CustomType.type`

**Comment by aphelionz** [comment]
While "ridiculous" might be subjective and debatable, I do agree that it would be convenient to have these modules available for custom work without having to explicitly import, for example, `orbit-db-access-controllers`

An easy way to achieve this might be to simply add them to the prototype of the already-exported OrbitDB class.

This would maintain backwards compatibility with existing codebases that are still using `const OrbitDB = require('orbit-db')` and still allow you the ease of customization via accessors like `OrbitDB.AccessControllers`

**Comment by shamb0t** [comment]
This was resolved by #717
