### ISSUE TITLE
Add queue for db operations

### ISSUE THREAD

**Issue by oed** [orbitdb/orbit-db#737]
Right now if you call multiple methods that updates an orbitdb store at the same time it will result in an error. For example with the `feedstore` if you call `store.add` twice but without waiting for the first promise to resolve it will cause only one of the updates to be added. This is a problem since as a user of orbitdb I might not always know when updates to a db have been made and if I need to wait for this promise to resolve.

To fix this an update queue can be added to the [_addOperation](https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L473) method of `orbit-db-store` which would wait for the previous operation to be fully added before starting to add a new one. 

Even though I was aware of this issue it took a while for me to figure out why an error was happening to me where one entry was missing. Turns out this is the problem. I've added a workaround for myself using a message queue on top of the `add` function for now. However the correct place to solve this seems to me like it should be in orbitdb itself :)

**Comment by oed** [comment]
I guess related: When I call `db.close()` the returned promise will resolve even if there is an operation in process of being added, which results in the db not getting properly closed.

**Comment by tabcat** [comment]
_addOperation calls adds a function to a queue and close awaits for the queue to empty before resolving

https://github.com/tabcat/orbit-db-store/commit/579173b2a9b45a741e8294273f9067330fd9e0ed

**Comment by aphelionz** [comment]
@tabcat Thanks for jumping in and taking a look at this. A question in your code: after adding it to the queue in `_addOperation` is there another place where the queue gets drained besides close? That seems to be like it would only add the operations when the db was closing.

**Comment by tabcat** [comment]
@aphelionz if i understand correctly you are asking if the operations added to queue are only executed when `await queue.onEmpty()` is called in close()? I'm not very familiar with the library but when i was looking at it earlier it seemed like they were executed concurrently on being added to queue however what you suggest could be the case.

**Comment by aphelionz** [comment]
No, you're probably correct. Just making sure. If the tests are passing feel free to make a PR. This looks like a good improvement.

**Comment by phillmac** [comment]
Closing as fixed by https://github.com/orbitdb/orbit-db-store/pull/85
