### ISSUE TITLE
This version of cids doesn't build in angular

### ISSUE THREAD

**Issue by sixcorners** [orbitdb/orbit-db#757]
See multiformats/js-cid#96 I get this error when I run `ng serve`.

**Comment by shamb0t** [comment]
Hey @sixcorners this appears to be fixed in `cids@0.7.2`, are you still getting the error? Which version of IPFS are you using and how are you including OrbitDB in your code?

**Comment by sixcorners** [comment]
When I changed the cids version in package-lock.json I stopped getting this error. I'm getting other errors now. though.

```json
    "orbit-db": "^0.23.0",
    "ipfs": "^0.40.0",
```

I'm adding the dependencies to a project created from angular's CLI. After I fix the cids issue I get references errors saying global doesn't exist. I've read that I guess I have to add browserify to the build. I'm not really sure yet.

**Comment by shamb0t** [comment]
@sixcorners did you manage to fix the issue? Can you elaborate on the reference errors?

**Comment by sixcorners** [comment]
@shamb0t I'm not really an expert on node stuff but I made a script to try to reproduce errors building this with angular.
```bash
npx @angular/cli new test --defaults
cd test
npm i ipfs
npm i orbit-db
cat <<EOF >>src/app/app.component.ts
import IPFS from 'ipfs';
import OrbitDB from 'orbit-db';

// For js-ipfs >= 0.38

// Create IPFS instance
const initIPFSInstance = async () => {
  return await IPFS.create({ repo: "./path-for-js-ipfs-repo" });
};

initIPFSInstance().then(async ipfs => {
  const orbitdb = await OrbitDB.createInstance(ipfs);

  // Create / Open a database
  const db = await orbitdb.log("hello");
  await db.load();

  // Listen for updates from peers
  db.events.on("replicated", address => {
    console.log(db.iterator({ limit: -1 }).collect());
  });

  // Add an entry
  const hash = await db.add("world");
  console.log(hash);

  // Query
  const result = db.iterator({ limit: -1 }).collect();
  console.log(JSON.stringify(result, null, 2));
});
EOF
npm run build
```

**Comment by sixcorners** [comment]
I'm not really the best person to be asking about this. I don't know how javascript gets built. So I'm closing this ticket.

**Comment by tabcat** [comment]
It looks like in the issue u referenced originally its been fixed upstream. best of luck
