### ISSUE TITLE
Ordbitdb don't create the folder

### ISSUE THREAD

**Issue by kypanz** [orbitdb/orbit-db#758]
Hello ! , i have a question , when i try to instanciate a orbitdb they don't create the folder i don't know why , somebody can help me please i try to solved but i cant, can be possible a permission problem ?

the error says : 
```

 Error: ENOENT: no such file or directory, mkdir 'orbitdb/QmSrPLkeZHLySrVYFLj8VEZZcrEgNME4BCHCqvahXzZ5ue/keystore'
    at Object.fs.mkdirSync (fs.js:840:3)
    at Promise (/home/kypanz/Escritorio/prueba/Dapp-V2/back/node_modules/orbit-db-storage-adapter/src/index.js:61:36)
```

i am using ubuntu

**Comment by shamb0t** [comment]
Hey @kypanz whch version of OrbitDB are you using? Can you share code of how you are creating your db?

**Comment by kypanz** [comment]
> Hey @kypanz whch version of OrbitDB are you using? Can you share code of how you are creating your db?

i can't solve , the error says : 
```
Error: ENOENT: no such file or directory, mkdir 'orbitdb/QmSrPLkeZHLySrVYFLj8VEZZcrEgNME4BCHCqvahXzZ5ue/keystore'
    at Object.fs.mkdirSync (fs.js:840:3)
    at Promise (/home/kypanz/Escritorio/prueba/Dapp-V2/back/node_modules/orbit-db-storage-adapter/src/index.js:61:36)

```

the code are : 
```
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

var change = {
  ipfs:undefined,
  orbitdb:undefined
}


iniciar();

async function iniciar () {

  const ipfsOptions = {
    EXPERIMENTAL: {
      pubsub: true
    }
  }

  const ipfs = await IPFS.create(ipfsOptions);
  change.ipfs = ipfs;


  const orbitdb = await OrbitDB.createInstance(ipfs)
  //const orbitdb = await OrbitDB(ipfs);  

change.orbitdb = orbitdb;

}

//module.exports = change;
```

**Comment by shamb0t** [comment]
You can run the command `npm ls orbit-db ipfs orbit-db-storage-adapter` to print the versions of orbit-db/ipfs you are using :)

> i create this code in another SO named manjaro and works fine , i think is a permission problem in ubuntu and i dont know how to solve

Could be the case. Does the error occur if you specify the repo as follows: 

``` 
const ipfsOptions = {
   repo: './ipfs-repo',
    EXPERIMENTAL: {
      pubsub: true
    }
  }

const ipfs = await IPFS.create(ipfsOptions)
```

(Note if you're using an ipfs version >= 0.38, you don't need the `EXPERIMENTAL` option)

**Comment by kypanz** [comment]
> You can run the command npm ls orbit-db ipfs orbit-db-storage-adapter to print the versions of orbit-db/ipfs you are using :)

I'm sorry I forgot it : 
```
├── ipfs@0.39.1 
└─┬ orbit-db@0.22.1 
  └── orbit-db-storage-adapter@0.5.3 

```
- NodeJs v10

I still thinking is a permission problem , because i install my repository in windows and manjaro and works fine , but when i install in ubuntu have problem to create te folders , if i am correct when the erorr says "mkdir" is a function that create a folder , in anothers OS don't show thats errors and is the same code, i really don't know how to do for ubuntu , i dont have more answers to solve this problem in ubuntu :(

**Comment by shamb0t** [comment]
@kypanz are you using node >= v10.12.0? I believe the recursive flag will be ignored otherwise and the directory is not created

**Comment by kypanz** [comment]
@shamb0t i am using v10.0.0 , i trying with the default ubuntu nodejs has installed in 8.0 and is the same problem , i dont know what's happend with ubuntu in anohters OS works fine  :(

the last i thinking is use the same version of nodejs and try if works fine, but really i think is a problem permission of ubuntu , i feeling at i need to do something in ubuntu to this error

- sorry for the late reply

**Comment by shamb0t** [comment]
@kypanz are you able to test with v10.12.0? This will clarify if it is a version or a permissions issue

**Comment by kypanz** [comment]
@shamb0t 

> This will clarify if it is a version and not a permissions issue

that's true , now i update nodejs to this version `v12.15.0` , and works fine, thanks a lot , problem solved <3
