### ISSUE TITLE
Unable to save Chat history

### ISSUE THREAD

**Issue by kottackalsulvin** [orbitdb/orbit-db#768]
Hi,

I am trying to develop a dapp-chat application using orbit-db and pushed the dynamic values into it. When I am trying to get all the pushed dynamic values(chat history) from orbit-db, but it shows only latest pushed value. I am new to orbit-db and please help me to resolve this issue. 

**Orbit-db Code**

```
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

// Create IPFS instance
const ipfs = new IPFS(ipfsOptions)

ipfs.on('ready', async () => {

  // Create OrbitDB instance
  const orbitdb = await OrbitDB.createInstance(ipfs)
  // DB creation
  const db = await orbitdb.docs('first-database')
  // pushing dynamic data in DB
  const hash = await db.put({name: name,msg: msg, })
  // getting data from DB
  const profile = db.get('');

})
```

**Comment by tabcat** [comment]
Hello @kottackalsulvin

could you try adding `await db.load()` the line after  `const db` is defined?

the .load method needs to be called and finish before adding entries to the store. if not all entries from previous sessions will not carry over but will be overwritten.
https://github.com/orbitdb/orbit-db/blob/master/API.md#storeloadamount--fetchentrytimeout-

**Comment by kottackalsulvin** [comment]
@tabcat Updated my code as below. But the message is still overwritting.
ipfs.on('ready', async () => {
  const orbitdb = await OrbitDB.createInstance(ipfs)
  const db = await orbitdb.docs('Chat',{indexBy: 'name'})
  await db.load(); 
  const hash = await db.put({name: name,msg: msg, })
  const profile = db.get('');
})

**Comment by kottackalsulvin** [comment]
@tabcat Updated the code as below. But the message is still overwritting.
```
ipfs.on('ready', async () => {
  const orbitdb = await OrbitDB.createInstance(ipfs)
  const db = await orbitdb.docs('Chat',{indexBy: 'name'})
  await db.load(); 
  const hash = await db.put({name: name,msg: msg, })
  const profile = db.get('');
})
```

**Comment by aphelionz** [comment]
I believe this was resolved in [Gitter](https://gitter.im/orbitdb/Lobby) by moving `db.load` until after `db.put`

**Comment by valerius21** [comment]
@aphelionz THANK YOU! I was slowly getting mad bc I didn't find the issue.
