### ISSUE TITLE
Release v0.24.0

### ISSUE THREAD

**Issue by vaultec81** [orbitdb/orbit-db#772]
### What's left for release
* ready for js-ipfs v0.41 (#767)
* Orbit-db-store update to `v3.2.0`
     * https://github.com/orbitdb/orbit-db-store/pull/87
     * _addOperation calls are serialized fixes #737 (https://github.com/orbitdb/orbit-db-store/pull/85)
* Update documentation
     * Include oplog specific events into API.md
* adds toJSON method to orbitdb address class (https://github.com/orbitdb/orbit-db/pull/756)
* Add db events to orbitdb instance (https://github.com/orbitdb/orbit-db/pull/713)
    * Raise db scope events to orbitdb instance scope event emitter (https://github.com/orbitdb/orbit-db-store/pull/92)

- [ ] Update change log
- [ ] Blog post on orbitdb.org
- [ ] Update field manual.
- [ ] Contributors & thank yous list

### Estimated shipping date
TBD

### General bugfixes and updates: 

Relevant PRs
* fix: fix documentation (https://github.com/orbitdb/orbit-db/pull/770)
* Update matrix and discord links (https://github.com/orbitdb/orbit-db/pull/766)
* fix: fix Module with IPFS Instance (https://github.com/orbitdb/orbit-db/pull/770)
* Fix assert.notEqual (https://github.com/orbitdb/orbit-db/pull/769)

Relevant issues:
* Add queue for db operations (https://github.com/orbitdb/orbit-db/issues/737)

Reviewers and contributions are welcome.

**Comment by aphelionz** [comment]
Thanks for doing this @vaultec81

**Comment by tabcat** [comment]
i think it would be great if these could be included with the next release:
https://github.com/orbitdb/orbit-db/pull/756
https://github.com/orbitdb/orbit-db-store/pull/85

they definitely need more feedback from @haadcode and @shamb0t before being considered

**Comment by vaultec81** [comment]
@tabcat Added! Additional review will be done before finalization. However, if your PRs get merged before this next version has been released they will be included either way.

**Comment by aphelionz** [comment]
Might be good to simply link to the project for the issues / PRs, but keep the administrative stuff here like the blog post, etc. That way we won't have to keep the project and the list here in sync

**Comment by vaultec81** [comment]
@aphelionz that sounds good. Definitely we should keep this format or a similar format when the release is published so people will know what has been changed, features, etc.

**Comment by aphelionz** [comment]
So to be clear my suggestion is to simply remove the checkboxes between "What's left for release" and "additional tasks" and keep everything else. That way, to your point, you can just copy and paste everything under "General bugfixes and updates" to the CHANGELOG

**Comment by aphelionz** [comment]
Release 0.24.0 is out... We need a changelog, a release, and a blog post!

**Comment by aphelionz** [comment]
We have a changelog, a release, and a blog post :)
