### ISSUE TITLE
Get length of the object index is a problem

### ISSUE THREAD

**Issue by kypanz** [orbitdb/orbit-db#773]
Hello all i have big problem i know a little solution to solved but i dont know if is the optimal

what i wanna do : unique key identifier

the problem : someone can rewrite the info

code example : 

```
/* Data Register  example */
const db = await orbitdb.docstore('myDB');
await db.load()
var count = Object.keys(db._index._index).length; // getting the max lenth of the object database
count += 1; // here add 1

await db.put({

      _id:''+count, // Problem here, because any time get the max length and add 1
      data : "my info data"

})
```

explained : 
- Example you have 100 data inserts in "myDB" , and 50 objects keys delete , when you wanna add another entry this gona be instert int 51 , but the problem is 51 really exist , and the problem of this is overwrites

more explained : 50 objects in left / 50 objects in right , if you every time insert you are getting the max of that objects and add "+1" , the problem come when you delete the 50 objects of the left , because if you wanna add another object this not gonna be 101 length , this gonna be 51 , and 51 exist, and there is overwrite :( , i dont tested but i thinking this gonna happend reading my code :(

my solution can be the next but really i dont wanna use this if anyone has another best solution, i really would aprecciate a lot : 

- my posible solution is before adding the count in the _id field i need check if that id exist , and there is another problem , because if exist i need to use a "bucle for" to check the max of length , and insert the data in the key thats no haves the correct id, in the empty id 

anyone know how to solve this problem ? i searching for automatic unique key but i dont finded

i am so sad for my code , because i think can be best :(

**Comment by aphelionz** [comment]
@kypanz Let's try something new, using codesandbox to figure out your issue: https://codesandbox.io/s/orbitdb-issue-773-i68s1. Feel free to make an account or fork.

**Comment by aphelionz** [comment]
Keep in mind that what you described, with the indexes increasing and not resetting if items are deleted is typically how SQL databases work if you don't re-index... you might want to keep the count calculation dynamic

**Comment by kypanz** [comment]
omg thats true , i think if i save that count in a database i can return the same value of count to the next insert

**Comment by aphelionz** [comment]
Yeah, i suppose it all depends on what your use case is! Are you ok with closing this issue then, or do you still need help?

**Comment by kypanz** [comment]
i think is solved , thanks a lot @aphelionz i really appreciate it

**Comment by aphelionz** [comment]
Any time!
