### ISSUE TITLE
Why i cant see my files in ipfs ?

### ISSUE THREAD

**Issue by kypanz** [orbitdb/orbit-db#777]
Hello, i have a question , why i cant see my files in ipfs ?

when i run the ipfs they return this in te console : 

```
Swarm listening on /ip4/192.168.56.1/tcp/4002/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd
Swarm listening on /ip4/192.168.0.2/tcp/4002/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd
Swarm listening on /p2p-circuit/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd
Swarm listening on /p2p-circuit/ip4/192.168.56.1/tcp/4002/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd
Swarm listening on /p2p-circuit/ip4/192.168.0.2/tcp/4002/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/4002/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd

```

but example , if i pick the first : 

`/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd`

and i wanna see in ipfs like this : 

`https://ipfs.io/ipfs/QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd`

i cant see the files, but dont show me error , only stay loading waiting the files

what i doing wrong ?

**Comment by aphelionz** [comment]
Ah, a couple things to clarify here:

When an IPFS node starts up and shows those messages int he console, `QmbgpyTLCYBy84E1HGwei6niQHiLQmRpfN6SQtfJiyNMUd` is your node id. Technically this is just a hash of your public key, not a file. So you wouldn't be able to see any content there.

From there, when objects are added to Orbit, they are added via the `dag` APIs, not `ipfs.add` for example. This means they won't be accessible via the HTTP gateway but they would be via `ipfs.dag.get` calls in JS code, for example.

**Comment by kypanz** [comment]
@aphelionz  thanks a lot for the answer , i do the next :

- save the result in a `variable` at the same time when i use `db.put` with orbit , like this : 

`var result = await db.put({ example : 'example content' });`

and you say that put is like a ipfs.dag.put ? , i dont know if i understand right

after that you are right i cant see in `http` gateway like : `ipfs.io/ipfs/ <myhash>`

but i can see the result of this in the IPLD : 

- https://explore.ipld.io/#/explore/zdpuAnhjYEo78eZuM52kFoLo8TbWBMKhGqU1cQtTAJEFqUW7F

- is not the example but i can see my results in side openning the object and go to object payload and see there

i think ipfs.dag.get is the same but in console, i dont know if i am right, i have a lot of questions but for now y really happy because i can see my object uploaded, now i go to learn more about ipfs , and what i do with orbitdb , i have a questions for the control access , i read de documentation and orbitdb says the only writer is the creator of the dabase , but i dont know , i go to learn more and try a lot of things

now i am training with protoschool tutorials trying to learn

thanks a lot for the answer i really aprecciate because i wanna learn and this help me a lot <3

**Comment by aphelionz** [comment]
Sure. I'm gonna close this for now but you can always ask more questions! Thanks for using OrbitDB!
