### ISSUE TITLE
OrbitDB browser/explorer

### ISSUE THREAD

**Issue by rigwild** [orbitdb/orbit-db#781]
Hi,

I searched if there was some kind of database browser/explorer that was available to see the content inside an OrbitDB database on an IPFS node but could not find one.

Does such a thing exists ? If not, it could be a really useful tool and help developers know if their code is working as expected.

I'm not sure if this is the right place for this type of request. You may move it to another repo.

thanks!

**Comment by phillmac** [comment]
Perhaps you could try the [Control Center](https://ipfs.io/ipfs/QmPoqRhSX2rMy6NR7Y3pnkC2z1kK9TH9fZa6wyfXLEptw9) 
the src code is here: [haadcode/orbit-db-control-center](https://github.com/haadcode/orbit-db-control-center)

**Comment by wallynm** [comment]
We could have this documented here into the repo? Never thought something like this was already built!

**Comment by aphelionz** [comment]
I think that's a good point. Happy to accept a PR @wallynm !

It can go in any/all of these places:
1. This README
2. The readme at https://github.com/orbitdb/welcome
3. https://github.com/orbitdb/field-manual
4. https://github.com/orbitdb/orbitdb.org

**Comment by aphelionz** [comment]
In fact, it might be good to have it at least linked to from https://orbitdb.org as a bit of a demo. What say you, @haadcode ? and if not, what needs to be added before we can?

**Comment by haadcode** [comment]
Fine by me to include where appropriate. Happy to also transfer the repo to orbitdb org if needed.

**Comment by aphelionz** [comment]
Sure, go ahead :) very exciting

**Comment by rigwild** [comment]
Seems dead ?

**Comment by aphelionz** [comment]
The repo was moved under the orbitdb org

**Comment by rigwild** [comment]
Did not see, https://github.com/orbitdb/orbit-db-control-center

Is it mentionned in website/reamde ?

**Comment by aphelionz** [comment]
Not yet but happy to accept a PR that adds it
