### ISSUE TITLE
Is orbit-db data same as ipfs data?

### ISSUE THREAD

**Issue by devanshusehgal** [orbitdb/orbit-db#787]
Is the orbit-db data distributed and hosted by my peers just like regular IPFS data? Or do the peers also need to have orbit-db installed?

**Comment by phillmac** [comment]
Orbit-db relies on IPFS dag entries to save the data. To stitch all the data back together into a useable database, you need orbit-db for sure

**Comment by devanshusehgal** [comment]
Like suppose if I have two applications.

App 1 is for nodes who are running ipfs and orbit-db. They can add data to the orbit-db database.
App 2 is for users who just want to read the data from orbit-db.

How do the users of App 2 read the data? Can they download the database from IPFS even if no orbit-db node is running and process it?

**Comment by phillmac** [comment]
You can read the raw data with `ipfs dag get<hash>` but for the data to have any meaning for App2 you should have an orbit-db node for it to read from. The raw data from IPFS does not function as a database, this is implemented only by orbit-db.

**Comment by devanshusehgal** [comment]
Is it possible to get orbit-db functionality without running a full node. Like can it be run in the browser if we only want read-only functionality.

**Comment by phillmac** [comment]
Yes, you can run orbit-db in the browser, e.g. https://github.com/orbitdb/orbit-db/tree/master/examples/browser

**Comment by devanshusehgal** [comment]
Thanks, that should do it for me.
