### ISSUE TITLE
Is orbit-db tamper proof and help reach consensus?

### ISSUE THREAD

**Issue by devanshusehgal** [orbitdb/orbit-db#788]
Can you pls answer some of my questions. oribit-db seems perfect but I'd like to confirm these things before using it for my application.

1) Can we be sure that database with a same name is not created twice?
2) Can we be sure that no node is tampering with the data?
3) Do we always get the latest data or sometimes some node can be out of sync and return old data?
4) Is orbit-db fully decentralised and running on IPFS without any central server?

**Comment by tabcat** [comment]
Ill try to answer these the best I can for now but no doubt someone else can likely answer these much better. Also feel free to check out the [OrbitDB gitter](https://gitter.im/orbitdb/Lobby) to chat with community members.

> 1. Can we be sure that database with a same name is not created twice?
Databases in OrbitDB have an immutable and deterministic address which depend on options set at creation of the database. The name of the database is one thing that affects this address but there are a couple others. If someone at creation of a database picks all the same options as someone else creating the same database they will end up with the same addresses. 

> 2. Can we be sure that no node is tampering with the data?
Nodes can only tamper with the data if the database controls say they can tamper with the data. All controls are enforced locally.

> 3. Do we always get the latest data or sometimes some node can be out of sync and return old data?
Nodes can be out of sync. Once they are able to sync again they will be able to return to a synchronized state no matter what was added while out of sync.

> 4. Is orbit-db fully decentralised and running on IPFS without any central server?
OrbitDB's architecture is decentralized as it doesn't specify or require designating a single node to decide what is added to the database. I don't know if I would say anything 'runs on' IPFS however OrbitDB utilizes an IPFS node to communicate and replicate databases.

**Comment by devanshusehgal** [comment]
@tabcat Thanks a lot for taking time to answer.

Like suppose if I have two applications.

App 1 is for nodes who are running ipfs and orbit-db. They can add data to the orbit-db database.
App 2 is for users who just want to read the data from orbit-db.

I want to use the *log* type database which is immutable. So, when the users of App 2 try to get data can they check somehow that they are reading the longest log?

**Comment by tabcat** [comment]
I believe the short answer is no, you can't know if you are reading the longest log.
