### ISSUE TITLE
Read Permission for table or row

### ISSUE THREAD

**Issue by am2222** [orbitdb/orbit-db#807]
Hi,
I am new with orbit-db. I was wondering if it is possible to give a table read-access to specific users? or even go further and give access per rows?

**Comment by phillmac** [comment]
By nature of the database structure the entire database is readable by anyone. If you want to implement 'table' or 'row' level read access control you need to look into either row or table level symetric encryption and controll acess via distribution of the encryption keys

**Comment by am2222** [comment]
Thanks for your reply. So in this case it is not possible to hide some rows
or a table from a user. Right? Since it is readable by all the network

**Comment by phillmac** [comment]
That's correct. You have tobresort to encryption to prevent read access to the data

**Comment by am2222** [comment]
@phillmac thanks!
