### ISSUE TITLE
Unable to write in any types

### ISSUE THREAD

**Issue by ialberquilla** [orbitdb/orbit-db#809]
Hi, 

I'm trying to create a database following the field-manual, but when I try to add data in any type of databases I'm always getting the error:
Error: Could not append entry, key "...790e06f" is not allowed to write to the log.
I was looking some old issues and my code looks like this solutions, but still fails

The databases are created as follow:

```
        this.node = await this.IPFS.create({
            preload: { enabled: false },
            repo: './ipfs',
            EXPERIMENTAL: { pubsub: true },
            config: {
                Bootstrap: [],
                Addresses: { Swarm: [] }
            }
        })
        this.orbitdb = await this.OrbitDB.createInstance(this.node)
        this.defaultOptions = { accessController: { type: 'ipfs', write: ['*'] } }
        const docStoreOptions = {
            ...this.defaultOptions
        }
        this.products = await this.orbitdb.keyvalue('products', docStoreOptions)
        this.steps = await this.orbitdb.eventlog('steps', docStoreOptions)
        await this.products.load()
        await this.steps.load()
```

And saving the data with this function:

```
    async addProduct(productId, product) {
        const hash = await this.products.put(productId, product)
        return hash
    }

    const hash = await orbit.addProduct(1, {
        property1: 1,
        property2: 2,
        property3: 3,
        property4: 4,
    })
```

Database is created but always gives the same error on save data.

Im using     "ipfs": "^0.47.0" and  "orbit-db": "^0.24.2" versions.

Thanks

**Comment by tabcat** [comment]
Hi @ialberquilla, this is a bug documented in here: https://github.com/orbitdb/orbit-db-keystore/issues/45 .
It will say how you can patch this manually until a new version is released.

**Comment by ialberquilla** [comment]
Thanks @tabcat I changed the secp256k1 version on my project to 3.8.0, and added as dependency and It's working now.
Thanks!

**Comment by geolffreym** [comment]
downgrade ipfs@0.46.0 @ialberquilla https://github.com/orbitdb/orbit-db/issues/813

**Comment by tabcat** [comment]
hi again @ialberquilla :wave: is this resolved?

**Comment by ialberquilla** [comment]
hey @tabcat, yes it's resolved
