### ISSUE TITLE
0.47 Compatibility NOT READY YET!

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbit-db#813]
Sorry for the loud pin, but just want to make sure people know that we are working on the issues with js-ipfs@0.47 compatibility. Some of them are on us, others are with js-ipfs.

In the meantime, please downgrade to 0.46 or 0.45

**Comment by geolffreym** [comment]
Cool!!

**Comment by geolffreym** [comment]
@achingbrain where can i see the roadmap to js-ipfs@0.47?

**Comment by achingbrain** [comment]
@geolffreym it’s here: https://github.com/orgs/ipfs/projects/6

**Comment by geolffreym** [comment]
@aphelionz where can i see the roadmap for orbit?

**Comment by phillmac** [comment]
@geolffreym
https://github.com/orgs/orbitdb/projects/3

**Comment by aphelionz** [comment]
Thanks @phillmac. Not only that but we'll be posting a more extensive roadmap for OrbitDB 2020 -> 2021 either this week or the next.

**Comment by jacobheun** [comment]
Just a heads up with SECIO support removal planned for later this month we're going to look at patching js-ipfs 0.46 to include support for Noise to give more time to upgrade here.

**Comment by geolffreym** [comment]
@jacobheun which version of js-ipfs removes SECIO support? 0.47.2? I am currently using 0.47.1 with orbit.. working fin so far..

**Comment by jacobheun** [comment]
Tentatively slated for 0.50 later this month. We're currently on 0.48. 0.47 supports Noise as a fallback so you'll still be able to connect, it will just cause a roundtrip hit when establishing a new connection.

**Comment by geolffreym** [comment]
Ohhh sorry, yep 0.48.1 that's what i tried to say.. ok cool, will be ready to test new version!! thanks @jacobheun

**Comment by geolffreym** [comment]
This is just if i am using IPFS default settings right? Can i can keep using SECIO or NOISE in my custom libp2p settings?

**Comment by jacobheun** [comment]
> Is this only if i am using IPFS default settings right? Can i can keep using SECIO or NOISE in my custom libp2p settings?

Yes to both. After 0.50 you'll need to be sure to require SECIO in your dependencies list as well.

**Comment by aphelionz** [comment]
All set! @jacobheun ready and waiting for 0.50 :)
