### ISSUE TITLE
OrbitDB - Ipfs is not defined Examples Browser

### ISSUE THREAD

**Issue by locoalien** [orbitdb/orbit-db#816]
I have had problems in the last days, to run the OrbitDB examples.

The problem that appears in the web browser is the following:

`Uncaught ReferenceError: Ipfs is not defined`

Specifically in the file "example.js"
`// Create IPFS instance
  const ipfs = new Ipfs({
    repo: '/orbitdb/examples/browser/new/ipfs/0.33.1',
    start: true,
    preload: { 
      enabled: false
    },
    EXPERIMENTAL: {
      pubsub: true,
    },
    config: {
      Addresses: {
        Swarm: [
          // Use IPFS dev signal server
          // '/dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star',
          '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star',
          // Use local signal server
          // '/ip4/0.0.0.0/tcp/9090/wss/p2p-webrtc-star',
        ]
      },
    }
  })
`

You can see the problem in the following image:
<img width="1016" alt="orbitdb" src="https://user-images.githubusercontent.com/1004466/87183947-b4b2c680-c2ac-11ea-8b8c-58774cfe07e8.png">

The problem is due to the fact that there is a new version of the IPFS library, therefore the way to create the IPFS class instance has changed.

**Solution:**

To solve the problem, the example has been modified to be able to run the program correctly in the browser.

To solve the problem it is necessary to follow the following steps:
1)Modify the file "browser.html", with the dependencies in the correct path.
Before:
<img width="819" alt="before" src="https://user-images.githubusercontent.com/1004466/87184320-69e57e80-c2ad-11ea-9b06-772bff389b58.png">
After:
<img width="835" alt="after" src="https://user-images.githubusercontent.com/1004466/87184402-8ed9f180-c2ad-11ea-9018-be96c44d7c74.png">

2) The file "example.js" should be modified, with the new form of the latest version of IPFS.

Before:
<img width="639" alt="1before" src="https://user-images.githubusercontent.com/1004466/87184541-d1033300-c2ad-11ea-9bd0-0fba4f62b4c1.png">
After:
<img width="578" alt="2after" src="https://user-images.githubusercontent.com/1004466/87185119-d1e89480-c2ae-11ea-8794-8993f3fae3a4.png">
Once the previous steps have been carried out, we can now correctly run the example with the latest version of IPFS.
<img width="897" alt="finish" src="https://user-images.githubusercontent.com/1004466/87185197-f8a6cb00-c2ae-11ea-9f47-d836a53d2cb0.png">
Have a nice day :)

**Comment by aphelionz** [comment]
I believe this can be closed
