### ISSUE TITLE
Migration when in production

### ISSUE THREAD

**Issue by wagner-daniel** [orbitdb/orbit-db#826]
Hello,

in the roadmap to version 1.0 there is a statement that backwards compatibility may be abandoned. Because of the decentralized nature of the project, developers of application cannot migrate the data to a newer version.

One scenario to handle this is enabling a upgrade function for every user to migrate their data. But this only works in cases where users don´t interact with each other. For instance user A, B and C have created their profile with version 0.x and their client uses v0.x at the moment. User A updates the client and migrates the profile. When user A visits the profile of user B or C it may not work. (Correct me if this is wrong). On the other hand user b or c cannot view profile of user A.

I can image a solution where different orbitdb version run at the same time, but it may not be possible and if it is, more javascript needs to be loaded and processed, which is a problem on low end devices and puts decentralized apps at a even higher disadvantage against centralized competitors.

I know that breaking changes are always coming as the tech progresses, but I think that normal users wont accept those splits occurring in the community with major version upgrades. Do you have had any thoughts on this before? This problem should be tackled as early as possible to not scare developers and make users of dapps switch back to centralized alternatives after they experienced such issues.

As I am developing a project with orbitdb I am willing to help finding a solution to this problem, but I only have partial understanding of your project at the moment.

Greetings

Daniel

**Comment by aphelionz** [comment]
Hi Daniel, thanks for raising this concern. tl;dr - we have no intention of leaving our users (and their users) high and dry

In the past we've been _aggressively_ dedicated to backwards compatibility: 

1. The log entries are [versioned](https://github.com/orbitdb/ipfs-log/issues/211) so we know how to process them
2. [Automated tests](https://github.com/orbitdb/orbit-db/blob/master/test/v0-open-load.js) check for them and the corresponding mitigation
3. There are [automatic migrations](https://github.com/orbitdb/orbit-db/blob/master/src/migrations/0.21-0.22.js) that run if certain conditions are detected

I don't see why we wouldn't continue these and similar practices, at least not without having a valid migration path. The language in the roadmap is to be taken seriously, but it's also there as a distant early warning for folks that big changes could be coming coming. We just don't want to hinder progress by having to do a ton of extra work to support backwards compatibility if we may not have to.

All that said, welcome and we hope you have more valuable input as things move forward!

**Comment by wagner-daniel** [comment]
This sounds great! Cant wait to benefit from all the changes that come with version 1.0.
