### ISSUE TITLE
(question) What size can my database be?

### ISSUE THREAD

**Issue by arthur-fontaine** [orbitdb/orbit-db#827]
Hi!

I wonder if the size of the database is unlimited (if it is based on many devices in the world) or if it only depends on my device and those that have connected using the address of my database?
I couldn't find any information about it.

**Comment by Pluto1010** [comment]
+1

**Comment by Lazerbeak12345** [comment]
I would assume it's closely related to the IPFS max file size, but I don't think there is one, or if it is, it's truly huge.

**Comment by aphelionz** [comment]
It would be related to the max size enforced by bitswap mostly, but that's still by _log entry_ and not by the database itself. Each entry is a different IPFS CID. Currently the biggest constraint on db size is RAM since the DB is loaded into memory.
