### ISSUE TITLE
online demos broken

### ISSUE THREAD

**Issue by fdietze** [orbitdb/orbit-db#828]
## Live Demo 1: 
https://ipfs.io/ipfs/QmeESXh9wPib8Xz7hdRzHuYLDuEUgkYTSuujZ2phQfvznQ/

Connecting to a remote database doesn't work. It says  `Connecting to peers...` forever.

## TodoMVC: 
https://ipfs.io/ipfs/QmTJGHccriUtq3qf3bvAQUcDUHnBbHNJG2x2FYwYUecN43/

```
WebSocket connection to 'wss://star-signal.cloud.ipfs.team/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 502
```

**Comment by aphelionz** [comment]
Thanks for calling our attention to this. They sunsetted the star servers so we'll need to replace those with newer multiarrs

**Comment by aphelionz** [comment]
I believe this has been resolved
