### ISSUE TITLE
a 3Box SDK  bug because OrbitDB

### ISSUE THREAD

**Issue by aturX** [orbitdb/orbit-db#830]
"Error: Could not append entry, key "did:3:bafyreig4trqtifolb3mw7b6elt5butfb23gj2n6dugtjm2gwt63s..." is not allowed to write to the log"

I have same problem , I can read data from 3box, but can't change or add new data into.

**Comment by aphelionz** [comment]
@aturX What version(s) of orbit-db and ipfs are you using?

**Comment by aphelionz** [comment]
@tabcat is this related to the secp256k1 bug?

**Comment by aphelionz** [comment]
@oed @zachferland looking into this now, any suggestions are welcome

**Comment by tabcat** [comment]
@aphelionz yes i would be surprised if this was related to https://github.com/orbitdb/orbit-db-keystore/issues/45

**Comment by aphelionz** [comment]
That's what I was thinking too... can we get a PR in?

**Comment by aphelionz** [comment]
Nevermind about the PR..

@aturX Can you give me the output of `npm ls orbit-db-keystore`?

**Comment by aturX** [comment]
<img width="394" alt="77b20ba0a7df94cdafb6f9fdd682a62" src="https://user-images.githubusercontent.com/34887700/91008977-1b4c3380-e612-11ea-94be-0c75ec8c454b.png">


Sure, This is result. 
```
PS D:\app\Ldata\VUE\ant-cave> npm ls orbit-db-keystore
ant@0.1.0 D:\app\Ldata\VUE\ant-cave
`-- 3box@1.21.0
  +-- orbit-db@0.24.2
  | `-- orbit-db-keystore@0.3.5
  `-- orbit-db-identity-provider@0.3.1
    `-- orbit-db-keystore@0.3.5  deduped
```
@aphelionz

**Comment by aphelionz** [comment]
Hmm, ok. We just released OrbitDB 0.25.0, maybe that will help. 

In the meantime, can you package up some code, either on codesandbox or in a git repo so I can reproduce and experiment?

**Comment by aturX** [comment]
[I use it here](https://github.com/SusuwatariCoder/SusuwatariCoder.github.io/blob/master/src/views/demo/3box/index.vue)

I maybe not useful, I am trying it to make sure that  if I should  update `3box` 's  package because it is now still 0.24.2 .


now it is..
```
+-- 3box@1.21.0
| `-- orbit-db-identity-provider@0.3.1
|   `-- orbit-db-keystore@0.3.5
+-- orbit-db@0.25.1
| `-- orbit-db-keystore@0.3.4  deduped
`-- orbit-db-keystore@0.3.4
```

**Comment by aphelionz** [comment]
Is this resolved from the update to 0.25.1?

**Comment by aturX** [comment]
@aphelionz    Thanks!   Problem solved. It worked 
gooood!

**Comment by aphelionz** [comment]
Glad to hear. Closing this but don't hesitate to reach back out.
