### ISSUE TITLE
unable to add localy and retrieve remote 

### ISSUE THREAD

**Issue by zoernert** [orbitdb/orbit-db#841]
After sorting out some issues with pubsub, swarm etc... I am able to "see" databases I've created using Control Center:

Like:
/orbitdb/zdpuAkZqauK6eJyKpsL1e5z5pJwVJHvTpMZJxAtvAzSLR3LYF/casa-corrently-beta

It shows the right meta data (storage type)  - however the items are always 0. Same in my code if I request (open) a database remotely I get an item count of 0 back. 

Does anybody have a hint where to continue debugging?

 -  "ipfs": - "^0.50.2"
 - "orbit-db": "^0.26.0"

And yes I am aware of the version dependency and official support of <=0.46 ipfs - I've tested with downgrades already.

**Comment by aphelionz** [comment]
Hi @zoernert thanks for opening the issue. A couple exploratory questions first

1. Are you using the in-browser node or are you connecting to a js-ipfs node on your machine?
2. Relatedly, when you say you're able to "see" databases do you mean just in the UI, or from another IPFS node?

**Comment by zoernert** [comment]
1. for publishing (adding) I am using node and start js-ipfs as a module (which works find for pubsub and orther ipfs related operations)
2. in the UI they get added as soon as a new entry got added.

With the above mentioned versions doing on my local machine (that adds data) after db ready event:
```javascript
const items = db.iterator().collect().map(e => e.payload.value)
        console.log("Local DB Ready:",items.length);
```

always brings a "1" after first  `.add(item)` and does not increase (i am using feed storage)

**Comment by aphelionz** [comment]
Thanks - I think it's because it needs an upgrade to the WebRTC star servers. Do me a favor and try this branch? https://github.com/orbitdb/orbit-db-control-center/pull/4

If it works for you I'll be happy to merge it.

**Comment by zoernert** [comment]
Using the branch I could now see the permissions hash - but still 0 entries. One thing that I will try is to manually add the star server from https://github.com/orbitdb/orbit-db-control-center/blob/master/src/config/index.js to my script and see if it works.

**Comment by aphelionz** [comment]
How'd it go? :)

**Comment by zoernert** [comment]
My first CI failed on a public server - however I wanted to double check later today if everything is configured as required and no firewall etc.. .blocks.

**Comment by aphelionz** [comment]
Cool, take your time

**Comment by zoernert** [comment]
So all my checks failed. What I will do is create a private module that just has and orbitdb with some randomly added values on one server and a second module as "listener" to debug the issue. Hope that helps.

**Comment by aphelionz** [comment]
May I see the IPFS configs for both IPFS nodes you're trying to connect? And whether or not they are browser, node.js, or go?

**Comment by zoernert** [comment]
#Baehmmm 

I think I found the issue - it is my architecture! In order to have a bit of stability in my pubsub communication I am using go ipfs on the "servers" and node js on the "clients" - however pubsub of ipfs does not relay topics if one node is not subscribed to. My channel event messaging worked perfect as the "servers" are subscribed to that topics. However for the orbitdb they are not ... so they will forward a message from Client A via Server B to Client C.

**Comment by aphelionz** [comment]
Ah, you can turn on circuit relay and hop in your go-ipfs config as well! 

https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#autorelay

**Comment by zoernert** [comment]
Issue might be closed. It works from my scripts - however not within my browser version (eq. [Control Center](https://ipfs.io/ipfs/QmPoqRhSX2rMy6NR7Y3pnkC2z1kK9TH9fZa6wyfXLEptw9/)). I've upgraded my go-ipfs to latest version and figured out that always the first iterator call ends with "0" items - however polling it from time to time brings up results.
