### ISSUE TITLE
update GUIDE.md, permission denied

### ISSUE THREAD

**Issue by simonbonnefoy** [orbitdb/orbit-db#847]
Hi, 
I submitted this PR a few days ago https://github.com/orbitdb/orbit-db/issues/846
Since the Doc was outdated, I have updated the GUIDE.md, with my modifications for the examples to work. 
I have no permission to create a branch on the repo for my modifications. Is it possible to get access?
Or should I send my updated GUIDE.md file to someone?

cheers

**Comment by aphelionz** [comment]
Hi @simonbonnefoy You can create a fork of orbit-db and make a PR from there.

**Comment by simonbonnefoy** [comment]
Hi @aphelionz , 
Thanks! I have submitted a PR with the modifications.
