### ISSUE TITLE
Open existed db

### ISSUE THREAD

**Issue by weishancc** [orbitdb/orbit-db#851]
Hi everyone,

Im trying to create a key-value db with `setup.js` then loading it with` interact.js` whereas I still can't get the existed data (key1:value1). Could you please help with me? Thanks!

**setup.js**
```console
  1 const IPFS = require('ipfs')
  2 const OrbitDB = require('orbit-db')
  3
  4 async function main () {
  5   // Create IPFS instance
  6   const ipfsOptions = { repo : './ipfs', };
  7   const ipfs = await IPFS.create(ipfsOptions);
  8
  9   // Create OrbitDB instance
 10   const orbitdb = await OrbitDB.createInstance(ipfs);
 11
 12   // Create database instance
 13   const db = await orbitdb.keyvalue('firstdb');
 14   const hash = await db.put('key1', 'value1', { pin: true });
 15   console.log(hash);
 16   console.log(db.address.toString());
 17 }
 18
 19 main()
```

**interact.js**
```console
  1 const OrbitDB = require('orbit-db')
  2 const IPFS = require('ipfs')
  3
  4 async function main() {
  5
  6     const ipfsOptions = { repo : './ipfs', };
  7     const ipfs = await IPFS.create(ipfsOptions);
  8     const orbitdb = await OrbitDB.createInstance(ipfs);
  9     //const db = await orbitdb.keyvalue('firstdb');
 10
 11     const db = await orbitdb.open('/orbitdb/zdpuAoDkS3Visgws6Eu1VEhFFqhPBxCJx1AbS7cEH9EKT35SQ/firstdb');
 12
 13     console.log(db.all);
 14
 15     await orbitdb.disconnect();
 16 }
 17
 18 main()
```

**Comment by aphelionz** [comment]
Hey there, thanks for opening an issue :)

Try putting `await db.load()` on line 12 of interact.js?

**Comment by weishancc** [comment]
Thanks for the prompt reply. It works!

Just one more question, if I created db like `setup.js`, is it open to public by default? (i.e., under the premise that didn't set permission)

**Comment by aphelionz** [comment]
Everything is always going to be public read-only due to the nature of IPFS. You can set up a private IPFS cluster (which kinda defeats the purpose imo) or you can use encryption for your payloads.

Write permissions are by-default enabled only for the creator of the database, but you can use `write: ['*']` to enable all writers if you want.
