### ISSUE TITLE
Missing dist folder '../../dist/orbitdb.js' ?

### ISSUE THREAD

**Issue by neosin** [orbitdb/orbit-db#862]
trying to follow the browser example and it shows the orbitdb,js file is in the subsub dist folder but this folder is missing as part of the orbitdb project...

https://github.com/orbitdb/orbit-db/blob/master/examples/browser/browser.html

is there somewhere I can download orbitdb.js ?

**Comment by tabcat** [comment]
please run `npm run build` which should create the needed files.
https://github.com/orbitdb/orbit-db/blob/52d68cd690aaa800430200db48a935d8af693e8e/package.json#L81

**Comment by neosin** [comment]
I am not using node, is there a built version somewhere?

**Comment by tabcat** [comment]
http://ipfs.io/ipfs/QmanAYDoi8UVk2SN85KQAkguoYvGEESwJqTBdEx5iyTLvY/

**Comment by neosin** [comment]
works 100% tyvm
