### ISSUE TITLE
Discord invite has expired.

### ISSUE THREAD

**Issue by digitalextremist** [orbitdb/orbit-db#867]
The `README.md` invite link to `Discord` has expired, and needs to be updated.

**Comment by RichardLitt** [comment]
The discord was owned by PL, and was either taken over or removed. We currently don't have a discord.

How do we feel about just removing discord everywhere, since it isn't being used and Gitter works for our purposes?

**Comment by aphelionz** [comment]
Yes and now that Gitter speaks matrix we get two for one :)

**Comment by RichardLitt** [comment]
I wasn't happy with these old links existing. There.

**Comment by phillmac** [comment]
Holy pr spam, Batman! 😜

**Comment by RichardLitt** [comment]
Haha I'm sorry. It had to happen, though.
