### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbit-db#870]
This is happening across GitHub, and it's more inclusive.

For more, see https://github.com/github/renaming.

**Comment by CSDUMMI** [comment]
I don't know?
Is it really?

**Comment by aphelionz** [comment]
It is what it is. I'm happy with either but don't have the time to make the change on 20+ repos. Happy to work with somebody that does.

**Comment by tabcat** [comment]
the [symbolism] behind it is why i didnt want to touch it :grimacing: @CSDUMMI

**Comment by aphelionz** [comment]
Yeah, one thing I _don't_ want this thread to turn into is another one of these extremely well-worn debates about "politics." 

So again, if somebody feels like taking the time to change it in all the repos, please feel free. Otherwise let's just leave well enough alone.

**Comment by RichardLitt** [comment]
@CSDUMMI writes: "is it really?"

Yes. [Here's a good write up](https://www.drupal.org/project/drupal/issues/2275877#comment-8831441) on the thinking. 

I'm sorry, I strongly disagree with the sentiment of "leave well enough alone."

From our Code of Conduct, one of our goals is: 

> Being respectful of differing viewpoints and experiences

From Software Conservancy, linked in the link I dropped in the initial comment: 

> Both Conservancy and the Git project are aware that the initial branch name, ‘master’, is offensive to some people and we empathize with those hurt by the use of that term.

I think that not changing the name of the branch is orthogonal to our community values. Granted, I don't code here nearly as much as I used to. 

@aphelionz You should be able to run [this script](https://github.com/octoherd/script-rename-master-branch-to-main) to rename them in all repos, as you have access to most of them. I might, too. Let me know if you want me to try.

**Comment by aphelionz** [comment]
> I'm sorry, I strongly disagree with the sentiment of "leave well enough alone."

My sentiment isn't "leave well enough alone," it's that I don't want a big drawn out debate on this full of galaxy-brain takes of all shapes and sizes about this in this repo as it has all over GitHub.

I meant what I said - if you want to run the script, go for it. It's simple enough for local devs to switch over to main, 1 (maybe 2) commands and carry on.

**Comment by RichardLitt** [comment]
This has been done for all orbitdb repos.

**Comment by aphelionz** [comment]
Great, thanks for taking the initiative.
