### ISSUE TITLE
Best practices for security concepts available?

### ISSUE THREAD

**Issue by s-a** [orbitdb/orbit-db#871]
I discover this technologie but wonder how to protect database against hackin. If it s deploeyed on several systems should be easy to manipulate data for replication right ? Can some one explain or point me to the right docs? What I need is some kind of permission logic in terms of who can change what and when and where :) . Thanks in advance. Pretty impressive repository here. Amazing.

**Comment by tabcat** [comment]
Hello @s-a,

 > If it s deploeyed on several systems should be easy to manipulate data for replication right ? What I need is some kind of permission logic in terms of who can change what and when and where :)
 
The security measures are roughly as follows:

Replicas are stored locally and can be manipulated by the machine. However correctly operating, machines will look at entries delivered by remote machines before adding them to their replica. These checks include 1) the entry data matches the hash used to fetch the data (this is done by ipfs) 2) the entry belongs to that replica 3) the entry is valid and contains a valid signature 4) the key that made the signature has permission to add entries to the replica.

At a high level I believe that covers everything but there may be something I'm missing in the moment.

**Comment by CSDUMMI** [comment]
These security considerations are okay for some projects, but we will need a more complex access permissions.

**Comment by CSDUMMI** [comment]
@tabcat 
> Replicas are stored locally and can be manipulated by the machine. However correctly operating, machines will look at entries delivered by remote machines before adding them to their replica. These checks include 1) the entry data matches the hash used to fetch the data (this is done by ipfs) 2) the entry belongs to that replica 3) the entry is valid and contains a valid signature 4) the key that made the signature has permission to add entries to the replica.

Is it valid to summerize this as follows: "If an honest node operates honestly and correctly, it's database will be correct, regardless of the number of bad actors in the system."?

**Comment by aphelionz** [comment]
Can this be closed?

**Comment by CSDUMMI** [comment]
I think so.

**Comment by CSDUMMI** [comment]
I would think that this should be closed by now.

**Comment by aphelionz** [comment]
Thanks for the heads up :)
