### ISSUE TITLE
TodoMVC edit does not work

### ISSUE THREAD

**Issue by chrisamow** [orbitdb/orbit-db#876]
Maybe just demo maintenance(?)

There doesn't seem to be a way to complete Editing a previously created todo 
and in the console I'm seeing:

Firefox can’t establish a connection to the server at ws://127.0.0.1:8081/p2p/QmV7gnbW5VTcJ3oyM2Xk1rdFBJ3kTkvxc87UFGsun29STS. ipfs.min.js:2:1310596
Firefox can’t establish a connection to the server at ws://127.0.0.1:8081/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN. ipfs.min.js:2:1310596
TypeError: e[r] is undefined

**Comment by tabcat** [comment]
those errors can be ignored.
not sure how but i can confirm its broken.
also seems like firefox has a really hard time peering and for some reason.

**Comment by tabcat** [comment]
ok now its working really well again so this is very odd.

**Comment by tabcat** [comment]
Ok so it seems like for some reason the links to the live demo are wrong.

the link in the [example's repo readme](https://github.com/orbitdb/example-orbitdb-todomvc) is correct but im guessing everywhere else is incorrect. i have no idea how this happened but its my fault.

here is the link correct link you can try: https://ipfs.io/ipfs/QmdapauyBinux52DUCfhRV44FTWmg6i1krvhQtKDEDWCPZ/#/
and thanks for making this issue @chrisamow :+1:

**Comment by chrisamow** [comment]
@tabcat - thanks, just verified it - looks good - great work on the project!
I hope to figure out how to orbitdb power some stuff - it looks exciting!
