### ISSUE TITLE
Cannot write to a Public Database

### ISSUE THREAD

**Issue by CSDUMMI** [orbitdb/orbit-db#878]
The source code for this is this: https://gitlab.com/-/snippets/2105561#LC17

It creates a Feed database with `accessControl.write = ["*"]`.

But when I try to add something to the database, I am getting this error:
```
Error: Could not append entry, key "03394dadc11a7291dcedda7806f5caf90bc75c39ba80c4496cb92f07a0e0881c3c" is not allowed to write to the log
```

Do you have the same issue? Have I made a mistake?

**Comment by tabcat** [comment]
Hi @CSDUMMI ,
> It creates a Feed database with accessControl.write = ["*"].

the option should be `accessController.write` which is what you have in your sample so that should not be the issue. i will try to find what the issue is, thanks for the code sample.

**Comment by CSDUMMI** [comment]
I know used a different Nodejs installation and it appears to work.
