### ISSUE TITLE
Coding Style - Avoiding nested ternary operators

### ISSUE THREAD

**Issue by CSDUMMI** [orbitdb/orbit-db#890]
I have now read the source code of orbit-db in separate places. 

And have seen in at least two places now ([EventStore](https://github.com/orbitdb/orbit-db-eventstore/pull/38) and [DocStore](https://github.com/orbitdb/orbit-db-docstore/blob/e23b3c7b9d71759a2627a561a9b1366f88e93698/src/DocumentIndex.js#L9)) I have 
seen a syntax structure, that I think is very unreadable:

Nested ternary operators: 
```js
  get (key, fullOp = false) {
    return fullOp
      ? this._index[key]
      : this._index[key] ? this._index[key].payload.value : null
  }
```

This is very unreadable in my opinion.
I think it will be more understandable to use explicit if statements
and rewrite the example above like this:

```js
get(key, fullOp = false) {
    if(fullOp) {
         return this._index[key
    else if(this._index[key]) {
          return this._index[key].payload.value
   else {
          return null
   }
```

Because, although this requires more lines and characters, it is more understandable.
I propose, that these nested ternary operators and avoid them in the future for
readablility.

**Comment by zcstarr** [comment]
lolz throwing my hat in the ring for that suggested rewrite to be 
```js
get(key, fullOp = false) {
    const index = this._index[key];
    
    if(fullOp) return index;
    if(index) return  index.payload.value
    return null
}
```

**Comment by aphelionz** [comment]
branchless and succinct, very nice!

**Comment by tabcat** [comment]
for me the OP recommended rewrite is the least readable of the three so far (may have to do with the uneven indentation)

personally dont have a problem at all with nested ternaries (when its only nested once) and seems more case by case.
