### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by christroutner** [orbitdb/orbit-db#908]
My app using OrbitDB spins up several instances of OrbitDB and is consistently displaying this error message as a result:

`(node:27273) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 replicate.progress listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit`

I understand that each instance of an OrbitDB has an EventEmitter, so this is expected.

**My question**: Is there a way to pass a value at instantiation to set the `setMaxListeners()` value?

When using EventEmitter in my own applications, I can avoid the error message by setting something like `emitter.setMaxListeners(50)`. However, that must be done for each instance of the EventEmitter. I'm not aware of a way to apply it globally to all instances of the EventEmitter within an app.

It would be *really* nice if OrbitDB had a config value that could be passed at instantiation that would get passed on to each instance of EventEmitter.

**Comment by phillmac** [comment]
In the http api server I did something like this:
```
require('events').EventEmitter.defaultMaxListeners = 50 // Set warning higher then normal to handle many clients
```

**Comment by christroutner** [comment]
Great idea. Thanks @phillmac!

**Comment by awcchungster** [comment]
I ran into this issue too. @phillmac 's suggested fix worked.
