### ISSUE TITLE
go-ipfs 0.10.0 support

### ISSUE THREAD

**Issue by tabcat** [orbitdb/orbit-db#909]
Issue to track support for go-ipfs 0.10.0

#### Tests run and pass:
_using go-ipfs@0.10.0-rc1 via ipfs-http-client_
- [x] orbit-db
- [x] orbit-db-store
- [x] orbit-db-io@next
- [x] ipfs-log

**Comment by tabcat** [comment]
the main package is passing. its using older versions of the other listed packages which are all failing after installing `go-ipfs@next`. the orbit-db-io test errors are concerning;
```js
  3) IO tests (go-ipfs)
       dag-cbor
         writes with links:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'zdpuAsrQMsQKMnCSv2bLU5scjbydUBQs8KCKCJ84DQVPXqT1Y'
- 'zdpuAqeyAtvp1ACxnWZLPW9qMEN5rJCD9N3vjUbMs4AAodTdz'
        ^
      + expected - actual

      -zdpuAsrQMsQKMnCSv2bLU5scjbydUBQs8KCKCJ84DQVPXqT1Y
      +zdpuAqeyAtvp1ACxnWZLPW9qMEN5rJCD9N3vjUbMs4AAodTdz

```
```js
  9) IO tests (go-ipfs)
       raw
         reads:
     AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ Uint8Array(13) [
+   161,
+   100,
+   116,
+   101,
+   115,
+   116,
+   102,
+   111,
+   98,
+   106,
+   101,
+   99,
+   116
+ ]
- {
-   test: 'object'
- }
```
all tests fail and the code returns differing cids than before.

**Comment by tabcat** [comment]
these issues seem to be stemming from the ipfs-http-client. the latest commits tests are failing after install the rc.

```js
  ipfs-http-client constructor tests

...

  .dag
    1) should be able to put and get a DAG node with format dag-pb
    2) should be able to put and get a DAG node with format dag-cbor
    ✔ should be able to put and get a DAG node with format raw
    ✔ should error when missing DAG resolver for multicodec from requested CID
    ✔ should error when putting node with esoteric format
    3) should attempt to load an unsupported format
    4) should allow formats to be specified without overwriting others

```

**Comment by tabcat** [comment]
scoping use of the block api exclusively as a work around and improvement of how everything is used currently for us. the block api doesnt seem to be broken by the ipfs-http-client + go-ipfs rc. encoding data ourselves using the same packages actually seems like it could be cleaner and allows us to get the cid sooner.

**Comment by tabcat** [comment]
the main package was never actually passing because orbit-db-test-utils was using its own ipfs deps. ive updated that and other packages and most everything is passing now with go-ipfs@0.10.0.rc1 and the latest js-ipfs. we have some tests that have always been a bit flaky that arent passing but that is all.

**Comment by rvagg** [comment]
Hey @tabcat, can you give us a little more info about the failure you experienced here, the red flags for us from changed CIDs warrants a little more investigation to make sure that we've not introduced something wonky on our end.

Is https://github.com/orbitdb/orbit-db-io/pull/26 addressing the main problem? And therefore the source of the issue is:

> supplying write with a 'raw' format param would result in ipfs.dag defaulting to encoding the data with dag-cbor

So by upgrading, you were suddenly _actually_ using raw but were previously using dag-cbor? In this thread I'm only seeing dag-cbor CIDs though: `zdpuAsrQMsQKMnCSv2bLU5scjbydUBQs8KCKCJ84DQVPXqT1Y`, `zdpuAqeyAtvp1ACxnWZLPW9qMEN5rJCD9N3vjUbMs4AAodTdz` and the two `bafyrei` CIDs in the second failed test in the screenshot are all dag-cbor. Is there something we can help investigate here?

**Comment by tabcat** [comment]
Hi @rvagg, I didn't investigate that well enough to be sure before switching to the block api. I believe the default is still dag-cbor; the dag api when used with the latest ipfs-http-client [seems to be in a broken state currently](https://github.com/orbitdb/orbit-db/issues/909#issuecomment-912100326) due to the failed tests i ran after installing the go rc.

I haven't opened an issue on in js-ipfs yet so if you dont want to switch to the block api i would suggest doing that.

**Comment by tabcat** [comment]
@rvagg the [`ipfs-http-client`'s dag api tests fail](https://github.com/orbitdb/orbit-db/issues/909#issuecomment-912100326) with `go-ipfs@next`. If you clone the js-ipfs repo and run the ipfs-http-client packages test with go-ipfs@next installed to the devDependencies you should see the dag api tests fail as shown above.

**Comment by tabcat** [comment]
Closed by: https://github.com/orbitdb/orbit-db/pull/912
