### ISSUE TITLE
Releasing version 0.27 - latest js/go ipfs support

### ISSUE THREAD

**Issue by tabcat** [orbitdb/orbit-db#913]
A new version of orbit-db will be released with support for the latest go and js ipfs implementations, v0.10 and v0.58 respectively. Expect a version of orbit-db to be published under the next tag soon, and a new latest to be published after some of the issues below are handled.

- fix failing replication event tests in `test/replicate.test.js`
- fix browser concurrent writes test

PRs:
- https://github.com/orbitdb/orbit-db/pull/912
- https://github.com/orbitdb/orbit-db-store/pull/116
- https://github.com/orbitdb/ipfs-log/pull/337
- https://github.com/orbitdb/orbit-db-access-controllers/pull/64
- https://github.com/orbitdb/orbit-db-io/pull/26
- https://github.com/orbitdb/orbit-db-test-utils/pull/42

PRs need to be published in reverse order that they are listed above, and replacing github deps with the published versions.

**Comment by tabcat** [comment]
the issue with the browser tests for orbit-db failing have to do with the CID instance not being the same for orbit-db and ipfs. since they are bundled separately the instance is not shared and ipfs tests whether the cid provided is a cid using the `instanceof` token.

**Comment by tabcat** [comment]
currently stuck on `orbit-db-io`. moving to the block api works perfectly but incurs some performance hit so I will be making the small changes need to move back to the dag api. the dag api isn't working as perfectly as the block api for some reason, it seems like there is an issue with advertising cids for data that has been uploaded using the dag api. the cids are identical but requesting them from peers that uploaded them isnt resolving in tests. i'm going to look at the ipfs change logs for clues and try to isolate the behavior to open an issue if needed.
after this is taken care of all that i believe is needed for passing tests would be to move the `orbit-db-access-controller` tests to the main repo.

**Comment by tabcat** [comment]
[version 0.27](https://www.npmjs.com/package/orbit-db/v/0.27.1) published

**Comment by aphelionz** [comment]
cc @autonome @achingbrain
