### ISSUE TITLE
Consolidating OrbitDB repos

### ISSUE THREAD

**Issue by tabcat** [orbitdb/orbit-db#917]
This issue will track consolidation of the OrbitDB repos.
The goal is to move multiple orbit-db repos used only by orbit-db into the main repository. This is in effort to simplify maintenance and publishing as well as making refactors for 1.0 easier to accomplish.
While doing this we will ensure that the modules retain their modularity even after they are no longer published as standalone packages. They will still be exported; likely via [package.exports](https://nodejs.org/api/packages.html#packages_exports) for simple import paths.

repos to be joined with the main repo:
- [ ] https://github.com/orbitdb/orbit-db-store
- [ ] https://github.com/orbitdb/orbit-db-counterstore
- [ ] https://github.com/orbitdb/orbit-db-feedstore
- [ ] https://github.com/orbitdb/orbit-db-kvstore
- [ ] https://github.com/orbitdb/orbit-db-eventstore
- [ ] https://github.com/orbitdb/orbit-db-docstore

Once joined the old repos will be deprecated. If you think a repo should be added or removed to/from this list leave a comment why.

**Comment by chrispanag** [comment]
In terms of this, have you considered moving to a monorepo style of development? Packages could still be published separately and maintenance/publishing/refactors will be way easier to accomplish. (Tests will run in one repo for all packages).

**Comment by tabcat** [comment]
we have [talked about it some](https://github.com/orbitdb/orbit-db/issues/320)
I think im going to refrain from changing the repos now and work on an implementation spec for 1.0 as that will probably give us a better idea on how this should be done.
closing for now
