### ISSUE TITLE
Calling load() periodically

### ISSUE THREAD

**Issue by mikelfried** [orbitdb/orbit-db#939]
Hello,

The field manual mention:

> • Calling load() periodically ensures you have the latest entries from a local database available in memory

I understand that the first load() will load all local data. So what is the advantage of calling load() periodically?

**Comment by tabcat** [comment]
i think things have changed since then; the field manual is dated in some places. you want to call load just once now and it will be called by default in the future.

**Comment by mikelfried** [comment]
Thanks! appreciate it
