### ISSUE TITLE
Error: No binary available for arch 'undefined' on Raspberry Pi 4

### ISSUE THREAD

**Issue by christroutner** [orbitdb/orbit-db#951]
I filed [this issue with the same title](https://github.com/ipfs/npm-go-ipfs/issues/46) in the npm-go-ipfs repository. The error information in that issue is originating from orbit-db due to the [go-ipfs dev dependency](https://github.com/orbitdb/orbit-db/blob/726e667a4f452876271a3a40d22999268cc8a3e2/package.json#L53). Is it absolutely necessary? An easy fix would be to remove it from the dependency list.

I verified the error occurs with the latest version of orbit-db (v0.28.1)

**Comment by tabcat** [comment]
We need go-ipfs for tests. It looks like the underlying issue is being fixed.

**Comment by christroutner** [comment]
I was able to overcome this issue by setting the following environment variable in Ubuntu:

- `export TARGET_ARCH=arm64`

**Comment by captaincole** [comment]
I also ran into this issue with a M1 macbook pro. I solved it the same way
