### ISSUE TITLE
AccessController get Key value

### ISSUE THREAD

**Issue by awcchungster** [orbitdb/orbit-db#954]
I am following the AccessController documentation. I am trying to find a way to obtain the key value for use in my AccessControllers. Does entry have a property like `key` when invoking `canAppend`?

```
async canAppend(entry, identityProvider) {
      // logic to determine if entry can be added, for example:
      if (entry.payload === "hello world" && entry.identity.id === identity.id && identityProvider.verifyIdentity(entry.identity))
        return true

      return false
      }
```

https://github.com/orbitdb/orbit-db/blob/afc85156f53757f08e8026485f6ac2e1fc3fb3bf/GUIDE.md#custom-access-controller

**Comment by tabcat** [comment]
entry.payload.key

https://github.com/orbitdb/orbit-db-kvstore/blob/019c6d98469c03096c6d13c5577ddf492678efab/src/KeyValueStore.js#L27
https://github.com/orbitdb/orbit-db-store/blob/f1461ce078fd58be6962cde6ad37980dfb29e811/src/Store.js#L434
https://github.com/orbitdb/ipfs-log/blob/2cb68814b98ba15f79a8dcf554f26c1505a5985e/src/log.js#L292
https://github.com/orbitdb/ipfs-log/blob/2cb68814b98ba15f79a8dcf554f26c1505a5985e/src/entry.js#L44

**Comment by CSDUMMI** [comment]
No, but the entry should be structuredout in the same manner as the entries of the oplog.

See [Oplog Documentation](https://github.com/orbitdb/orbit-db/blob/main/API.md#oplogvalues) for further details.

**Comment by awcchungster** [comment]
I can confirm the entries passed to the entry in `canAppend` are the opslog format. That means to access the variable I would do `entry.payload.key`.

Thanks for this awesome community
