### ISSUE TITLE
WARNING! Head hash didn't match the contents

### ISSUE THREAD

**Issue by CSDUMMI** [orbitdb/orbit-db#955]
When running this [code](https://codeberg.org/mutating-secrets-coin/Wallet/src/branch/main/src/main.js).

I receive multiple warnings like this:
```
"WARNING! Head hash didn't match the contents
```

I tried to figure out what could cause this error (because no traceback or explaination is given).

And this is what I came up with:

### Warning stems from `Store.js`

The call to `console.warn` is triggered in the [`Store.sync`](https://github.com/orbitdb/orbit-db-store/blob/f1461ce078fd58be6962cde6ad37980dfb29e811/src/Store.js#L327) function after a `head` object has been converted into an `Entry` and written to ipfs.

### Warning correlates with `replicate` event.
When logging the `replicate` events occurring on a db, these strongly correlate with the warnings.

After each warning a `replicate` and `replicated` event is triggered.

```
"WARNING! Head hash didn't match the contents
Replicating /orbitdb/zdpuB2Qa9TKSDNzFBjqQrw75RnMiPt8etGFiucEZDqD5rNxnc/claims-03d3d666383ceee1b24a781aaadd49b5e531698c052647983691d8c3baf58af010
```

### Warning appears to have no consequence.
Since this is a crucial part of the OrbitDB codebase, I'd like to know what this warning means in the context of OrbitDB.

What reason could there be for a head hash not to match the hash calculated by writing the corresponding entry to IPFS?

**Comment by tabcat** [comment]
Closed in community chat, has to do with Uint8Arrays not being supported inside entries yet.
