### ISSUE TITLE
Invalid multihash format in db address, how to read manifest ?

### ISSUE THREAD

**Issue by anarkrypto** [orbitdb/orbit-db#956]
The [GUIDE](https://github.com/orbitdb/orbit-db/blob/main/GUIDE.md#manifest) says that the second part of the db address is composed of a multihash that we can read using:
 `ipfs dag get <multihash>`

In fact, in the example we have a valid multihash format.

But the addresses I get is like: `/orbitdb/zdpuAuZ7jiofffFnQgGknfRseqi2zbmHYER75viguePqHUeGD/database-name
`

**zdpuAuZ7jiofffFnQgGknfRseqi2zbmHYER75viguePqHUeGD** is not a valid multihash and I cannot read from IPFS node.

**Comment by anarkrypto** [comment]
in reality, while it doesn't work with `ipfs cat <multihash>`, it works with `ipfs dag get <multihash>`

Fixed!

**Comment by tabcat** [comment]
I think `ipfs cat` is for ipfs files and we use ipld DAG objects encoded with CBOR.
