### ISSUE TITLE
Getting Error: Manifest 'test\_access' cannot be opened as 'test/_access' when starting node server

### ISSUE THREAD

**Issue by Nike1421** [orbitdb/orbit-db#980]
So, whenever I try to run the node server, I get this error: Error: Manifest 'test\_access' cannot be opened as 'test/_access'

    const ipfs = await IPFS.create({
        host: 'ipfs.infura.io',
        port: 5001,
        protocol: 'https'
    })
    const identity = await Identities.createIdentity({ id: 'test1' })
    const orbitdb = await OrbitDB.createInstance(ipfs, { identity })
    const optionsToWrite = {
        accessController: {
            type: 'orbitdb',
            write: [orbitdb.identity.id, identity.publicKey],
        },
    }
    const db = await orbitdb.docs('test', optionsToWrite)

    const app = express()

    app.use(express.json())

I am on Windows.
orbit-db is 0.27.1
ipfs is 0.59.1

Any idea how to solve this?

**Comment by tabcat** [comment]
You can upgrade to 0.28 where this bug won't cause an error to be thrown. Thank you for opening this.

**Comment by tabcat** [comment]
I'm not sure how this happened, unable to duplicate while checking out 27.1

The problem is the manifest name for the access manifest was 'test_access' instead of 'test/_access' somehow.

Let me know if upgrading the version changes anything.

**Comment by Nike1421** [comment]
Hey there!
Sorry I couldn't check earlier, but looks like upgrading orbit-db to 0.28 fixes the issue!

Thanks a lot @tabcat!

**Comment by tabcat** [comment]
@Nike1421 its not unlikely the underlying issue is simply not able to throw an error anymore (instead it may appear as a warning). I'd still like to follow through and see if the access controller's manifest.name is not matching it's database address.
