### ISSUE TITLE
Doc Node Version support out of date. NVM potential?

### ISSUE THREAD

**Issue by caleb-mabry** [orbitdb/orbit-db#985]
Hello! I hope everything has been going well,
Node Version: `v14.17.4`

When I was initially trying to set the code up to play around with, I noticed that I was receiving a weird error telling me
> class TimeoutController extends AbortController {
TypeError: Class extends value undefined is not a constructor or null

I checkout out the Element lobby and someone suggested upping your node version from v14 to v16. 
[I noticed the docs saying that it supports all even numbered node versions](https://github.com/orbitdb/orbit-db/blob/main/README.md?plain=1#L31)  but I didn't find that to be the case for my v14 node 😔

I was wondering if maybe the docs could be updated to specify that people should be using a node version >16?
[To kind of extend on that idea, adding a `.nvmrc` so users could `nvm use`](https://github.com/nvm-sh/nvm) and get the right node version might be helpful? Any thoughts?

**Comment by tabcat** [comment]
@caleb-mabry thanks for opening this, its probably needed like you suggest and I think a good plan moving forward is to support the latest lts version only, like the ipfs packages orbitdb needs.

**Comment by caleb-mabry** [comment]
This seems like a beginner friendly issue I could open a PR for since it's just a document change?

Any thoughts on including NVM support?

**Comment by tabcat** [comment]
Yea go for it, I love NVM
