### ISSUE TITLE
ideas for restructuring orbit-db-* repos/packages

### ISSUE THREAD

**Issue by tabcat** [orbitdb/orbit-db#987]
There are a few packages within the org that make up `orbit-db`. Here is a list of them:
```
orbit-db-store
orbit-db-counterstore
orbit-db-docstore
orbit-db-eventstore
orbit-db-feedstore
orbit-db-kvstore
orbit-db-access-controllers
orbit-db-identity-provider
orbit-db-io
orbit-db-pubsub
orbit-db-test-utils
orbit-db-storage-adapter
orbit-db-cache
orbit-db-keystore
```

While many of them deserve their own repo/package domain, there are a few that may be better joined or replaced. Some of the reasons for doing this have to do with what is required to test code and maintenance complexity.

Some changes I think would be worthwhile:

combined into orbit-db repo/package
```
orbit-db-store
orbit-db-counterstore
orbit-db-docstore
orbit-db-eventstore
orbit-db-feedstore
orbit-db-kvstore
orbit-db-access-controllers
orbit-db-identity-provider
```

combined in an orbit-db-utils repo
```
orbit-db-io
orbit-db-pubsub
orbit-db-test-utils
```

deprecated/replaced
```
orbit-db-storage-adapter -> https://github.com/ipfs/js-ipfs-interfaces/tree/master/packages/interface-datastore
orbit-db-cache -> https://github.com/ipfs/js-ipfs-interfaces/tree/master/packages/interface-datastore
orbit-db-keystore -> https://github.com/libp2p/js-libp2p/tree/master/src/keychain
```
> the datastore implementation we would use and support use with orbit-db would be https://github.com/ipfs/js-datastore-level

> the keychain takes an instance of libp2p as a parameter but only accesses its storage component which is a datastore
---

`ipfs-log` lists orbit-db-identity-provider in its dependencies but only uses it in tests, so it doesn't need to be a circular dependency. it may fit better in orbit-db-utils, an orbit-db-modules, or not being moved.

@haadcode @aphelionz

**Comment by tabcat** [comment]
wrt identities being used by `ipfs-log`, it could make sense to move access to a point before `ipfs-log`. this would also require separating the replication pieces out of ipfs log since access would be needed for traversal.

**Comment by aphelionz** [comment]
I think my favorite part out of all of this is:

```
orbit-db-storage-adapter -> https://github.com/ipfs/js-ipfs-interfaces/tree/master/packages/interface-datastore
orbit-db-cache -> https://github.com/ipfs/js-ipfs-interfaces/tree/master/packages/interface-datastore
orbit-db-keystore -> https://github.com/libp2p/js-libp2p/tree/master/src/keychain
```

This may solve a lot of the "packaging" issues that we inherit from `js-ipfs` like the one just mentioned in #988, and allow us to stay more up to date with the ecosystem at large.

As for the other refactors, I'm OK with them as long as they can provably improve the developer experience - I think your point about testing is a particularly good one 👍

**Comment by aphelionz** [comment]
If all of these end up in `orbit-db`:

```
orbit-db-store
orbit-db-counterstore
orbit-db-docstore
orbit-db-eventstore
orbit-db-feedstore
orbit-db-kvstore
orbit-db-access-controllers
orbit-db-identity-provider
```

then you can probably deprecate `orbit-db-test-utils` and put it back inside `orbit-db`

**Comment by aphelionz** [comment]
IMO these four should be dependency-injected so that people can write their own flavors:

```
orbit-db-access-controllers
orbit-db-identity-provider
orbit-db-io
orbit-db-pubsub
```

Additionally, `orbit-db-store` should still be extensible and people should be able to write and similarly dependency-inject their own store/index definitions into OrbitDB as well

**Comment by aphelionz** [comment]
The final thing to keep in mind is that `orbit-db` must remain isomorphic between `go-ipfs` and `js-ipfs`
