### ISSUE TITLE
Problem adding new keys for write permission

### ISSUE THREAD

**Issue by aitorru** [orbitdb/orbit-db#989]
Hi there! I been using this project in my final uni project. It's about SSI over the ethereum network and I added orbit-db as a mean to share data between users. My project is almost complete, but I'm facing a last issue. I use a smart contract to verify and share the identities.

Right now, a user can create a "room", and announce the event using the smart contract. The room is basically an orbit-db instance.
```js

	const handleCreateDB = async () => {
		if (!ipfs.current) return;
		// Create identity https://github.com/orbitdb/orbit-db/blob/main/GUIDE.md#creating-an-identity
		const Identities = require('orbit-db-identity-provider');
		let options = { id: account };
		const identity = await Identities.createIdentity(options);
		// Create instance
		// Mantain connection to pesist data
		const orbitdb = await OrbitDB.createInstance(ipfs.current, { identity });
		options = {
			// Give write access to yourself at first
			accessController: {
				write: [
					orbitdb.identity.id,
				],
			},
		};
                // Create key value db
		const db = await orbitdb.keyvalue(account, options);
		// Replicate db in local storage
		await db.load();
               // ...
};
```
When another user wants to enter into this room, it sends a request that the room creator can accept. Then the proposer, sends their identity so that it can get added to the db writers.
```js
const handleAcceptRequestToDatabase = async (identity, proposer) => {
		const jsonInterface = JSON.parse(identity);
		// Grant access to existing db.
		await DB.access.grant('write', jsonInterface.publicKey);
		console.log('Added pKey');
		// Contact smart contract
		contract.current.methods.acceptProposal(proposer).send({ from: account, gasPrice: '20000000000' });
                // ...
};
```
Lastly, the proposer needs to subscribe to the url.
```js
const handleConnectToPeerDatabase = async (url) => {
		if(!ipfs.current) return;
		// Create instance
		const orbitdb = await OrbitDB.createInstance(ipfs.current, { identity: OrbitDBidentity.current });
		// Connect to remote db
		const db = await orbitdb.open(url, {type: 'keyvalue'});
		setDB(db);
		// Replicate db in local storage
		await db.load();
}; 
```
At that point, I get an error saying that my id is not allowed to write to that DB. All these functions are executed in different browsers and the flow of data is correct because if I set the DB as public everything works.

> If you want to check the full code is at https://github.com/aitorru/tfg-self-sovereign-identity/blob/main/pages/upload.js

As I have read in the FAQ, the write protection is a WIP, but in the API.md document it doesn't mention anything. I suppose it might be a silly error on my side, but I can't seem to find it.

**Comment by tabcat** [comment]
What happens if you change
`await DB.access.grant('write', jsonInterface.publicKey);` -> `await DB.access.grant('write', jsonInterface.id);`

**Comment by aitorru** [comment]
> What happens if you change `await DB.access.grant('write', jsonInterface.publicKey);` -> `await DB.access.grant('write', jsonInterface.id);`

It happens the same :(. Out of curiosity I tried adding the publicKey, id and the whole JSON just in case, but it didn't work either.

**Comment by tabcat** [comment]
you still need to use the `.id` prop of the identity when granting access. its possible the access controller hasnt been replicated yet. It's also possible the cause is the access controller being loaded concurrently but this is less likely.

I recommend editing your orbit-db files in `node_modules` and see what is causing this. The first thing would probably be to log everything in https://github.com/orbitdb/orbit-db-access-controllers/blob/bf06527fc75d542460428a185fc83092a2523197/src/orbitdb-access-controller.js#L26

which you can find in `node_modules/orbit-db-access-controllers/src/orbit-db-access-controller.js`

**Comment by aitorru** [comment]
Great! Thanks for the help. I will keep you updated.

**Comment by aitorru** [comment]
Hey there, I was unable to debug the issue. I need to submit my work so I prefer to have an insecure but working demo, than a secure concept. I love the project and I hope to contribute to this project in the future. For now, as I lack free time, I'm closing the issue.
